### ISSUE TITLE
Shutting down `Manager.taskExecutor`

### ISSUE THREAD

**Issue by bensymonds** [outworkers/phantom#101]
I am really new to scala/java so apologies if this is a stupid question, but how should the `ExecutorService` created in `Manager` be shut down?

**Comment by velvia** [comment]
Is this no longer an issue with the removal of the Java driver in 1.8.0+?

**Comment by alexflav23** [comment]
@velvia I think there was a shutdown method added. In the newer version. Have a look [here](https://github.com/websudos/phantom/blob/ba777c2ed015834be87d0b1c518535897a1ac7fc/phantom-dsl/src/main/scala/com/websudos/phantom/Manager.scala).

**Comment by velvia** [comment]
Thanks, it seems to work - except for a weird bug running stuff from SBT.
