### ISSUE TITLE
phantom-zookeeper 1.4.0 has unresolved dependencies

### ISSUE THREAD

**Issue by anshumans** [outworkers/phantom#158]
SBT fails to resolve the following dependencies:

[warn]  :: com.twitter.common.zookeeper#server-set;1.0.83: not found
[warn]  :: com.twitter.common.zookeeper#client;0.0.60: not found
[warn]  :: com.twitter.common.zookeeper#group;0.0.78: not found
[warn]  :: com.twitter#finagle-zookeeper_2.10;6.17.0: not found

**Comment by prasadmahendra** [comment]
Finagle zookeeper appears to have disappeared from "maven.websudos.co.uk/ext-release-local"?

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter#finagle-zookeeper_2.10;6.24.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

I have the correct resolvers set:
resolvers += "websudos-repo" at "http://maven.websudos.co.uk/ext-release-local"

**Comment by MartinHerren** [comment]
Yeap, currently not possible to find com.twitter#finagle-zookeeper_2.10;6.17.0 required for Phantom 1.4.0
Not anymore on maven.websudos.co.uk/ext-release-local nor could i find it somewhere else. Phantom seems to want a ghost version of zookeeper :-)

**Comment by alexflav23** [comment]
@MartinHerren We will have to ask you to upgrade to either 1.5.0 or 1.5.1. Our Maven repo suffered some damage from AWS withdrawing hardware from use, some of the previous releases are now gone as a consequence. The 6.24.0 used by the latest phantom should however be available for both Scala 2.10 and 2.11.

**Comment by MartinHerren** [comment]
Yes thanks, that's fine, dependencies resolve fine now using 1.5.0
Now it's my code that doesn't compile, but this bug must be sitting in my chair ;-)
So now i can learn to use Phantom.

Thanks and best regards !

**Comment by sblask** [comment]
Seems like the Maven repository is down again? http://maven.websudos.co.uk/ext-release-local gives a 404

**Comment by alexflav23** [comment]
@sblask Yes it is indeed, some infrastructure changes have gone wrong as I was just informed. We are working on restoring everything back to normal and all phantom artefacts are now moving to Maven Central, to avoid situtations like this in the future.

**Comment by sblask** [comment]
Works now, thanks for the quick fix!

**Comment by alexflav23** [comment]
@sblask Glad to hear that and apologies for the service interruption!

**Comment by charlesa101** [comment]
@alexflav23: Looks like the repo is still down

`http://maven.websudos.co.uk/ext-release-local`

Taking a while to to resolve

**Comment by charlesa101** [comment]
@alexflav23: looks like the repo is still down

`http://maven.websudos.co.uk/ext-release-local`

**Comment by patrickotoole** [comment]
+1 http://maven.websudos.co.uk/ext-release-local is down...

it doesnt look like the artifact is available on mvn central either

**Comment by patrickotoole** [comment]
here's what I have as a work-around to the missing repository

```
git clone https://github.com/websudos/finagle-zookeeper/
git checkout feature/scala-2.11
# manually remove .configs(IntegrationTests) from project/Build.scala
sbt package
sbt make-pom
cp target/scala-2.11/finagle-zookeeper_2.11-6.24.0.pom pom.xml
mvn install
```

**Comment by charlesa101** [comment]
@patrickotoole  thanks!

**Comment by mkhudyakov-axon** [comment]
@alexflav23, any ideas, when http://maven.websudos.co.uk/ext-release-local could be up? any alternatives, the above solution doesn't work for me, where I have SBT 0.13:

```
finagle-zookeeper/project/Build.scala:13: value coreDefaultSettings is not a member of object sbt.Defaults
[error]   val baseSettings = Defaults.coreDefaultSettings ++ Seq(
[error]                               ^
[error] one error found
[error] (compile:compile) Compilation failed
```

**Comment by alexflav23** [comment]
@mkhudyakov-axon Get the bintray version. I've updated the README to show you how to get it. You are not using SBT 0.13 by the looks of it.

**Comment by thiagoandrade6** [comment]
Even using the bintray("https://bintray.com/websudos/oss-releases/"), I got

```
[error] sbt.ResolveException: unresolved dependency: com.websudos#phantom-dsl_2.11;1.8.4: not found
[error] unresolved dependency: com.twitter#finagle-zookeeper_2.11;6.24.0: not found
[error] unresolved dependency: org.cassandraunit#cassandra-unit;2.0.2.6: not found
[error] unresolved dependency: org.cassandraunit#cassandra-unit-parent;2.0.2.6: not found
[error] unresolved dependency: com.twitter#finagle-zookeeper;6.24.0: not found

**Comment by alexflav23** [comment]
@thiagoandrade6 Try `1.8.12` which is on Maven Central.

**Comment by thiagoandrade6** [comment]
Got the same

```
[error] sbt.ResolveException: unresolved dependency: com.twitter#finagle-zookeeper_2.11;6.24.0: not found
[error] unresolved dependency: org.cassandraunit#cassandra-unit;2.0.2.6: not found
```

Looks like the phantom-dsl is trying to get both, but none is found...

I'm using this resolvers

```
resolvers ++= Seq(
  "Typesafe repository snapshots"    at "http://repo.typesafe.com/typesafe/snapshots/",
  "Typesafe repository releases"     at "http://repo.typesafe.com/typesafe/releases/",
  "Sonatype repo"                    at "https://oss.sonatype.org/content/groups/scala-tools/",
  "Sonatype releases"                at "https://oss.sonatype.org/content/repositories/releases",
  "Sonatype snapshots"               at "https://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype staging"                 at "http://oss.sonatype.org/content/repositories/staging",
  "Java.net Maven2 Repository"       at "http://download.java.net/maven/2/",
  "Twitter Repository"               at "http://maven.twttr.com",
  "Websudos releases"                at "https://bintray.com/websudos/oss-releases/"
)
```

**Comment by thiagoandrade6** [comment]
Looking at http://maven.twttr.com/com/twitter/ indeed, I couldn't find any finagle-zookeeper library.

**Comment by alexflav23** [comment]
`"Websudos releases"                at "https://bintray.com/websudos/oss-releases/"` should be `Resolver.bintrayRepo("websudos", "oss-releases")` for SBT `0.13.6`+.

Otherwise, if you are using an older version of SBT, use `"https://dl.bintray.com/websudos/oss-releases/"`

**Comment by thiagoandrade6** [comment]
Great @alexflav23 that was the trick! I will send you a pull request updating the documentation, there  some broken links and in the resolver sections the older unavailable repo is still there.

Thanks anyway for your time.
