### ISSUE TITLE
Frozen collection

### ISSUE THREAD

**Issue by mmatloka** [outworkers/phantom#322]
Hi,
Is it possible to model in phantom the:
```
sth frozen<map<text,text>>,
```
?

Additionally frozen collection should be possible to use with primary key.

**Comment by alexflav23** [comment]
Hi @mmatloka,

Not at this time. We will add a feature request to be included in the roadmap, I think it's already there. Right now our focus is on prepared statements which are close to being done.

Regards.

**Comment by psycho-ir** [comment]
Hi @alexflav23 

I am going to contribute on UDT and frozen stuffs. 
As far as I understood from other issue comments you internally are working on UDT support (Please correct me if I am wrong).

Is it possible to work on it in a public github branch? then I will have opportunity to contribute on it.

**Comment by alexflav23** [comment]
Hi @psycho-ir,

What we have on UDTs is already in. Perhaps we will share the end DSL we are trying to achieve and we can start from there, see if you have better ideas about what DSL we can offer. Some minimal version of UDTs is already working, but our effort has been primarily targeting prepared statements and other efforts, so there has been a lot of work around that.

Regards.

**Comment by mmatloka** [comment]
hey, were frozen already included with udt? Now I need some more advanced scenario of ` map<int,FROZEN<tuple<decimal, text>>>` ;)

**Comment by alexflav23** [comment]
Hi @mmatloka,

Sorry for the late reply on this one, I think this is not yet implemented in the UDT part of the framework, we are still trying to find best ways for a number of things. The known way, which involves a lot of Shapeless, does work, but presents some challenges in IDE highlighting and whatnot.

Regards.

**Comment by alexflav23** [comment]
HI @mmatloka,

Frozen collections coming in 1.29.4, this is handled invisibly at driver level so if you use a list column together with a primary key, it will be automatically frozen in the schema. Apologies for the long winded delivery on this, I'm not exactly sure how it skipped the pipeline so far.

More advanced freezing is coming with tuple support in 2.0.0 as well, if you have any more advanced cases to address we can deal with those too now, as primitives are now infinitely smarter in phantom.

Regards.
