### ISSUE TITLE
Duplicate repository definition

### ISSUE THREAD

**Issue by skuppa** [outworkers/phantom#387]
I am using the `phandom-dsl_2.11:1.18.1` in my project.  The project is a multi module gradle project and one of the module is a cassandra module which uses the phandom library.  While compiling, I get the following error.
```
Processing of /Users/kuppas/.gradle/caches/modules-2/files-2.1/com.websudos/phantom-dsl_2.11/1.18.1/947cb508bedcbe1d05be074735746da4ce0dada7/phantom-dsl_2.11-1.18.1.pom failed:
    'repositories.repository.id' must be unique: bintraywebsudosossreleases -> https://dl.bintray.com/websudos/oss-releases/ vs https://dl.bintray.com/websudos/oss-releases/ in com.websudos:phantom-dsl_2.11:1.18.1
```

Looking at the pom (https://dl.bintray.com/websudos/oss-releases/com/websudos/phantom-dsl_2.11/1.18.1/:phantom-dsl_2.11-1.18.1.pom), it is clear that pom has duplicate repository definition for `bintraywebsudosossreleases`.  

Thanks,
-Sridharan

**Comment by alexflav23** [comment]
Hi @skuppa,

You are free to check the build definition yourself inside SBT, I don't see any duplicates. Obviously the `.pom` is generated on the fly and I'm not sure which part of the pipeline deals with that, I would assume SBT. We don't have any man power to spend on this at present times.

Regards.

**Comment by alexflav23** [comment]
Hi @skuppa,

Can you please confirm if this still persists in the most recent version of phantom?

Regards.
