### ISSUE TITLE
Create secondary index over primary key

### ISSUE THREAD

**Issue by fggarcia** [outworkers/phantom#428]
Try create table example:

object key extends StringColumn(this) with PartitionKey[String]
  object hotel extends StringColumn(this) with PrimaryKey[String] with ClusteringOrder[String] with Ascending
  object period extends DateColumn(this) with PrimaryKey[Date] with Index[Date] with ClusteringOrder[Date] with Ascending
  object cacheKey extends StringColumn(this) with PrimaryKey[String] with ClusteringOrder[String] with Ascending
  object datetime extends DateTimeColumn(this)
  object jsonValue extends BlobColumn(this)

Compile error:

[error]  object period inherits different type instances of trait Key:
[error] com.websudos.phantom.keys.Key[java.util.Date,com.websudos.phantom.keys.Index[java.util.Date]] and com.websudos.phantom.keys.Key[java.util.Date,com.websudos.phantom.keys.PrimaryKey[java.util.Date]]
[error]   object period extends DateColumn(this) with PrimaryKey[Date] with Index[Date] with ClusteringOrder[Date] with Ascending

Cqlsh console let me to create the secondary index over "period" field.

**Comment by alexflav23** [comment]
Hi @fggarcia,

This should now be adequately supported as of `1.25.4`. You should be able to simply mix in `Index[Type]` to a `PrimaryKey` and so forth with no issues.
