### ISSUE TITLE
What is the best way to alter tables with phantom

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#432]
If I just add columns I get errors during autocreate. What is the migration mechanism with phantom ?

Thanks
Lahiru

**Comment by alexflav23** [comment]
Hi @lahirug,

The mechanism is automated, but it's not available in the open source version. It works based on a `DiffConfig` where you can provide modes, for instance allow phantom to "override all" during development and things like that.

Starting with end of April you will be able to subscribe to a development license and use the more advanced automated features phantom offers.

Regards,
Flavian
