### ISSUE TITLE
Build fails for Cassandra 3.3 (and maybe 3.x?)

### ISSUE THREAD

**Issue by mmatloka** [outworkers/phantom#435]
The `com.websudos.phantom.builder.query.db.crud.CreateTest` tests fail, with
```org.scalatest.exceptions.TestFailedException: The future returned an exception of type: com.datastax.driver.core.exceptions.SyntaxError, with message: Invalid value for property 'caching'. It should be a map..```

**Comment by alexflav23** [comment]
Hi @mmatloka,

This has already been reported fortunately and it will be fixed very shortly. CQL was indeed changed to allow specifying multiple properties for a `caching` clause. Thank you for reporting this though, I will try to get a fix in sometime today.

Regards.

**Comment by alexflav23** [comment]
HI @mmatloka,

Thank you for reporting this, fixed in `1.25.0` pending more tests.
