### ISSUE TITLE
unresolved dependency: com.websudos#diesel-engine_2.11;0.2.4

### ISSUE THREAD

**Issue by mozartvn** [outworkers/phantom#439]
I use resolver 

"com.websudos" at "http://mvnrepository.com"

libraryDependencies

    "com.websudos" % "phantom-dsl_2.11" % "1.22.0",
    "com.websudos" % "phantom-connectors_2.11" % "1.22.0",
    "com.websudos" % "phantom-testkit_2.11" % "1.12.2",

When I compile in sbt, I catch issues : 

error] (*:update) sbt.ResolveException: unresolved dependency: com.websudos#diesel-engine_2.11;0.2.4: not found

Please help me solve this isses !
thanks in advance !

**Comment by alexflav23** [comment]
https://github.com/outworkers/phantom/wiki/Integrating-phantom-in-your-project
