### ISSUE TITLE
Test with LocalDate in PreparedQueryTest is failing

### ISSUE THREAD

**Issue by levinson** [outworkers/phantom#441]
The test "serialise and execute a primitives cassandra 2.2 prepared select statement with the correct number of arguments" in ```PreparedSelectQueryTest.scala``` is failing for me when run locally. My local machine has Cassandra 3.3 running.

The error message is: PrimitiveCassandra22(7b7d673f-0102-41b2-a99d-e52f6615e260,6216,9,**2016-03-16**) did not equal PrimitiveCassandra22(7b7d673f-0102-41b2-a99d-e52f6615e260,6216,9,**2016-03-17**).

If I update the column to be a DateTime instead of LocalDate then it works fine.

**Comment by alexflav23** [comment]
Use `DateTime`. Otherwise you are probably skewing timezones and things like that, I don't use how phantom could interfere there.

**Comment by levinson** [comment]
@alexflav23 -- I'm referring to a test in the phantom-dsl library that is failing.

**Comment by alexflav23** [comment]
Hi @levinson ,

I see, thank you for that. I will have a look.

**Comment by mmatloka** [comment]
Hmm, works for me, @levinson what is Your timezone?

**Comment by alexflav23** [comment]
Hi @mmatloka,

I think maybe we should force UTC in tests if possible, would make it more robust. I'm not sure how it defaults, but it sounds like it defaults to system timezone, in which case the real problem might be Cassandra's timezone in his setup different from the machine's setup. I don't think phantom interferes with timezones when writing/extracting dates. 

Regards.

**Comment by mmatloka** [comment]
Well the `LocalDate` itself is timezone independent, but underneath it is parsed using the `DateTime` and in every place where timezone is needed the UTC is provided, so clearly theoretically it already should not use anywhere the system one. Cassandra stores dates against the UTC, so it also should not be the issue "theoretically". Also I am not in UTC, so its additionally interesting :) It has to be some issue with `DateTime <-> LocalDate` conversion...

**Comment by levinson** [comment]
I am in the Pacific timezone (UTC−08:00). I observed this same behavior (failing tests) when running on my Macbook (which had Cassandra 3.3 installed with brew), and also on my Windows desktop which had Cassandra 3.3.0 service installed using the Datastax distribution.

The related test in PreparedInsertQueryTest is also failing for me with the same reason.

**Comment by alexflav23** [comment]
Hi @levinson @mmatloka ,

The tests are explicitly designed to pass only in the very front of the Big Ben tower clock at Westminster Palace. As you fly into Heathrow, take the Piccadilly Line eastbound, and change with the Jubilee Line at Green Park, then go to Westminster. As soon as you get out of the underground station you will be right in front of the Big Ben, and those tests pass with flying colours.

On a more serious note, I will look into it, the theory says everything should normalise to UTC by default, so no timezone nonsense should ever hit DB level.

Regards,
Flavian

**Comment by mmatloka** [comment]
https://github.com/outworkers/phantom/pull/453 it was missing UTC forcing in two places near from row conversion....

**Comment by alexflav23** [comment]
HI @levinson,

We can successfully close this thanks to @mmatloka.

Regards.
