### ISSUE TITLE
com.datastax.driver.core.exceptions.NoHostAvailableException

### ISSUE THREAD

**Issue by GoldenZero** [outworkers/phantom#445]
Hi,
Sometimes I'm getting this exception when trying to connect Cassandra service. 
the configuration as following:  
ConnectionThreshold: 50
ConnectionsPerHost: 256 

"com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: \/10.240.195.18:9042 (com.datastax.driver.core.TransportException: [\/10.240.195.18:9042] Cannot connect))\n\tat com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:220)\n\tat com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)\n\tat com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1393)\n\tat com.datastax.driver.core.Cluster.init(Cluster.java:162)\n\tat com.datastax.driver.core.Cluster.connectAsync(Cluster.java:341)\n\tat com.datastax.driver.core.Cluster.connectAsync(Cluster.java:314)\n\tat com.datastax.driver.core.Cluster.connect(Cluster.java:252)\n\tat com.websudos.phantom.connectors.DefaultSessionProvider.createSession(DefaultSessionProvider.scala:50)\n\tat com.websudos.phantom.connectors.DefaultSessionProvider.<init>(DefaultSessionProvider.scala:54)\n\tat com.websudos.phantom.connectors.KeySpaceDef.<init>(Keyspace.scala:63)\n\tat com.websudos.phantom.connectors.KeySpaceBuilder.keySpace(KeySpaceBuilder.scala:39)\n\tat models.common.BasicCassandraConnector$class.session(CassandraConnector.scala:29)\n\tat 

Any advice to make the connection more reliable?

**Comment by alexflav23** [comment]
This has nothing to do with phantom I'm afraid, so I'm not sure how much help I will be able to provide. Try increasing the connection timeout, it's the one thing sometimes happens on AWS and the like. I think you're looking at a late stage in the error log, at some point it should tell you it couldn't connect.

```scala
val Connector = ContactPoints(Seq(seedHost))
    .withClusterBuilder(_.withSocketOptions(
      new SocketOptions()
      .setReadTimeoutMillis(1500)
      .setConnectTimeoutMillis(20000)
    )).keySpace("bla")
```

**Comment by wirefly09** [comment]
I am having a similar issue and cannot seem to find a resolution. Was a solution to this found?
