### ISSUE TITLE
Materialized Views

### ISSUE THREAD

**Issue by vishramachandran** [outworkers/phantom#454]
Support for Materialized Views (Cass 3 feature) would be very useful

**Comment by alexflav23** [comment]
Hi @vishramachandran,

We are about to be release it, but it will not be available in the free version.

Regards.

**Comment by git4sun** [comment]
@alexflav23 is the feature released? how do I obtain a pro version?

**Comment by prettynatty** [comment]
I have the same question. How to get a commercial version? There is no information about it on website.
