### ISSUE TITLE
Inappropriate license

### ISSUE THREAD

**Issue by simonsouter** [outworkers/phantom#459]
The README claims the project is Open Source, yet the provided license is incompatible with the principles of Open Source software.  Either update README to make spurious restrictions clear, or provide a proper Open Source license (MIT/BSD).

**Comment by alexflav23** [comment]
HI @simonsouter,

Phantom is not open source in the strict sense of the definition, we are well aware and we will happily update the README. It's not the license that's inappropriate, it's perhaps the 2 words that mention phantom is open source. It isn't, but it is and will remain free to use, with the exception of pro variant which is completely separate.

Updates going live in a few minutes, thank you for reporting this.

Regards.

**Comment by jkpl** [comment]
What's the definition of free for this project? Free as in [freedom](https://en.wikipedia.org/wiki/Free_software) or free as in [freeware](https://en.wikipedia.org/wiki/Freeware)?

**Comment by alexflav23** [comment]
HI @jkpl,

Freeware is the best way to phrase everything, we are updating the README right now to reflect just that.

Regards.

**Comment by jkpl** [comment]
Some of the Phantom JARs are published Apache 2.0 license: http://mvnrepository.com/artifact/com.websudos/phantom-dsl_2.10/1.22.0

Can you clarify how Apache 2.0 fits in your licensing model?

**Comment by alexflav23** [comment]
Hi @jkpl,

We've added a few explanations [here](https://github.com/outworkers/phantom#license-and-copyright). According to your own previous question, phantom is freeware.  The Apache2 License is at best an unhappy display error on the MVN repository which we will trace up, phantom is not Apache2.

Again, to summarise, the license says if you only have a build time dependency on phantom, you have nothing to be worried about. 

Regards,
Flavian

**Comment by ches** [comment]
Too bad, I thought this was an exciting project.
