### ISSUE TITLE
Keys in CQLSyntax is incorrect for caching

### ISSUE THREAD

**Issue by fggarcia** [outworkers/phantom#463]
In object CQLSyntax the value of variable
val Keys = "KEYS"

it is used in sealed trait CachingQueryBuilder

def keys(qb: CQLQuery, value: String): CQLQuery = {
    quotedValue(qb, CQLSyntax.Keys, value)
  }

but it should be

ALTER TABLE destination_day_prices WITH caching = {'keys': 'ALL', 'rows_per_partition': 'NONE' };

keys != KEYS

is variable 'Keys' used in another places??

**Comment by alexflav23** [comment]
Hi @fggarcia,

I will correct the error, an easy oversight that's causing problems. I would expect CQL to be casing agnostic in such instances, but apparently not.

Regards.

**Comment by fggarcia** [comment]
Do you know when the fix will be release??

my question is if I wait for the new release or reverse the change

Thanks

**Comment by alexflav23** [comment]
Hi @fggarcia,

Today, next couple of hours at most.

Regards.

**Comment by alexflav23** [comment]
Hi @fggarcia,

This is going live today, apologies for not applying and releasing the fix any sooner, schedule got in the way as always.

Regards.

**Comment by alexflav23** [comment]
Hi @fggarcia,

`1.25.2` should now address this, available on Bintray shortly.

Regards.
