### ISSUE TITLE
GPL Licence Violation

### ISSUE THREAD

**Issue by fommil** [outworkers/phantom#466]
The following people (at least) have made contributions when the licence was the GPL https://github.com/outworkers/phantom/blob/61f197841d24084005fe85da06eebfbb51a24c80/LICENSE.txt

@creyer
@bjankie1
@benjumanji
@ezhulenev
@mmatloka
@juanjovazquez
@viktortnk
@sksamuel
@tperek
@evanfchan
@jenshalm

but you have unilaterally changed the licence to a proprietary licence against the terms of the GPL.

The Free Software Foundation have been notified.

**Comment by alexflav23** [comment]
Hi @fommil,

It would appear you are rather short of hobbies. Some of the people making contributions where either on our direct payroll or on the payroll of organisations collaborating with us at the time of their contributions.

Our license will not change from the proprietary model for the foreseeable future. Thank you for your time!

Regards.

**Comment by fommil** [comment]
There are several people who are not on your payroll.

**Comment by alexflav23** [comment]
Hi @fommil,

Of course, that is very true, however I do fail to understand your direct involvement in our choice of licensing.

We appreciate all your concern, we really do, but it seems our choice of licensing while not compatible with your principled approach towards free, libre and open source, has worked well within the community and based on the recent outburst of community feedback we are already working on dropping some of the restrictions currently in place.

All the best.

Regards,

**Comment by fommil** [comment]
it would appear that you did several licence changes, so you might be ok. Dec 25, 2014 Apache 2.0 => GPL https://github.com/outworkers/phantom/commit/66329e9390a571849531b42a9941a8ac38208af2

then Apr 16, 2015 https://github.com/outworkers/phantom/commit/dcc8a665328fcf492aef8e9f4fbe67ad4c7d60a2#diff-61e0bdf7e1b43c5c93d9488b22e04170

which means that all contributors between these dates were contributing to you on the terms of the GPL (unless you own the copyright transfer of your employees). Other than yourself, this amounts to

- @velvia https://github.com/outworkers/phantom/commit/438753e3400c4f2efe3fa0bcfeb1bedd96e89e14
- @elmalto https://github.com/outworkers/phantom/commit/71bb3137d80be1cbf46b282af5e608a5959c2486
- Jacek Sokol https://github.com/outworkers/phantom/commit/50b22d8e61a161eca2864e8586ea32af3dbb498e
- @D-Roch https://github.com/outworkers/phantom/commit/70a33027e8cad68e0abeeff27483e3c8ad40e7da
- @slouc https://github.com/outworkers/phantom/commit/fcdb5898d15c326c86d41b74fa0aec955e206ae1

Note that despite the LICENSE in your github repository, you have been distributing under Apache 2.0 until as soon as 5 Jan 2016 https://github.com/outworkers/phantom/commit/5809d1e237067c5a428c92564e68e107cf93af48 which means that any releases obtained via Maven Central until that date are available for forking.

**Comment by fommil** [comment]
@alexflav23 you appear to be under the impression that I am advising you. I am not. I am a Contributing Member of the Free Software Foundation and I will ensure that any violation of FSF Licences are enforced with the full rigour of the law, and that any misuse of FSF terms are corrected.

**Comment by simonsouter** [comment]
Phantom is distributed via Bintray with an Apache 2.0 license (https://bintray.com/websudos/oss-releases/phantom/1.25.1/view).  Presumably Phantom can be used under the Apache license terms it's published under?

**Comment by mmatloka** [comment]
@simonsouter hmm, pom on Bintray says 
``` 
       <license>
            <name>Apache-2.0</name>
            <url>https://github.com/outworkers/phantom/blob/develop/LICENSE.txt</url>
            <distribution>repo</distribution>
        </license>
```
but licence from this link is not Apache, hmm

**Comment by alexflav23** [comment]
Hi @simonsouter,

That's an issue with Bintray's licensing, they only accept known license forms in publishing, something we have already picked up with them long ago and still waiting for a reply. Once phantom is on Bintray in binary form however, either by means of Apache license or our effective license which is obviously not Apache, you can still use phantom in the very same way.

This newly found criticism is perhaps in some form grounded and we agree restricting tutorials and content by means of licensing was a rather extreme measure, however even that was grounded by endless support calls generated by bad and misrepresenting content other companies have published on phantom. We have no control over the ecosystem's quality control process, and a

At the same time, while there is virtue in debating the merits of free software and open source software and so on, please try to understand our commercial viability is also equally important, if you were a phantom contributor on a payroll I have no doubt you would expect your pay check on time, and in the grand scheme of things this is all the license does.

Short of copy pasting the entire codebase and rebranding it as your own product, in which case we'll have the necessary pleasure of sitting together in court, there is virtually nothing you are prohibited from doing with phantom from either Bintray or Maven Central.

Yes we are definitely more restrictive than an Apache 2 license as we are not Twitter or Google or Facebook with many billions in revenue or venture capital and we cannot afford to match their efforts just yet, but at the same time we strongly encourage everyone to take a slightly different perspective here.

In spite of all the very recent criticism of the past day, our license which is an almost exact replica of Typesafe's Slick license hasn't changed in very long time and yet phantom adoption and features have been growing at a staggering pace with no slowdown.

Our efforts of delivering free features, at our own expense and time have not slowed down at all, they have constantly picked up, and the overall quality of the project has also been constantly growing as a result. Is it perfect? Not by far, but it is also by a very very far margin the market leader in its small niche segment and many many thousands of codebases rely on it for their own products and services, which makes the necessity of strongly debating virtues of license rather pointless, as our approach was always means to an end as opposed to very strong political correctness.

And yes, we have mouths to feed, just like any other company in the world, it just so happens that some of our quote and quote "open source" is more strategically important than it would be for a company the size of Facebook, their open source efforts don't affect their bottom line at all or perhaps insignificantly.

We can spend days and weeks together with lawyers and create pixel perfect wording making sure a Pulitzer prize would be in order for our quality `LICENSE.txt`, followed shortly by the blessing of a resurrected Hemingway, but unfortunately none of that makes even the slightest dent in the world and does not help anyone other than giving them something to talk about over a beer and exercise their apparent upper hand knowledge in open source.

Is @fommil right in his appraisal of our license alongside the other critics? Yes and no. Perhaps we are not fully complaint with the licensing view points of the Free Software Foundation and from that angle it is correct to say the license needs improvements, but the simple reality is **we have never tried to be!**. We have tried to build the very best and most simple to use Scala integration product for Cassandra, and endeavour which by any measure has been hugely successful.

Is it GPL V2, or V3 or V15, or Apache or FSF compliant or whatever you like? Maybe not, but does has any of that truly made any difference whatsoever in the total amount of value phantom has delivered? The answer to that is a strong **NO**.

Regards,

**Comment by fommil** [comment]
I never asked you to use a free software licence. I wanted you to:

1. use clear language (it is now clearer, thank you)
2. not to violate the terms of the GPL. This must still be addressed and is a legal matter which will be resolved in the courts if you do not comply.

**Comment by alexflav23** [comment]
Hi @fommil,

All offending contributions will be reverted to preserve the IP rights of the respective contributors, as per your aforementioned listing.

Regards.

**Comment by fommil** [comment]
Thank you. I will contact FSF's legal department once this has been achieved and a new binary release has been made.

**Comment by simonsouter** [comment]
1. Slick's license is an Open Source BSD 2 Clause license: https://opensource.org/licenses/BSD-2-Clause.  Your License is proprietary.
2. A Professional Bintray account is required to host artefacts with proprietary license.

**Comment by alexflav23** [comment]
Hi @simonsouter,

1. That's a no on the first one I think, given we've based our license on theirs. Look [here](https://github.com/slick/slick/blob/master/LICENSE.txt).

2. We do have a professional Bintray account specifically for that purpose.

**Comment by fommil** [comment]
@alexflav23 you just pointed to a 2-Clause (Simplified) BSD Licence, which is what Slick now is.

**Comment by alexflav23** [comment]
@fommil Our license is almost identical, with the exception of prohibiting binary form redistribution.

**Comment by fommil** [comment]
@alexflav23 that doesn't change the fact that you pointed to Slick's 2-Clause (Simplified) BSD Licence. Please do not claim to use a similar licence. You are using a proprietary licence and must make that clear.

**Comment by tperek** [comment]
@fommil could you please explain how come I am included in this list? I created this account on 15th of February 2015 and since then I haven't made a single commit or contribution to _any_ project, nor do I appear among contributors of this particular one. I believe there must have been some mistake, and if so, could you remove me from the list of "suspects"?

**Comment by fommil** [comment]
@tperek you're not a "suspect". Outworkers are in violation. Actually I narrowed down the list above to the exact timeframe in question. You are listed by Outworkers on their README as a contributor https://github.com/outworkers/phantom#contributors You may wish to request removal from that page if you do not feel you wish to be associated with this project (I certainly wouldn't want to be).

**Comment by velvia** [comment]
Can someone please summarize how this impacts any of  us that is listed under the “offending changes” list?  

What about open source projects that use Phantom but are Apache2 licensed?

**Comment by fommil** [comment]
@velvia it doesn't just impact anybody under that list, other than Outworkers may need to contact you to seek permission to use your changes under their proprietary licence.

All downstream users of Phantom should read the licence more carefully.

**Comment by slouc** [comment]
I don't understand either. Instead of producing actual value, here we are discussing some legal mumbo jumbo that most of the people here don't even understand (including me). I added one single fix to a broken link in a readme file and here I am listed like some kind of criminal :) If I have to examine every license in detail every time I want to contribute to an open-source project, I will rather not contribute at all then be involved in this kind of nitpicking on whether the license was GPL V15 or V16. So much for open source.

**Comment by fommil** [comment]
@slouc incase you didn't notice, you didn't contribute to an open source project, you contributed to a proprietary software project. Please read the licence.

**Comment by slouc** [comment]
I thought that having pull requests enabled on the repo is a safe sign to contribute and fix a broken link if the guys have a broken link. I didn't know that I have to go through a ton of text every time I want to fix one line in a readme. Point taken, I will ask to be removed from the contributor list or whatever the needed course of actions may be. As for my future contributions, I will rather leave the code/documentation broken than trying to help and being involved in this mess one year later.

**Comment by alexflav23** [comment]
Hi @slouc,

Standing out in today's world is difficult and Fommil thought this is a valid attempt towards his 15 minutes of fame. 

Please don't concern yourself with such behaviour, it is very unfortunate we have to deal with such people, it it remains necessary.

Should you wish to be removed from the contributors list, that would be understandable.

Regards

Regards.

**Comment by alexflav23** [comment]
Hi @velvia,

Please accept our apologies for having to deal with this, we are dealing with a very toxic kind of behaviour that stands to benefit no one.

You are fully compliant with our license and always have been, including your open source work on FiloDB and so on.

**Comment by slouc** [comment]
Since my only contribution was the previously mentioned small fix in a broken link that you guys had in the documentation, yes, I would rather be removed than be further involved in this discussion. If I had made a significant contribution then I would probably have pursued further, but since it's a trivial one, I'd rather be excluded from the whole thing. Good work on the library, by the way. Fommil, don't you have something constructive to do rather than digging around and making up problems for people who produce a lot of value for the open source community?

**Comment by fommil** [comment]
@alexflav23 There is absolutely no need to resort to name calling. This is extremely unprofessional behaviour. I am pointing out a licence violation that you are responsible for that could result in legal proceedings. If anything, I'm helping you avoid the worst of it and you will receive no more support from me.

**Comment by velvia** [comment]
I would echo this sentiment.

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by fommil** [comment]
@slouc @velvia click the Unsubscribe button on the right.

**Comment by fommil** [comment]
@slouc once again, this is not an open source project. I suggest you look at my profile if you want to see who is contributing to open source.

**Comment by slouc** [comment]
Point on the project not being open source is clear, I'm not talking about that. I'm not defending the phantom project and claiming that it's open source. I simply don't see the point of this whole discussion if no one got hurt. It's not like someone complained or anything. If I contributed to a proprietary software instead of open source software, so what? It's their software. I don't see them having problems with me helping them, or me having problems with them owning my contribution. It's a win-win situation for everyone - me, outworkers and all the users who were reading the docs. Why make a problem out of it, especially one year later?

**Comment by fommil** [comment]
@slouc Several contributors above submitted contributions under the GPL and Outworkers stole their work and distributed it under a proprietary licence. If you're not one of the people affected, then please do not feel the need to be involved any further.

**Comment by alexflav23** [comment]
Hi @slouc,

Yes we stole a couple of single line commits and broken link fixes and made a fortune selling it for the Grand Price of absolutely nothing. We are the evil empire.

@velvia I appreciate your sentiment, however professionalism has absolutely nothing to do with any of these current events or their motivation.

Regards.

**Comment by slouc** [comment]
@fommil If those people feel that their work has been stolen from them and "privatized" while they meant it to be open-source, then that's a completely different thing. But in that case it should be clear who got damaged and for what. My impression is that you simply came in here causing friction when there was none. If the damaged parties indeed do feel damaged, then I understand, but I don't see anyone having problems with that other than you. I thought @velvia was echoing my sentiment, not sentiment towards outworkers. Anyways, @alexflav23 please do remove me from the contributors list, my tiny contribution is not worth all this mess :) thanks and keep up the good work (I mean the actual work; I don't want to comment on the legal mumbo jumbo any further)

**Comment by fommil** [comment]
@slouc well your impression is incorrect. I came here to explain the violation and help everybody to work through what is a very serious situation. Flavian has turned vindictive and will be getting no more help from me. He can explain himself to the FSF legal team when they get in contact.

**Comment by alexflav23** [comment]
Hi @fommil,

Yes you are extremely helpful, please forgive me if I somehow failed to highlight that, I look forward to clearing this "very serious matter" with the FSF. Meanwhile, I am extremely confident your wide legal expertise is highly applicable to a broad range of other projects.

All the best!

Regards.
