### ISSUE TITLE
Does phantom support the datastax setFetchSize method?

### ISSUE THREAD

**Issue by richbolen** [outworkers/phantom#468]
I'd like to set the fetch size for queries.  Is this possible with phantom?

**Comment by alexflav23** [comment]
Hi @richbolen,

`Table.select.where(_.id eqs id).fetch(_.setFetchSize(20))` should work.

**Comment by richbolen** [comment]
Do you know what version of phantom this is supported in?

**Comment by alexflav23** [comment]
Hi @richbolen,

Definitely one of the most recent ones, try the latest available.

**Comment by alexflav23** [comment]
@richbolen,

Have you managed to use this successfully? Please let me know so I can close this ticket. 

Regards.

**Comment by richbolen** [comment]
It works in the most basic use case so you can close this ticket.  

But I have a fairly complex situation so I could use some guidance.  We're using a modified version of your driver that is based on version 1.12.2 of phantom.  I modified it to add full support for case sensitive table and column names and support for INSERT JSON/SELECT JSON.  Your latest version supports INSERT JSON but not SELECT.  As far as I can tell it does not support case sensitive table/column names either.  So I have to take your latest version and modify it to add these features.  Am I correct that it does not support these things?

**Comment by alexflav23** [comment]
Hi @richbolen,

If you already have the code, you could easily send a pull request and I am very happy to review, merge, and release a new version for you.

Also, as per our license, custom binary distributions aren't allowed, if this was your reason for not upgrading, the license was the same for `1.12.2` as well, you can have a look at that [here](https://github.com/outworkers/phantom/blob/b10e9f24cc0b5c9402bbddd251ccd54e782af896/LICENSE.txt), and I would be grateful for your support here.

Now that aside, it would be very easy to send us a small snippet for the select JSON and case sensitivity, although I am not 100% aware of any issues around that.

Regards.

**Comment by richbolen** [comment]
Pull request sent.  My apologies on the license.  We're not distributing your jar, but I'll make sure we stay within the license from now on.  

Another feature we need is support for the USING INGORE_NULLS clause for INSERT/UPDATE.  I'd be happy to add that and do another pull request if it will help.  It looks like you may have added support for the USING clause in your most recent versions, so maybe it's already there.

**Comment by alexflav23** [comment]
Hi @richbolen ,

I'm not aware of the `USING IGNORE_NULLS`, we will trace it up and add it. If there's more stuff missing, please never hesitate to create issues here, we have always addressed the vast majority of support issues within at most a few days, most on the same day.

Regards.

**Comment by richbolen** [comment]
Do you want me to create an issue for "USING IGNORE_NULLS"?

**Comment by alexflav23** [comment]
Hi @richbolen,

I've already added that internally, but for tracking purposes you can if you would like to.

Regards.

**Comment by alexflav23** [comment]
Hi @richbolen,

I am going to close this issue as we now have individual issues to track for everything here:

- Ability to use case sensitive table names(well in progress, still a bit of work to do. It introduces non trivial complexity on our part to adequately allow efficient configuration of all tables and so on).
- Ability to specify `USING IGNORE_NULLS` clauses . This is already done.
- Ability to use `SELECT JSON`, which will also be part of the next release.

Hope this helps.
