### ISSUE TITLE
Incorrect association of a contributor to his Github profile

### ISSUE THREAD

**Issue by tperek** [outworkers/phantom#469]
Please remove me (@tperek) from the [list of Contributors in project's README file](https://github.com/outworkers/phantom#contributors) or at least please remove the link to my profile. There might have been a contributor with the same name, but it definitely wasn't me.

**Comment by alexflav23** [comment]
Hi Tomasz,

I was probably the one to add you to the contributor list all those years ago when we worked together at Newzly. Perhaps this is the wrong username altogether.

We are simply dealing with a case of someone after their 15 minutes of fame, in lieu of real skill it seems such unfortunate measures are necessary.

**Comment by fommil** [comment]
@alexflav23 once again there is no reason for name calling, this is very unprofessional behaviour.

**Comment by alexflav23** [comment]
All done, going live in the next release.
