### ISSUE TITLE
SASI index support

### ISSUE THREAD

**Issue by mmatloka** [outworkers/phantom#473]
Is it also planned for `phantom-pro` ?

**Comment by alexflav23** [comment]
Hi @mmatloka,

No, this is planned for the normal phantom, it will be out in the next 2 -3 weeks at most hopefully.

Regards.

**Comment by mmatloka** [comment]
> No, this is planned for the normal phantom, it will be out in the next 2 -3 weeks at most hopefully. 

Great!

> it will be a cheaply priced tool for an entire team of developers to get, and we'll happily offer you a discount for all your contributions.

Nice, thanks :)

**Comment by alexflav23** [comment]
Hi @mmatloka,

This is finally coming out Friday, apologies for the delay on it, lots of fun stuff and huge amounts of work going into phantom-pro, it's more fun to keep up these days.

Regards

**Comment by git4sun** [comment]
@alexflav23 which version includes the sasi support and is there an example? Thanks.

**Comment by husam-otri** [comment]
@git4sun can you please confirm please if [http://search.maven.org/#artifactdetails%7Ccom.outworkers%7Cphantom-dsl_2.11%7C2.0.0%7C](phantom_dsl v2.0 ) supports SASI index? 

Thanks

**Comment by git4sun** [comment]
@husam-otri I tried the 2.0.0 briefly. Didn't find a specific SASI index support. Since I didn't find any document, it is possible that it is supported and I just didn't find it. Or the `with Index` is using SASI index. @alexflav23 could you please confirm?

**Comment by alexflav23** [comment]
@mmatloka @husam-otri @git4sun SASI support finalising on #698, should be live this week in phantom 2.11.0.

**Comment by alexflav23** [comment]
Fixed in 2.11.0, live on Maven Central shortly.

**Comment by git4sun** [comment]
This is great. We've been waiting for this. Thanks @alexflav23

**Comment by husam-otri** [comment]
Great thanks @alexflav23
