### ISSUE TITLE
Connect to cassandra with PasswordAuthenticator

### ISSUE THREAD

**Issue by dgomezs** [outworkers/phantom#475]
hi guys, first of all thank you very much for this great project. I have been using it in a new product Im about to launch and it has been great help. 

Now that I will be going to prod soon I wanted to enable authentication on my cassandra connection. Is there an example of how to do this with phantom? I couldnt find any.  

For ref I'm using 1.22

thank you very much in advanced. 
Best

**Comment by alexflav23** [comment]
Hi @dgomezs,

It's really easy to setup any cluster properties you want.

```scala
val connector = ContactPoint.local.withClusterBuilder(
    _.withAuthProvider(new PlainTextAuthProvider("user", "pass"))
  ).keySpace("play-phantom")
```

Hope this helps, all you need is the `withClusterBuilder` call.

Regards,

**Comment by dgomezs** [comment]
Great i'll give it a try
