### ISSUE TITLE
Allow index on Optional columns

### ISSUE THREAD

**Issue by mmatloka** [outworkers/phantom#478]
Issue described on gitter. Creating on github to be not forgotten :)

Currently:
```
object abc extends OptionalStringColumn(this) with Index[Option[String]] 
```
```
select.where(_.abc eqs Some("aa")).fetch() 
```
gives `eqs is not member of abc`.

such cqls work (it is just not possible to put null in where condition):
```
create table test2(id text primary key, value int, value2 int); 
create index someindex on test2(value2); 
insert into test2(id, value, value2) values ('a', 1, 1); 
insert into test2(id, value, value2) values ('b', 2, 2); 
insert into test2(id, value) values ('c', 1); 
select * from test2 where value2=1;
```

**Comment by alexflav23** [comment]
Hi @mmatloka,

Thank you for reporting this, we will work to get it out in the next release, should be 3 - 4 days from now.

Regards,

**Comment by mmatloka** [comment]
hey @alexflav23 what's the status of this issue? :)

**Comment by alexflav23** [comment]
Hi @mmatloka,

We've been swamped with work lately, so no one had a go at this, but I think by the end of the week we should have a release out. Hopefully this suits your schedule as well.

**Comment by alexflav23** [comment]
Hi @mmatloka,

Finally got round to implementing this bit of functionality, with apologies for the delay, how do you expect to handle situations where the underlying value is a `None`? By your own words you cannot use nulls in the where clause, so how can we handle that side of things efficiently to meet your expectation as library consumer?

Regards

**Comment by mmatloka** [comment]
Hi @alexflav23 ,
I would just expect that the `where` function would take as argument specific type instead of the `Option`, where the rest of operations like update etc still would take `Option`.

**Comment by alexflav23** [comment]
Hi  @mmatloka,

This is now implemented and will be part of the next incremental release, which should happen today.

Regards.
