### ISSUE TITLE
Stream never ends

### ISSUE THREAD

**Issue by thiagoandrade6** [outworkers/phantom#479]
I tried to reach you guys through Gitter, but no luck, also no problems.

I'm using the ```select.fetchEnumerator()``` method to streams results from cassandra to my akka streams with the following code:

```
val enumerator = select.fetchEnumerator() andThen Enumerator.eof
Streams.enumeratorToPublisher(enumerator)
```

Without the ```andThen Enumerator.eof()``` the stream never ends, so the question is, should this piece of code be part of the fetchEnumerator or not? Should the developer (me) in this case, implement it anyway? 

Is that a expected result?

**Comment by alexflav23** [comment]
Hi @thiagoandrade6,

I think you may be using the wrong API for streams, we have a dedicated `reactive-streams` module for such compatibility. `fetchEnumerator` is mostly intended to be used with the Play interfaces phantom providers, such as:

```scala
val counter: AtomicLong = new AtomicLong(0)
    val result = TestDatabase.primitivesJoda.select.fetchEnumerator run Iteratee.forEach {
      r => counter.incrementAndGet()
    }
```

Another possible use case is:

```scala
    val result: Future[Iterator[Record]] = TestDatabase.primitivesJoda.select.fetchEnumerator run Iteratee.drop(10)
```

Sounds to me like the `Streams.enumeratorToPublisher` is the one who should force  `andThen Enumerator.eof`. I am sure the play apis we are using for running ops on Iteratees, such as the various implementations of `fold` available, do add the `Enumerator.eof` manually at certain points, this was simply not necessary so far. As we cannot interfere with the current implementation inside Play, you are best adding this yourself, however it is indeed a bit surprising.

**Comment by thiagoandrade6** [comment]
Hi @alexflav23 Thanks for your message.

Well, unfortunately your streams library do the same, the stream never ends.

I tried the following code:

```
import com.websudos.phantom.reactivestreams._

val songs = Source.fromPublisher(database.songsModel.publisher())

    val x = songs.runForeach(println)

    println(Await.result(x, 10.seconds))
```

The last line should result in a ```Done``` but gives me TimeoutException.

```
07:34:15.014 [main] DEBUG com.websudos.phantom - Executing query: SELECT * FROM test.songs;
Song(97f8e7a0-07ac-11e6-8bec-d9441f658ef8,Prison Song,Toxicity,System of a Down)
Song(97fba6c0-07ac-11e6-8bec-d9441f658ef8,Toxicity,Toxicity,System of a Down)
Song(97fb7fb0-07ac-11e6-8bec-d9441f658ef8,Aerials,Toxicity,System of a Down)
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at com.cassandra.phantom.modeling.test.stream.SongsStreaming$.main(SongsStreaming.scala:55)
	at com.cassandra.phantom.modeling.test.stream.SongsStreaming.main(SongsStreaming.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 130
```

whereas the expect result should be the following: (using the enumerator with eof at the end)

```
07:37:54.178 [main] DEBUG com.websudos.phantom - Executing query: SELECT * FROM test.songs;
Song(1a9ca930-07ad-11e6-92c1-d9441f658ef8,Prison Song,Toxicity,System of a Down)
Song(1a9f6850-07ad-11e6-92c1-d9441f658ef8,Toxicity,Toxicity,System of a Down)
Song(1a9f4140-07ad-11e6-92c1-d9441f658ef8,Aerials,Toxicity,System of a Down)
Done
```

**Comment by alexflav23** [comment]
Hi @thiagoandrade6,

The underlying implementations are not something we control, phantom adds some rather basic syntactic sugar on top of streams to make it look like they are built in house, but the reality is anything to do with streams is delegated to the appropriate library.

I'm happy to make any improvements necessary here, but I'm not sure if forcing `Eof` may have other implications, we will need to test for that first and if there are no issues we can certainly make sure that step is always executed at library level.

Regards.

**Comment by thiagoandrade6** [comment]
Ok, makes sense.

For now I will keep the ```Eof``` on my side, no problems.

Thanks for your time.

Regards,
Thiago
