### ISSUE TITLE
Upgrade to java-driver 3.0.1

### ISSUE THREAD

**Issue by mmatloka** [outworkers/phantom#482]
https://github.com/datastax/java-driver/blob/9583163388096cd066254df7af99ceffc7911fbb/changelog/README.md

**Comment by alexflav23** [comment]
Hi @mmatloka,

Thank you for this, I've already bumped things internally, now we are dealing with the list of new features in CQL and so on, this will go live together with the optional indexes you've been waiting for hopefully today, if not tomorrow.

Regards,
Flavian

**Comment by alexflav23** [comment]
Hi @mmatloka,

Shipped in 1.26.0, alongside a relatively big changelog. In short, phantom-dsl got a lot thinner, we removed all the twitter deps and a bunch more stuff, you can do indexes on primary keys and a few more items.

I've left the changelog to be the last bit as I'm still not sure what the full scope will be, we are including very small last minute stuff here and there.

Regards.
