### ISSUE TITLE
Support Overriding Name of Column 

### ISSUE THREAD

**Issue by coreyauger** [outworkers/phantom#486]
I have recently migrated from 1.11 to 1.25.4

I have a column that is named `provider`
This now clashes with a field in the base type for the `CassandraTable`

Here is an example:
`object provider extends StringColumn(this)`

Does it seem reasonable to have a trait or some other mechanism for overriding the functionality seen in:
https://github.com/outworkers/phantom/blob/develop/phantom-dsl/src/main/scala/com/websudos/phantom/column/AbstractColumn.scala

```scala
private[this] lazy val _name: String = {
    cm.reflect(this).symbol.name.toTypeName.decodedName.toString
  }
```

something like:
`object prvdr extends StringColumn(this) with NamedCol("provider")`

Thoughts ?

**Comment by alexflav23** [comment]
Hi @coreyauger,

```scala

class MyTable extends CassandraTable[..] {
  object column extends StringColumn(this) {
    override def name = "bla"
  }
}
```

**Comment by coreyauger** [comment]
hehe.. right sorry.  Thanks :)
