### ISSUE TITLE
Delete multiple values at once

### ISSUE THREAD

**Issue by mmatloka** [outworkers/phantom#491]
Is it possible to perform delete of multiple values in one query in phantom, I mean e.g. `delete attributes['ab'], attributes['ac'] from xyz where id = ...; `  from map column?

**Comment by alexflav23** [comment]
Hi @mmatloka,

Apologies for the late reply, I don't think we support that chaining just yet, I think we only do that for update queries, but I can create a ticket and make sure there is an appropriate variant, that's not a problem. As always thank you for reporting the issue.

Regards.

**Comment by alexflav23** [comment]
Hi @mmatloka,

This will go live in 1.26.3, CI building finishing up as I type this.

Regards.
