### ISSUE TITLE
select another node when connection is lost to that node

### ISSUE THREAD

**Issue by fggarcia** [outworkers/phantom#495]
I only want to know if phantom can change the method that use when phantom lost connection with cassandra?

Today, it keep the reference to the same node until the node is restarted. Can phantom be configure to choose another node??

**Comment by alexflav23** [comment]
HI @fggarcia,

This is done automatically, and you shouldn't really be trying to manage this yourself. You can make some changes to the load balancing policy using the `ClusterBuilder` and `withClusterBuilder` equivalent but this is very difficult to manage.

```scala
val connector = ContactPoint.local.withClusterBuilder(_.withLoadbalancingPolicy(...))
```

Regards.
