### ISSUE TITLE
How to create User defined types?

### ISSUE THREAD

**Issue by annovi** [outworkers/phantom#496]
I saw that a new module UDT was added to your library, in 2014, to support User defined types: 

`CREATE TYPE address (
      street text,
      city text,
      zip int
  );
  
  CREATE TABLE user_profiles (
      login text PRIMARY KEY,
      first_name text,
      last_name text,
      email text,
      addresses map<text, frozen<address>>
  );`
http://www.datastax.com/dev/blog/cql-in-2-1

However I could not find an example online that describe how to do that, a part from this: 
http://stackoverflow.com/questions/34633440/phantom-dsl-cassandra-with-frozen-type

I guess there should be a simple way to solve this problem. I guess I have to extend the Primitive Data type.
Can you please provide an example code (or documentation) similar to this one (that is really useful): http://outworkers.com/blog/post/a-series-on-phantom-part-1-getting-started-with-phantom but that create and use a specific User defined type?

**Comment by alexflav23** [comment]
Hi @annovi,

Support for the following:

- UDTs via annotations
- Native Spark support(Complete phantom based re-implementation of Cassandra spark support)
- Automated table migrations
- Support for Solr/DSE integration

Are all available exclusively in our subscription based `phantom-pro`. All the revenue from this product is 100% re-invested into producing more open source content(phantom, reactiveneo) and so on.

An example usage for UDTs:

```scala

@udt
case class CustomUdt(name: String, firstName: String, age: Int)

case class Record(
  id: UUID,
  timestamp: DateTime,
  flag: Boolean,
  custom: CustomUdt
)

abstract class MyTable extends CassandraTable[MyTable, Record] {
   object id extends UUIDColumn(this) with PartitionKey[UUID]
   object timestamp extends DateTimeColumn(this)
   object flag extends BooleanColumn(this)
}
```

**Comment by annovi** [comment]
So what you are saing is that the example that you provide is not working yet, with the current version  of the library?
The current implementation should support "UDTs via annotations" is it correct?
In that case I will probably try to figured out myself.

Thank you.

**Comment by alexflav23** [comment]
Hi @annovi,

The example I provide will not be available in the OSS version at all. It's part of `phantom-pro` and that's what it looks like, this particular feature is well under completion/testing internally so I was able to give you a realistic example of how udts will be used.

The open source phantom here on GitHub has no explicit support for UDTs whatsoever, but you could use things like `JsonColumn` to define the same thing just as well, until the pro version comes out. If you like, send me an email and I will add you to the list of people automatically notified of any updates to phantom-pro, you will also get an early bird discount if you are on this list.

You can reach me at `flavian@outworkers.com`.

Regards.
