### ISSUE TITLE
How to delete key - value pair from map

### ISSUE THREAD

**Issue by shadius** [outworkers/phantom#497]
The CQL syntax to delete from a map is:
    DELETE m['key'] FROM foo WHERE k=1

The equivalent with QueryBuilder is:
    delete().mapElt("m", "key").from("foo").where(eq("k", 1));

Is there any way how to do similar thing using phantom API?

**Comment by alexflav23** [comment]
Hi @shadius,

Yes there is:

```TestDatabase.recipes.delete(_.props("test")).future()```

Regards.
