### ISSUE TITLE
autocreate leads to cluster inconsistency

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#499]
Hi Devs, 

I am not quite sure this is the right place to ask but just trying out. We use phantom and do the autocreate to create tables and pointing to a Cassandra cluster with 3 nodes. In our server code we have multiple modules and each has its own CassandraDB object which extends DatabaseImpl and it contains all the tables but all of these tables will be in single keyspace. 

When we start the server most of the time i see Column family ID mismatch error in the cluster. Is this something to do with the way phantom doing autocreate ? Should we use separate keyspaces if we are using different DatabaseImpls. One of our CassandraDB's looks like this.

```
class CassandraDB(system: ExtendedActorSystem) extends DatabaseImpl(CoreCassandraDB.keyspaceDef(system)) with Extension {
  val keySpace = KeySpace(connector.name)

  object sessionEventLog extends SessionEventLog with connector.Connector
  object sessionsByDomainMeetingClient extends SessionsByDomainMeetingClient with connector.Connector
  object sessionsByMeetingUuid extends SessionsByMeetingUuid with connector.Connector
  object sessionsByPrincipalId extends SessionsByPrincipal with connector.Connector

  object meetingEventLog extends MeetingEventLog with connector.Connector
  object meetingsByDomain extends MeetingsByDomain with connector.Connector
  object meetingsByUuid extends MeetingsByUuid with connector.Connector

  object userActivitiesByDay extends UserActivitiesByDay with connector.Connector
  object userActivitiesRollingSum extends UserActivitiesRollingSum with connector.Connector
  object userActivitiesByMonth extends UserActivitiesByMonth with connector.Connector
  object userCallsByDay extends UsersCallsByDay with connector.Connector
  object userCallsByMonth extends UsersCallsByMonth with connector.Connector
  object userCallsRollingSum extends UsersCallsRollingSum with connector.Connector

  object domainActivities extends DomainActivities with connector.Connector
  object domainCalls extends DomainsCalls with connector.Connector
  object streamEventLog extends StreamEventLog with connector.Connector
  object streamsByMeetingUuid extends StreamsByMeetingUuid with connector.Connector

  @BeanProperty
  object videoQualityByMonth extends VideoQualityByMonth with connector.Connector
  object videoQualityBySessionId extends VideoQualityBySessionId with connector.Connector

  system.registerOnTermination {
    session.getCluster.close()
    session.close()
  }

  @annotation.varargs def loggedBatch(list: Seq[ExecutablePreparedQuery]*): CompletionStage[ResultSet] = Batch.logged.add(list.flatten: _*).future()
}

object CassandraDB extends ExtensionId[CassandraDB] with ExtensionIdProvider {
  override def createExtension(system: ExtendedActorSystem): CassandraDB = CassandraDB(system)

  override def lookup(): ExtensionId[_ <: Extension] = CassandraDB

  override def get(system: ActorSystem): CassandraDB = super.get(system)

  def registerCodecs = {
    val codecRegistry: CodecRegistry = CodecRegistry.DEFAULT_INSTANCE
    codecRegistry.register(new OffsetDateTimeCodec)
    codecRegistry.register(new InstantCodec)
    codecRegistry.register(new ZoneOffsetCodec)
  }

  registerCodecs
}
```

**Comment by lahirug** [comment]
``

**Comment by alexflav23** [comment]
HI @lahirug,

We are aware this happens, however it has nothing to do with phantom and I'm not sure there is a lot that ca be done from a client perspective. The details are outlined in [CASSANDRA-8387](https://issues.apache.org/jira/browse/CASSANDRA-8387).

Auto-create is not necessarily doing any advanced schema migrations, it's simply going through the tables you nest inside a database and mapping every query to a `CREATE IF NOT EXISTS` schema variant, using lightweight transactions.

And then it uses `Future.sequence` so you can execute all creation futures in parallel, so there isn't necessarily a lot of control we exercise at driver level over Cassandra behaviour. Not the most helpful answer, but hopefully it does shed some light onto the internals.

The Cassandra ticket will contain more detail on how to address such things.

Regards,
Flavian

**Comment by lahirug** [comment]
Hi Alex,

Thanks for the response, we are not trying to create same table in two different places but use same keyspace. Still this column family mismatch error should come ?

Lahiru

**Comment by alexflav23** [comment]
Hi @lahirug,

I would be pretty confident in telling you the column id mismatches don't really come from the driver or phantom as there are no references kept.

The issue is you have an impedance mismatch between things like commit logs and disk files/ss tables for schemas, which is the real problem at hand. There isn't much we can do from a driver perspective.

Regards,
