### ISSUE TITLE
Support for "USING IGNORE_NULLS" clause in INSERT/SELECT queries

### ISSUE THREAD

**Issue by richbolen** [outworkers/phantom#501]
Does your driver support this?  We need it for our system.  BTW, This clause will allow you to insert sparsely populated objects and Cassandra will not create tombstones for all the null fields.  This prevents errors from queries where there are too many tombstones.

**Comment by alexflav23** [comment]
Hi @richbolen,

This just went in `1.26.5`, it will be released live shortly when CI finishes.

Regards.

**Comment by alexflav23** [comment]
Hi @richbolen,

`1.26.6` is now on Maven Central with the above feature included.

**Comment by alexflav23** [comment]
Hi @richbolen Not sure if you've seen this: https://github.com/outworkers/phantom/blob/develop/docs/basics/tables.md#the-name-of-the-table-can-be-controlled-using-namingstrategy
