### ISSUE TITLE
compile phantom-sbt plugin against scala 2.11

### ISSUE THREAD

**Issue by shadius** [outworkers/phantom#502]
Hi,

I'd like to use scala-sbt plubin to test our software together with running cassandra. Unfortunately we are using scala 2.11 and it looks like phantom-sbt_2.11 is not being released, onle version _2.10?

Many thanks

**Comment by alexflav23** [comment]
Hi @shadius,

Yes, we are not yet running a version of SBT build against Scala 2.11, but this is already in the pipeline, so we will be adding it within the weeks to come.

Regards.

**Comment by alexflav23** [comment]
Hi @shadius,

This is blocked by the default that SBT doesn't have a 2.11 release out yet. IT doesn't really matter if you are using Scala 2.11.x as if you are using SBT the version of the plugin that you require will still be 2.10.x, SBT will do that automatically.

This is meant to be a plugin not a library dependency, which may be be the source of confusion. For more details on how to use phantom-sbt, have a look [here](http://outworkers.com/blog/post/phantom-tips-tip2-testing-with-phantom-sbt).

Regards.
