### ISSUE TITLE
Determining time-to-live for a column

### ISSUE THREAD

**Issue by shadius** [outworkers/phantom#505]
Hi, 

according to phantom spec it seems there is no way how to determine TTL for a column:

SELECT TTL (name) from excelsior.clicks
  WHERE url = 'http://apache.org' ALLOW FILTERING;

https://docs.datastax.com/en/cql/3.1/cql/cql_using/use_ttl_t.html

Could you please add it?

**Comment by alexflav23** [comment]
Hi @shadius,

Thank you for the missing feature report, we can definitely add this in, it looks like a reasonably simple change so it should be part of the next incremental release today/tomorrow.

Regards.

**Comment by shadius** [comment]
Hi @alexflav23 ,

thank you for such quick response, can't wait to start using it 👍

Regards

**Comment by alexflav23** [comment]
Hi @shadius,

This has been implemented, it's going to be made available in the next release today. There's a PR for it, but basically you can do `db.table.select.function(t => ttl(t.column)`. `t` is the table in this case.

Regards.

**Comment by alexflav23** [comment]
Hi @shadius,

`1.26.6` is on Maven Central with the above feature included.
