### ISSUE TITLE
allow to create keyspace with custom replication factor

### ISSUE THREAD

**Issue by shadius** [outworkers/phantom#506]
We would like to autocreate our keyspace during application startup with replication factor = 2.

In Phantom, there is DefaultSessionProvider with hardcoded replication factor = 1:

session.execute(s"CREATE KEYSPACE IF NOT EXISTS $keySpace WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};")

Currently, there is no way how to pass our own replication factor into that object. Please provide a mechanism how to do that during keyscape creation, or how to provide our own implementation of SessionProvider

Thanks

**Comment by alexflav23** [comment]
Hi @shadius,

This is a known issue and we are in the process of porting the entire keyspace builder from phantom-pro(the paid for version) to the open source version, it winded up implemented there but as it's so important it doesn't make sense for it not to be OSS.

This work is fortunately scheduled for completion this week, so hopefully by Friday everything will be in great standing. You can define all the possible CQL features of keyspaces using a new immutable typesafe builder, just like for everything else, and the session provider and connector will be able to use your input for generating the keyspace.

Regards.

**Comment by markglh** [comment]
@alexflav23 will this allow us to avoid executing the `create keyspace` altogether? 

As per: https://github.com/outworkers/phantom/issues/511

**Comment by alexflav23** [comment]
Hi @shadius @markglh ,

As of phantom 1.28.0, you can skip the `autoinit` stage completely using the following syntax:

```scala
ContactPoint.local.keySpace("phantom", autoinit = false)
```

As of phantom 1.28.1, which is going live today, you can also optionally specify a keyspace creation query.

You can furthermore specify(for now), a function from `(Session, KeySpace) => String` to build your CQL query that creates the keyspace. We are in the process of adding a proper typesafe query builder for that part, it's just a question of porting over from a different codebase, but the string will do in the mean time.

Here's how to use it:

```scala
ContactPoint.local.keySpace("phantom", autoinit = true, (session, keyspace) => {
  s"CREATE KEYSPACE ${keyspace.name} WITH REPLICATION ..."
})
```

**Comment by markglh** [comment]
great, thanks @alexflav23 👍

**Comment by shadius** [comment]
thanks @alexflav23 !

I was just looking at 1.28.1 release on bintray, that feature where you can specify a keyspace creation query is not quite there yet, is it coming with the next release then or it just need merging?

Thanks

**Comment by alexflav23** [comment]
Hi @shadius, it will be published automatically in the next few hours, it ended up in 1.28.2 by human error(mine).

**Comment by alexflav23** [comment]
Hi @shadius  1.28.3 now available on Bintray, you can now use the aforementioned features.

**Comment by shadius** [comment]
Just in case someone needs it:

the actual syntax is:
`ContactPoint.local.keySpace("phantom", autoinit = true, Some((session, keyspace) => {
  s"CREATE KEYSPACE ${keyspace.name} WITH REPLICATION ..."
}))`

**Comment by alexflav23** [comment]
Thanks @shadius, I've added another overload for that method, so you can work withtout the option, it will go live in the next patch release. Apologies about that oversight, hopefully you can work with it anyway.
