### ISSUE TITLE
How to increase connection timeout

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#510]
I continously get connection timeout error and its actually coming through java driver. How should I increase the timeout value from phantom ?

**Comment by haggy** [comment]
@lahirug What was the resolution to this. I also need to increase the timeouts but I have no idea where to do that within phantom.

**Comment by alexflav23** [comment]
@haggy You can pass in whatever settings you like the connector.

```scala
  import com.outworkers.phantom.connectors.ContactPoint

  val default: CassandraConnection = ContactPoint.local
    .withClusterBuilder(_.withSocketOptions(
      new SocketOptions()
        .setConnectTimeoutMillis(20000)
        .setReadTimeoutMillis(20000)
      )
    ).noHeartbeat().keySpace("test")
```

**Comment by haggy** [comment]
Gotcha tyvm!
