### ISSUE TITLE
Feature request: support timestamp for deletes

### ISSUE THREAD

**Issue by charles-crain** [outworkers/phantom#515]
You currently can't do this (does not compile):

```scala
  delete()
    .where(_.foo eqs 1)
    .timestamp(DateTime.now())
    .future()
```

...even though CQL supports that.

Note: I am currently trying my hand at implementing this myself in a PR.

**Comment by alexflav23** [comment]
Hi @charles-crain,

There was work done to integrate all this in a streamlined `USING` clause API on a query, it's not yet finalised. We do of course welcome contributions, but in an attempt to centralise all these using clause defects we will release an updated version of phantom to address this.

Regards.

**Comment by charles-crain** [comment]
Again thanks for the quick response!
In that case I won't bother with the PR.  Any suggestions for a workaround in the meantime?  Right now all I can think of is to escape down to the raw Java API (using the session directly).

**Comment by alexflav23** [comment]
Hi @charles-crain apologies it took a little longer to ship this, it's a very busy time for us unfortunately. This is going live in 1.28.4 latter today, it's just pending a CI Test run which will automatically publish the new version.

**Comment by alexflav23** [comment]
1.28.4 now available on Bintray, you can specify a timestamp on a delete.
