### ISSUE TITLE
How to do prepared insert with ttl

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#517]
I see phantom support ttl with insertQuery but is it possible to use ttl with preparedInsetquery ?

**Comment by alexflav23** [comment]
Hi @lahirug,

I don't think Cassandra supports preparing the TTL, you will have to add that separately. We've tried adding this before but Cassandra says the query is invalid, maybe someone will correct me if I am mistaking.

Regards.

**Comment by lahirug** [comment]
@alexflav23 Thanks for the response. How do we add it separately ? I saw this issue https://github.com/outworkers/phantom/issues/396 stopped in a dead end too. 

We really have to batchable prepared statements in our usecase with ttl.

**Comment by alexflav23** [comment]
HI @lahirug,

This doesn't work on the Cassandra side, it's not a driver side limitation. Run it yourself in the CQL shell, and confirm results. Maybe they have since added the functionality, but when we tried adding it it failed.

Regards.

**Comment by lahirug** [comment]
do you support setting ttl for column family during autocreate ?

**Comment by alexflav23** [comment]
Hi @lahirug,

Not currently, if this is something Cassandra supports then it may be interesting to add it. Could you please create a separate issue about this and highlight the exact features/behaviour you'd expect to see? Either DSL or CQL examples would be more than welcome, if you could help there we'll add that to the pipeline and get it fixed asap.

Regards.

**Comment by lahirug** [comment]
I created this https://github.com/outworkers/phantom/issues/517 but didn't get any response. Just want to add a reference in the code so that we can change our code when this feature is available. Are you planning to support table properties to be read during autocreate ?

**Comment by alexflav23** [comment]
This is already fixed in 1.28.1, which should be available sometime today. You simply override the autocreate method inside the table to specify options.

**Comment by alexflav23** [comment]
Hi @lahirug,

If you are referring to supporting prepared TTL, this will become available in `1.28.1`, and you can simply use it with the following syntax:

```scala

val query = database.recipes.insert
      .p_value(_.uid, ?)
      .p_value(_.url, ?)
      .p_value(_.servings, ?)
      .p_value(_.ingredients, ?)
      .p_value(_.description, ?)
      .p_value(_.lastcheckedat, ?)
      .p_value(_.props, ?)
      .ttl(?)
      .prepare()
```

Hope this helps.

**Comment by lahirug** [comment]
Thats good news and Thanks a lot.

**Comment by alexflav23** [comment]
Hi @lahirug 1.28.3 now available on Bintray, you can simply use `ttl(?)` as described above.
