### ISSUE TITLE
Using 1.26.1 in play framework, gives me the compile error "wrong number of type arguments for com.websudos.phantom.dsl.ListColumn, should be 3"

### ISSUE THREAD

**Issue by git4sun** [outworkers/phantom#518]
Should the collection type only take one type argument after 1.25? Why am I still getting this error?

**Comment by alexflav23** [comment]
Hi @git4sun,

Try 1.27.0, I don't think you should be getting this error, but check the definition of `ListColumn` and the changelog on the wiki to see where we introduced the change.

Regards.

**Comment by git4sun** [comment]
It turns out to be another included library using an earlier version of phantom.

**Comment by alexflav23** [comment]
Hi @git4sun,

Out of curiosity, what library is that?

Regards.

**Comment by git4sun** [comment]
@alexflav23  It's not a public library.
