### ISSUE TITLE
Configure logging for sbt-phantom

### ISSUE THREAD

**Issue by aeons** [outworkers/phantom#519]
The embedded cassandra instance started by sbt-phantom spews a lot of logging.

I haven't been able to figure out how to configure or disable this.

Any suggestions?

**Comment by alexflav23** [comment]
Hi @aeons,

A way to  fix things would be to turn the logging off. Add `logback-test.xml` inside `src/test/resources` and  simply turn off the right loggers to suit your preference, that should be it. Look [here](https://github.com/outworkers/phantom/blob/develop/phantom-dsl/src/test/resources/logback-test.xml) for an example of such a configuration, we use this for phantom tests. 

Regards.

**Comment by aeons** [comment]
I have logging configured with log4j2 and slf4 and it seems to work for phantom and datastax stuff, but it doesn't affect the output of the embedded cassandra.

**Comment by kolemannix** [comment]
I have this same issue as well; `logback-test.xml` does not seem to affect the embedded cassandra.

**Comment by jerrypaytm** [comment]
Yup, it does not work.

**Comment by thereisnospoon** [comment]
I have the same problem. `logback-test.xml` configuration doesn't seem to affect the logging output. Was someone able to find the solution?
