### ISSUE TITLE
Support default_time_to_live in table definition

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#521]
In cql we can give table properties like default_time_to_live, caching etc. I see these parameters are defined in phantom code, but really don't understand how to specify these in table definitions.

Do you support this ? If you don't can you please implement this feature, so that table properties can be defined in table classes.

CQL looks like this, 

```
CREATE TABLE DogTypes (
  block_id uuid,
  species text,
  alias text,
  population varint,
  PRIMARY KEY (block_id)
) WITH caching = 'keys_only';
```

**Comment by alexflav23** [comment]
Hi @lahirug,

Yes we do have full support for all table creation properties. Here's an example:

```
BasicTable.create
          .`with`(compaction eqs LeveledCompactionStrategy.sstable_size_in_mb(50))
          .and(compression eqs LZ4Compressor.crc_check_chance(0.5))
          .and(default_time_to_live eqs 5.seconds)
```

Regards.

**Comment by lahirug** [comment]
@alexflav23 sorry for the misleading explanation. We do not create we just do autocreate. So our requirement is setting table proporties and phantom should pick them during autocreate and make sure properties are set in tables.

Do you have this feature or am I missing something ?

**Comment by lahirug** [comment]
@alexflav23 I removed the autocreate and manually used the create, If you can support autocreate  with table properties that would be much nicer than below code.

`Future.sequence(tables.toSeq.map(_.create.ifNotExists().`with`(default_time_to_live eqs Days.days(30).toStandardSeconds).future()))`

**Comment by lahirug** [comment]
@alexflav23 

In case you missed this request. 
Appreciate if you can provide an update. Did I confuse you with above description ?
Thanks
Lahiru
