### ISSUE TITLE
Issue with updates and time stamps

### ISSUE THREAD

**Issue by charles-crain** [outworkers/phantom#534]
I am on version 1.28.5.  This is very strange because I am almost sure this worked in earlier versions of Phantom, but I am getting errors trying to use time stamps with updates.  Here is what my code looks like:
`update.where(_.baz eqs "blat").modify(_.foo setTo "bar").timestamp(123456).future()`

This is what the generated CQL looks like:
`UPDATE awesome.table USING UPDATE awesome.table TIMESTAMP 123456 SET foo = 'bar' WHERE baz = 'blat'`

(note that for whatever reason the UPDATE clause is repeated twice)

**Comment by alexflav23** [comment]
Hi @charles-crain,

Looks like this slipped through somehow, will fix it asap for 1.28.6, coming up tonight.

Regards.

**Comment by alexflav23** [comment]
Hi @charles-crain just to confirm, `1.28.6` is now on Bintray with the fix, thank you for reporting this.
