### ISSUE TITLE
Delete with timestamp appears to still not work

### ISSUE THREAD

**Issue by charles-crain** [outworkers/phantom#540]
I reported delete-with-timestamp as not supported at all a while back, and that issues was closed as implemented in 1.28.4:
https://github.com/outworkers/phantom/issues/515#issuecomment-229370403

I am now on 1.28.9, and it is supported (it compiles) but generates incorrect CQL and fails on the Cassandra side.  Here is an example of some generated CQL:
`DELETE FROM awesome.table WHERE id = 'foo' USING TIMESTAMP 1471270621668000`

The "USING TIMESTAMP X" clause should come before the WHERE.

I am working on a PR that has some additional testing for the timestamp feature since I use it a lot.  Do you prefer tests that go all the way to actual Cassandra, or a test that tries to inspect the generated CQL for well-formed-ness (the former being a fuller test but the latter being more direct)?

**Comment by alexflav23** [comment]
Hi @charles-crain,

This is a different issue by the sounds of it, and one with the `delete` query. I think we did have tests for that and they seem to work, perhaps the order got reversed for the positioning of clauses in more recent versions.

Nonetheless, we can fix this in the next release and add more tests.

**Comment by alexflav23** [comment]
Hi @charles-crain,

Fixed pending CI, should go live in `1.28.12` whenever CI is done.

Regards.
