### ISSUE TITLE
Optional value updates using setIfDefined produces Cassandra Exception

### ISSUE THREAD

**Issue by daveinglis** [outworkers/phantom#549]
When using optional values in an update using `setIfDefined` will cause an exception about a malformed CQL statement.

So with this example update;

`update.where(_.id eqs m.id)`
`      .modify(_.api_key setIfDefined m.api_key)`
`      .and(_.home_url setIfDefined m.home_url)`
`      .and(_.description setIfDefined m.description)`
`      .and(_.name setIfDefined m.name)`
`      .future.map(_ => ())`

and when t `name` is the only field set, it produces the following failure;

> 00:43:44.570 [vert.x-eventloop-thread-1] DEBUG com.websudos.phantom - Executing query: UPDATE mustang_test.apps name = 'name 12' WHERE id = 4704dab0-7ecb-11e6-8556-d3990f2126dd;
00:43:44.574 [pool-9-thread-76] ERROR com.websudos.phantom - line 1:25 missing K_SET at 'name'
00:43:44.575 [vert.x-eventloop-thread-1] DEBUG com.websudos.phantom - Executing query: UPDATE mustang_test.apps name = 'name 12' WHERE id = 470b6a61-7ecb-11e6-8556-d3990f2126dd;
{ name: 'name 12', id: '47141cfa-7ecb-11e6-8556-d3990f2126dd' }
Operation returned an unknown exception
com.datastax.driver.core.exceptions.SyntaxError: line 1:25 missing K_SET at 'name'
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:132)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:173)

But if `api_key` is set the statement is correct, so it seems that if the value in the `modify()` is not defined phantom does not put the `SET` keyword in the `UPDATE` statement.

**Comment by alexflav23** [comment]
HI @daveinglis,

I've been having this exact problem in my head for the past few hours every since you asked about it yesterday, and I've already flagged an internal ticket about this. It will be fixed in the next release, if all goes well it should go in today, if not it will go in tomorrow.

Many thanks for reporting this!

Regards.

**Comment by alexandermikuta** [comment]
Are there any news about the current state of this fix?

**Comment by alexflav23** [comment]
Hi @alexandermikuta,

This will be available in today's release, which should just be a few more hours.

Regards.

**Comment by daveinglis** [comment]
Will this also have a fix to let setIfDefined be used on non-optional columns?

**Comment by alexflav23** [comment]
Yes, we're working to wrap this up as we speak.

**Comment by alexflav23** [comment]
@daveinglis Fixed in 1.29.4.
