### ISSUE TITLE
IF EXISTS support in Delete queries

### ISSUE THREAD

**Issue by kbalyasnikov** [outworkers/phantom#551]
Cassandra [supports](https://docs.datastax.com/en/cql/latest/cql/cql_reference/delete_r.html) IF EXISTS in Delete queries. In `DeleteQuery` where is only `onlyIf` method, but there is no `ifExists`.

**Comment by alexflav23** [comment]
Hi @kbalyasnikov,

Many thanks for reporting this, it will be added in the next release going out tomorrow evening.

Regards.

**Comment by kbalyasnikov** [comment]
Thanks, great news!

**Comment by alexflav23** [comment]
Hi @kbalyasnikov,

This is now fixed, it will be available in the next release.

Regards.
