### ISSUE TITLE
How to configure the embedded database?

### ISSUE THREAD

**Issue by jerrypaytm** [outworkers/phantom#555]
Hi @alexflav23, I want to configure the cassandra with `commitlog_segment_size_in_mb`. How can I pass it to the embedded database? Thanks!

**Comment by alexflav23** [comment]
Hi @jerrypaytm,

There's a way to specify a path to a custom yaml file for Cassandra. For example:

```
phantomCassandraConfig in Test := Some(baseDirectory.value / "tools" / "cassandra.yaml"),
````


Regards.
