### ISSUE TITLE
Use token aware policy

### ISSUE THREAD

**Issue by meddulla** [outworkers/phantom#557]
Hi,

I would like to change to a token aware policy to improve performance but using the code below

```
object Defaults extends DbConfiguration { 
[..]
val connector: KeySpaceDef = new KeySpaceBuilder(_.addContactPoints(hosts: _*)
      .withPort(port)
      .withLoadBalancingPolicy(new TokenAwarePolicy(new DCAwareRoundRobinPolicy())))
      .withClusterBuilder(_.withSocketOptions(
        new SocketOptions()
          .setReadTimeoutMillis(15000) // Default is 12000
          .setConnectTimeoutMillis(7000) // Default is 5000
      ))
      .keySpace(keyspace)
[..]
}
```

I get this error

`constructor DCAwareRoundRobinPolicy in class DCAwareRoundRobinPolicy cannot be accessed in object Defaults`

Am currently a bit stumped on how I would change the policy to token aware. Can you help?

Thanks :)

**Comment by alexflav23** [comment]
Hi @meddulla,

The no param constructor of `DCAwareRoundRobinPolicy` is `private` so that's why you get the error message. Normally you would use it like this:

```scala

    .withLoadBalancingPolicy(
      new TokenAwarePolicy(
        new DCAwareRoundRobinPolicy.Builder()
          .withUsedHostsPerRemoteDc(5)
          .withLocalDc("us-east").build()
        )
    )
```

Hope this helps!

**Comment by meddulla** [comment]
Thanks. That helped a lot :)
