### ISSUE TITLE
Pagination with pagingstate and setFetchSize work?

### ISSUE THREAD

**Issue by sourgreis** [outworkers/phantom#559]
I'm new with cassandra and phantom. When i use _select.limit(1000).fetchRecord(_.setFetchSize(500))_ i receive 1000 rows and pagingstate always null (with limit over 90k return over 90k rows igores fetchsize)

Row 252 in ExecutableQuery.scala resultSet => directMapper(resultSet**.all**) means all rows consumed without paging... [http://docs.datastax.com/en/drivers/java/3.0/com/datastax/driver/core/ResultSet.html#all--](http://docs.datastax.com/en/drivers/java/3.0/com/datastax/driver/core/ResultSet.html#all--)
Maybe i doing something wrong? 
How made proper pagination with fetchRecord(_.setFetchSize(pageSize).setPagingState(state))?

**Comment by alexflav23** [comment]
Hi @sourgreis,

You forgot `limit`, `setFetchSize` is more internal to the driver and it may help you with controlling the amount of network traffic if you have really large rows or something, but what you need here is simply `limit`.

The `setFetchSize` option does nothing more than to control the number of results fetched in a single call to Cassandra, but the driver internalises this, so if you request 1000 results and Cassandra has 1000 results to give, that means it will still fetch 1000, but in 2 batches of 500. Hope this makes sense.

`select.limit(500).fetchRecord()` should come back with a `PagingState`.

**Comment by sourgreis** [comment]
I have 100k+ record in test db, selecting with limit
select.limit(500).fetchRecord() map (res => println(res.pagingState))
prints **null**
p.s. phantomVersion "1.28.14" and scala "2.11" and cassandea 3.7 single node in docker

**Comment by alexflav23** [comment]
Hi @sourgreis,

I see now, my mistake above, I was used to the `Iteratee` API where this works because it does something very similar to `fetchSize` behind the scenes, so you do need `fetchSize`. I'm going to add a few details for large scenarios here, it may be that the fetch behaviour has to be replicated inside the mapping of results.

Many thanks for reporting this, it may take a few hours to fix it.

Regards.

**Comment by isacandrei** [comment]
Hi @alexflav23,

I am also struggling with pagination in Phantom. It's the same issue @sourgreis had, when I'm trying to use the `pagingState` it returns `null`. 
Here is my query: `select.where(_.boardName eqs board).limit(limit).fetchRecord().map(
            res => (res, res.pagingState)
        )`
I am using `scalaVersion = "2.11.8";  PhantomVersion = "1.29.3"; cassandra = "3.9"`.
Did you manage to find a solution for this issue? 
Thank you.

**Comment by dgomezs** [comment]
I also tried to implement the pagingState today with the same luck. It returns null. Has anyone made it work? 
Thank you

**Comment by git4sun** [comment]
any update on this issue?

**Comment by alexflav23** [comment]
HI @git4sun @dgomezs @isacandrei @sourgreis This has been fixed as of today, the fix is going live on Maven Central in 2 - 3 hours.
