### ISSUE TITLE
updates with increments producing bad CQL statements

### ISSUE THREAD

**Issue by daveinglis** [outworkers/phantom#562]
Hi @alexflav23 

Thanks for the fix for #549 , I have many more tests passing in our migration to the latest phantom release.  However I think I found another case where an UPDATE is not constructed properly (or maybe it's how I'm building the statement)  anyway with the following code snippet;

```
if (m.isEmpty) return Future.successful(())
var mod = update.where(_.bucket eqs m.bucket).and(_.hours_since_epoch eqs m.hours_since_epoch).and(_.org_id eqs m.org_id).and(_.app_id eqs m.app_id).and(_.device_id eqs m.device_id).and(_.user_id eqs m.user_id).and(_.item_type eqs m.item_type).and(_.item eqs m.item)
for (elapsed <- m.elapsed) mod = mod.and(_.elapsed increment elapsed)
for (fail <- m.fail) mod = mod.and(_.fail increment fail)
for (num <- m.num) mod = mod.and(_.num increment num)
mod.future.map(_ => ())
```

it produces the following statement with another exception Cassandra exception;

> 21:13:08.821 [vert.x-eventloop-thread-1] DEBUG com.websudos.phantom - Executing query: UPDATE mustang_test.statistics WHERE bucket = 1022 AND hours_since_epoch = 410061 AND org_id = 76daa11e-9433-4e2e-b76a-c3b78a29b39d AND app_id = d73977c2-aa2f-488c-aba7-52e69c5c4b05 AND device_id = 27981715-5274-4d55-804a-9d5bc3257b9f AND user_id = ffb76824-11df-4dd2-9289-aa22f7ff4679 AND item_type = 'pujhuco' AND item = 'ologanab' AND elapsed = elapsed + 3155702138798080 AND fail = fail + 6914330121469952 AND num = num + -6214899734675456;
> 21:13:08.823 [pool-9-thread-90] ERROR com.websudos.phantom - line 1:31 mismatched input 'WHERE' expecting K_SET
> Operation returned an unknown exception
> com.datastax.driver.core.exceptions.SyntaxError: line 1:31 mismatched input 'WHERE' expecting K_SET
>     at com.datastax.driver.core.Responses$Error.asException(Responses.java:132)
>     at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
>     at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:173)
> ...

Is this a problem with phantom or how I'm building the query?

Thanks
Dave

**Comment by alexflav23** [comment]
Hi @daveinglis ,

Thank you for reporting this, let me have a quick look, sounds like in a particular edge case phantom is not appending the `SET` keyword correctly.

Regards,
Flavian

**Comment by alexflav23** [comment]
Hi @daveinglis,

Just wanted to follow up on this to close this ticket, phantom now natively supports handling missing parts of updates by skipping `None` fields using `setIfDefined` and we are adding an `incrementIfDefined` to complement that functionality which would entirely solve your problem.

```scala
if (m.isEmpty) return Future.successful(())
var mod = update.where(_.bucket eqs m.bucket)
  .and(_.hours_since_epoch eqs m.hours_since_epoch)
  .and(_.org_id eqs m.org_id)
  .and(_.app_id eqs m.app_id)
  .and(_.device_id eqs m.device_id)
  .and(_.user_id eqs m.user_id)
  .and(_.item_type eqs m.item_type)
  .and(_.item eqs m.item)
  .modify(_.elapsed incrementIfDefined m.elapsed)
  .and(_.elapsed incrementIfDefined m.fail)
  .and(_.elapsed incrementIfDefined m.num)
```

The reason why this failed previously in your case is because the first update in the sequence has to supply a `modify` query before an `and`, otherwise phantom cannot distinguish between `and` as part of a `where` clause or `and` as part of an update clause.

Regards,
Flavian
