### ISSUE TITLE
JSON and collection column definition still need three type parameters

### ISSUE THREAD

**Issue by joosterman** [outworkers/phantom#565]
The [documentation](https://github.com/outworkers/phantom/wiki/Collection-columns) states:

> It's worth noting that before phantom 1.25.x, any collection column in phantom would need 3 arguments when being defined, which looked something like the below, where you needed to provide both the table type and the record type of the host table, as well as the type of the actual collection:
> In more recent versions of phantom, collection types consumed at DSL levels have been moved, so now they are type alises nested within Cassandra table. This means we can now the type of the host table and the record it holds without it needing to be provided explicitly.
> 

I am now running 1.29.4, but I still need to provide three type arguments for collection and JSON columns. Which version should have the described functionality?

**Comment by alexflav23** [comment]
Hi @joosterman,

They really shouldn't there are type aliases for them as well.

```

  object jsonSet extends JsonSetColumn[JsonTest](this) {
    override def fromJson(obj: String): JsonTest = {
      JsonParser.parse(obj).extract[JsonTest]
    }

    override def toJson(obj: JsonTest): String = {
      compactRender(Extraction.decompose(obj))
    }
  }
```

Regards.

**Comment by joosterman** [comment]
Quick reply, thank you!

There does indeed seem to be these type aliases in "default scope", but I still have two issues

1) My IDEA complains when I try to use the aliases. I get the error "Not applicable". sbt compile however works fine. Do you know what could cause this, or how I can resolve it?

<img width="839" alt="screen shot 2016-10-25 at 20 01 49" src="https://cloud.githubusercontent.com/assets/1252037/19698008/ec4ac038-9aed-11e6-9fc6-a6f9da019ec4.png">

2) The types aliases are not available in traits. My setup is the following: I have multiple tables that share a number of fields. Because I do not want to repeat the definition I have put the column definitions in a (generic) trait that I mixin in all relevant tables. Here however, it seems I cannot access the type aliases. My code:

```
trait ContentItemsModel[O <: CassandraTable[O, R], R] {
  var cassandra: O = _
  object site extends StringColumn(cassandra) with PartitionKey[String]
  object contentType extends StringColumn(cassandra) with PartitionKey[String]
  object contentUID extends StringColumn(cassandra) with ClusteringOrder[String] with Descending
  object datePublished extends DateTimeColumn(cassandra) with Index[DateTime]
  object tags extends SetColumn[O, R, String](cassandra)
}

class Articles extends CassandraTable[ConcreteArticles, Article] with ContentItemsModel[ConcreteArticles, Article] 

abstract class ConcreteArticles extends Articles with RootConnector{}

case class Article(site: String, id: String, datePublished: DateTime) extends ContentItem
```
So within the trait ContentItemsModel (when I remove the wrong import as you pointed out) it seems I cannot use the type aliases. The aliases are not found. Is there a way to make this work?

**Comment by joosterman** [comment]
Ok, issue 2) I managed to resolve by having the trait actually extend the CassandraTable. This allows me to use the type aliases.

Issue 1) is still a complete mystery to me.

**Comment by alexflav23** [comment]
Hi @joosterman,

I know what you mean that's indeed a problem, but we are also not sure what the best way to fix that.

Regards,
Flavian
