### ISSUE TITLE
Scala 2.12

### ISSUE THREAD

**Issue by fkowal** [outworkers/phantom#570]
Kind request for scala 2.12 artifact

**Comment by alexflav23** [comment]
Hi @fkowal,

Coming in phantom 2.0.0, it's baking in an internal pull request, currently only blocked by some macro compat fun that's very nearly ready for 2.12 as well.

The other dependencies, such as phantom-finagle and other modules in phantom that depend on external libs may need to wait out slightly longer for a 2.12 release depending on how soon those individual authors offer a 2.12 alternative.

Regards,

**Comment by fkowal** [comment]
Keep up the good work

**Comment by fkowal** [comment]
how's it going ?

**Comment by alexflav23** [comment]
Hi @fkowal,

Diesel is migrated, util is 60% of the way there, so I'd say 2 more weeks and this will be out.

Regards.

**Comment by alexflav23** [comment]
@fkowal Phantom 2.0.12 on `Resolver.bintrayRepo("outworkers", "oss-releases")` now includes Scala 2.12 support for the base models. You will find a compatibility table [here](https://github.com/outworkers/phantom/tree/feature/2.0.0#available-modules), it will tell you which modules have Scala 2.12 support and which don't yet.

**Comment by fkowal** [comment]
good job @alexflav23 thank you
