### ISSUE TITLE
Proper support for compaction strategy TimeWindowCompactionStrategy

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#571]
I see latest phantom doesn't have a proper support for TimeWindowCompactionStrategy and configure the attributes like compaction_window_size, compaction_window_unit, timestamp_resolution.

**Comment by alexflav23** [comment]
@lahirug Thank you for your feedback, we will implement this in the 2.0.0 release!

**Comment by lahirug** [comment]
@alexflav23 do you guys have a timeline for the 2.0.0 release ?

**Comment by alexflav23** [comment]
@lahirug Just another 2 - 3 days. It's already on Bintray, 2.0.4, but all the package names have changed to `com.outworkers` and the resolver is now `Resolver.bintrayRepo("outworkers", "oss-releases")`, so you can already try it out.

**Comment by alexflav23** [comment]
HI @lahirug,

Here's the [2.0.0 migration guide](https://github.com/outworkers/phantom/tree/feature/2.0.0#200-migration-guide), should give you a glimpse into a few of the core changes. There's a lot more to come, including a full tutorial, a changelog, some presentations, but those will take some time to show, I'm talking another 2 - 3 weeks. 

For now the 2.0.0 release is the focus, to bring in Scala 2.12 and other goodies.

Regards,
Flavian

**Comment by alexflav23** [comment]
Hi @lahirug, this work is now complete, just FYI, so you can find it in 2.0.7.
