### ISSUE TITLE
Websudos bintray repo requires credentials now?

### ISSUE THREAD

**Issue by charles-crain** [outworkers/phantom#573]
When I try to access the bintray repo, I get a Forbidden response, for instance:
https://dl.bintray.com/websudos/oss-releases/com/websudos/diesel-engine_2.11/0.3.0/diesel-engine_2.11-0.3.0.pom

This is causing all builds that have transitive dependencies on diesel-engine (such as Phantom) to fail.  As far as I can tell, this was working a few days ago.  It's hard to tell because many of our machines have cached dependencies.

**Comment by alexflav23** [comment]
Hi @charles-crain,

Apologies about this, Bintray have helped us migrate our repos to a new organisation, but we have explicitly paid them to keep the old ones intact until the migration process is complete. I can only guess that's not really happening, there should be absolutely no reason why our oss repos require credentials.

Thank you for the report, diesel engine will go to Maven Central asap to bullet proof this and we'll deal with the Bintray backfire shortly after.

Regards,
Flavian

**Comment by charles-crain** [comment]
Thanks for the quick response!  We're not dead yet since we have lots of machines with a cached diesel-engine, but setting new developer machines up is causing issues so keep us posted on the Maven Central move!

**Comment by alexflav23** [comment]
Hi @charles-crain,

This should be all fixed for now with the normal resolvers, our Bintray repo is back to life courtesy of bintray support. We are days away from moving it all to Maven Central and phantom 2.0, so this should never be a problem again after that point.

Apologies for any inconvenience caused in the interim.

Regards,
Flavian
