### ISSUE TITLE
Thring to use a prepared statement throws an exception 

### ISSUE THREAD

**Issue by 123avi** [outworkers/phantom#574]
Hi I am using phantom version: 

> 1.29.5

I am trying to use a prepared statement to compare performance 
 
```
import org.joda.time.DateTime
case class Metric (mkey:String, ts: DateTime, value:Double )

lazy val storeBound = session.prepare(
      s"INSERT INTO akkacassandra.metrics (mkey, ts, value) VALUES ( ?, ?, ?);")
 session.executeAsync(storeBound.bind(m.mkey, m.ts, new java.lang
 .Double(m.value)))

```
yields this exception

> com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [timestamp <-> org.joda.time.DateTime]

Please advise

**Comment by alexflav23** [comment]
Hi @123avi,

I'm not sure if you are using the Java Driver directly or why you are doing that at all, the API you are using doesn't seem to be related to phantom. I'm not sure at this point in time if your query even relates to phantom on the basis that you don't seem to be using any of phantom.

```scala

val query = insert.p_value(_.mkey, ?).p_value(_.ts, ?).p_value(_.value, ?).prepare()

case class Metric(
  mkey: String,
  ts: DateTime,
  value: Double
)

val instance = Metric("test", DateTime.now(), 5D)

val result = query.bind(instance).future()
```

Regards,
Flavian

**Comment by 123avi** [comment]
Hi @alexflav23 
I am using Phantom, I wanted to do benchmark between prepared statement and using Phantom dsl. this is the complete code sample
```

import com.datastax.driver.core.Row
import com.entities.Metric
import com.websudos.phantom.dsl._
import org.joda.time.DateTime
import scala.concurrent.Future

class MetricModel extends CassandraTable[MetricModel, Metric] {
  override def tableName = "metrics"

  object mkey extends StringColumn(this) with PartitionKey[String]
  object ts extends DateTimeColumn(this) with ClusteringOrder[DateTime]
  object value extends DoubleColumn(this)

  override def fromRow(r: Row): Metric = Metric(mkey(r), ts(r), value(r))
}

abstract class ConcreteMetricModel extends MetricModel with RootConnector {

  lazy val storeBound = session.prepare(
    s"INSERT INTO akkacassandra.metrics (mkey, ts, value) VALUES ( ?, ?, ?);"
  )

  def store(m: Metric): Future[ResultSet] = insert
    .value(_.mkey, m.mkey)
    .value(_.ts, m.ts)
    .value(_.value, m.value)
    .consistencyLevel_=(ConsistencyLevel.ONE)
    .future()

 def storex(m:Metric): Unit = session.executeAsync(storeBound.bind(m.mkey, m.ts, new java.lang
 .Double(m.value)))
}
 
```

**Comment by alexflav23** [comment]
Hi @123avi,

Phantom normalises those Scala types in a different way that the Java driver does. What you are after is the [CodecRegistry](http://docs.datastax.com/en/drivers/java/2.2/com/datastax/driver/core/CodecRegistry.html), and you need to manually implement the codec for the required conversion and then add it to the `CodecRegistry` and that should work.

Regards,
Flavian

**Comment by alexflav23** [comment]
Hi @123avi,

Have you managed to solve this independently?

The workaround is similar to this basically:

```scala
ContactPoints(hosts, port)
      .withClusterBuilder(_
        .withCodecRegistry(CodecRegistry.DEFAULT_INSTANCE.register(new BigDecimalCodec))
      )

class BigDecimalCodec extends MappingCodec(TypeCodec.decimal(), classOf[scala.math.BigDecimal]) {

  override def serialize(value: scala.math.BigDecimal): java.math.BigDecimal = value.bigDecimal

  override def deserialize(value: java.math.BigDecimal): scala.math.BigDecimal = BigDecimal(value)
}
```

**Comment by 123avi** [comment]
Hi @alexflav23 ,
Thank you for brining this up . I didn't had the time to straggle with it very much so I just put it aside for now.  I understood that I need to implement the CodecRegistry . however IMHO if phantom supports prepared statement why should one implement those types ? these are common used types (e.g String, DateTime, Double) .  shouldn't it be supported ?

**Comment by alexflav23** [comment]
Hi @123avi,

You were the one trying to use the Java Driver API, phantom normalises these types automatically, the Java Driver doesn't. Hope that makes sense. Sounds like I can close this ticket, come back if needed, this is already supported if you use the default phantom APIs.

Regards.

**Comment by 123avi** [comment]
@alexflav23  I am probably misunderstanding you, what do you mean by using the Java Driver API ? I am using Phantom libraries ? how can I use prepared statement properly ? is there an example that you can share please ?

**Comment by alexflav23** [comment]
@123avi At the top of this thread I gave you an example of how to replace your manual string version of a prepared statement with a phantom one, have a look there and simply use that.

**Comment by 123avi** [comment]
@alexflav23 thanks, I saw that and this is how I currently use Phantom (and it works great, thanks!) . but this is not the prepared I was referring too , but I was just wondering if there is a support for such statement 
```
lazy val storeBound = session.prepare(
    s"INSERT INTO akkacassandra.metrics (mkey, ts, value) VALUES ( ?, ?, ?);"
  )
```
I understand that there is partially support and I need to implement 

> CodecRegistry
which is OK . thanks and sorry for the misunderstanding

**Comment by alexflav23** [comment]
@123avi I'll copy paste again.

```
val query = database.table.insert
  .p_value(_.mkey, ?)
  .p_value(_.ts, ?)
  .p_value(_.value, ?)
  .prepare()

case class Metric(
  mkey: String,
  ts: DateTime,
  value: Double
)

val instance = Metric("test", DateTime.now(), 5D)

val result = query.bind(instance).future()
```
