### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by mazorigal** [outworkers/phantom#575]
Hi,

I am using the DB object according to the following example (object that extends class)
https://github.com/outworkers/phantom/blob/develop/phantom-example/src/main/scala/com/websudos/phantom/example/advanced/RecipesDatabase.scala

But when the DB is down or providing wrong ip/port, during the app start, I am getting the 
java ExceptionInInitializerError and unable to catch it since its fatal error, then the app is terminating.

However if the DB is up and I start the App, and lets say after 10 minutes, the DB is down, then I am able to catch com.datastax.driver.core.exceptions.NoHostAvailableException and prevent from the app to terminate.

Is there anyway to catch the error in the first described case ? ( I would terminate the app in case of unavailable DB anyway, but prefer to do it in more nicer, user friendly way)

Thanks,

**Comment by alexflav23** [comment]
Hi @mazorigal,

Just confirming that in more recent versions of phantom you can propagate a custom error handler to address any issues that can happen when the session is created or any errors occur.

As of 2.0.0 this should be available as standard and you can manipulate the error handling process using a simple function handler that gets passed through with the help of CassandraConnector.

The documentation is currently being updated to reflect all of this and some more advanced scenarios should be available shortly.

Regards,
Flavian

**Comment by alexflav23** [comment]
Hi @mazorigal 2.0.0 is on Maven Central, so you can pass a handler through and control this behaviour.
