### ISSUE TITLE
How to create a Akka streams from ResultSet

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#587]
In older version of phantom we used to have a method to convert ExecutableQuery result to akka streams using fetchEnumerator but its been removed and I am curious how to do it now.

This is what we had,

`def source()(implicit session: Session, keyspace: KeySpace): Source[R, _] = {
      Source.fromPublisher(Streams.enumeratorToPublisher(
        query.fetchEnumerator()
      ))
    }`

**Comment by mmatloka** [comment]
@lahirug hey, probably you can still use Source.fromIterator with

```
query.iterator().flatMap { iterator =>
   val sth = Source.fromIterator(() => iterator)
   ...
}
````
I've used this way with previous phantom version and worked without any issues. This iterator is just a scala  iterator wrapped around result set iterator which is using auto-pagination.

**Comment by alexflav23** [comment]
Hi @mmatloka @lahirug,

The old functionality is not actually gone, it's simply moved modules. We separated any dependencies on play and Akka in the `reactivestreams` module so people don't have to get all the dependencies by simply using the `dsl`.

In short: 

```scala

// in build.sbt
libraryDependencies ++= Seq(
  // this is the latest but comes with breaking API changes so be careful
  "com.outworkers" %% "phantom-reactivestreams" % "2.0.6"
)

// in your file
import com.outworkers.phantom.reactivestreams._

def source()(
  implicit session: Session,
  keyspace: KeySpace
): Source[R, _] = {
  Source.fromPublisher(
    Streams.enumeratorToPublisher(query.fetchEnumerator())
  )
}

```

**Comment by lahirug** [comment]
Thanks guys.
