### ISSUE TITLE
Clear migration guide for phantom 2.0

### ISSUE THREAD

**Issue by lahirug** [outworkers/phantom#589]
Hi Alex,

I am having lot of trouble with the 2.0 migration because I am just looking at the code and doing the migration and it seems very time consuming. Are you planning on doing a migration guide because this [2.0 migration](https://github.com/outworkers/phantom/tree/feature/2.0.0#200-migration-guide) is not very clear and missing lot of information. 

Ex: moving reactivestreams as a separate library
      how the table definitions should changes compare to older version

Or this is pretty much what you guys are planning for now in regards to the migration guide ?

**Comment by alexflav23** [comment]
Hi @lahirug,

We are going to come up with a full migration tutorial that will be published everywhere. Obviously it's true there will be non trivial commitment to completely jump versions, but it's only done to encourage further adoption and remove complexity and verbosity from the DSL.

As we see it the official 2.0.0 is not yet out, so you can either leave it aside for a while, e.g 2 weeks, or you will need to come back with questions here should you need help, and I'll do my best to help.

Regards,
Flavian

**Comment by lahirug** [comment]
@alexflav23 Thanks a lot for the note, I'll wait for few more weeks and try with your migration guide.

**Comment by alexflav23** [comment]
Hi @lahirug Just FYI the migration guide is [HERE](https://github.com/outworkers/phantom/blob/develop/docs/migrate.md), you can safely start porting to Phantom 2.x.x series, the latest version is 2.1.1
