### ISSUE TITLE
Optional Short Column Names

### ISSUE THREAD

**Issue by peter-empen** [outworkers/phantom#595]
Hi and thanks for your awesome library.

I like the idea sending short column names to Casssandra while using long names in Scala. For this purpose I am currently able to write:
```scala
object phantomIssueCount extends IntColumn(this) { override def name: String = "phIC" }
```
but I'd prefer just writing
```scala
object phantomIssueCount extends IntColumn(this, "phIC")
```
Would you accept such a new feature? If so, would you prefer adding it yourself or getting a pull request?

**Comment by alexflav23** [comment]
Hi @peter-empen, thank you for the suggestion, we'll take it under consideration and see how it may influence other things. As of 2.0.0 a lot is changing under the hood and reflection has been removed in favour of macros, that aside this looks like a sensible request.

**Comment by peter-empen** [comment]
Looking at https://issues.apache.org/jira/browse/CASSANDRA-4175, it seems that long column names cause no penalty any more. Would you agree? If so, feel free to close this issue by "won't fix".

**Comment by alexflav23** [comment]
Hi @peter-empen It's fine, we are still considering a good way to implement this, for other reasons if not this. People should still have easy control over column names, though this is made interesting by the fact that the name is macro derived.

**Comment by alexflav23** [comment]
Hi @peter-empen At this stage the DSL you are after would be difficult to implement and it sounds like it's not longer required anyway. If you experience any problems with this in the future, please feel free to re-open this ticket or reach out via the known support channels.
