### ISSUE TITLE
Cannot set fetchSize with fetchEnumerator 

### ISSUE THREAD

**Issue by micpalmia** [outworkers/phantom#597]
Both `fetch` and `future` in `ExecutableStatement` offer a version accepting a `Modifier` that provides a `setFetchSize` method to set the corresponding parameter on the native driver. 

Unfortunately, there is only one parameterless version of `fetchEnumerator` in the `reactivestreams` package, and I thus seem not to be able to set Cassandra's fetch size.

Is there a way around this? So far, I created my own `fetchEnumerator` (see [here](https://gist.github.com/micpalmia/59a04766a6516839b815119493bd64f4)) but maybe there is a faster cleaner way.

If this is the only way, should I make PR to add my `fetchEnumerator` to the `reactivestreams` package?

**Comment by alexflav23** [comment]
Hi @micpalmia,

Thank you for reporting this, you are correct. We will add a variant of this method that allows settings a modifier on the query being executed. Are you using 2.0.x or still on 1.x series?

Regards.

**Comment by micpalmia** [comment]
Hey, sorry for the delay. We are using 1.26, but I solved my issue more simply by using the result of `future `, that can be parametrized. Thank you anyways!

**Comment by alexflav23** [comment]
Hi @micpalmia, no worries, I am going to close this as it's fixed in 2.0.x series of phantom. I'm not sure we intend to do a whole lot of back porting of things just yet, but it may be possible in the future, otherwise it may mean an upgrade will give you what you want for free.
