### ISSUE TITLE
Sum function

### ISSUE THREAD

**Issue by moscowart** [outworkers/phantom#600]
Hi guys, is there `sum` function implemented for querying? Can't find it.

**Comment by alexflav23** [comment]
HI @moscowart,

Coming up in the next release, it's not there currently!

Regards.

**Comment by moscowart** [comment]
Cool! Thanks

**Comment by haggy** [comment]
@alexflav23 what's the status on the next release? We are currently blocked because we cannot figure out a way to perform a sum using Phantom. Do you have an available workaround while we wait for the next release?

**Comment by alexflav23** [comment]
Hi @haggy,

Apologies about this, everything is done, 2.9.0 is going live in 2 hours. `sum`, `min`, `max` and `avg` all available by default.

```scala
 val record = gen[PrimitiveRecord]

    val chain = for {
      _ <- database.primitives.store(record).future()
      res <- database.primitives.select.function(t => avg(t.long)).where(_.pkey eqs record.pkey).one()
    } yield res

    whenReady(chain) { res =>
      res shouldBe ...
    }
```

Regards,

**Comment by desertigloo** [comment]
Thanks for getting this out -- this is a huge bonus for me using phantom, very excited to implement.
