### ISSUE TITLE
Scala 2.12 for Phantom DSL

### ISSUE THREAD

**Issue by pradyuman** [outworkers/phantom#603]
Any idea on when we might be able to get a scala 2.12 artifact for phantom-dsl?

**Comment by alexflav23** [comment]
@pradyuman It's already out for phantom 2.0 starting with version 2.0.12

**Comment by pradyuman** [comment]
Is this for phantom-dsl?

I've added this line to the top of my build.sbt:
`resolvers += Resolver.bintrayRepo("outworkers", "oss-releases")`

And have this in my libraryDependencies:
`"com.websudos" %%  "phantom-dsl" % "2.0.13",`

But I still can't find the 2.12 artifact.

**Comment by alexflav23** [comment]
HI @pradyuman,

Have a look [here](https://github.com/outworkers/phantom/tree/feature/2.0.0#200-migration-guide).

Regards.

**Comment by abhsrivastava** [comment]
@alexflav23 the link above is dead. any idea where I can find it? on maven central is only having scala 2.11  https://mvnrepository.com/artifact/com.websudos/phantom-dsl

**Comment by abhsrivastava** [comment]
Wait found it. I think the company is now called "outworkers"

https://mvnrepository.com/artifact/com.outworkers/phantom-dsl_2.12/2.20.0

**Comment by alexflav23** [comment]
@abhsrivastava There has been massive upgrade work to phantom since the name change, so there's 1.5 - 2 years of development basically since then. You need to have a look at the migration guide for more details, there will be code change required, but you will get a lot of cool new stuff.
