### ISSUE TITLE
update statement produces incorrect CQL

### ISSUE THREAD

**Issue by nukemichaels** [outworkers/phantom#613]
I have a problem with phantom-dsl 2.0.1. I'm getting incorrect CQL for update statements.
My update:
```scala
                 update
                  .where(_.Producer eqs key.producer)
                  .and(_.MetricName eqs key.metric)
                  .and(_.Date eqs key.date)
                  .modify(_.LastDt setTo lastMetric.metricDatetime)
                  .and(_.LastValue setTo lastMetric.value)
                  .and(_.Values putAll pairs)
```
Generated CQL:
> com.outworkers.phantom - Executing query: UPDATE metrics_test.metric_values WHERE producer = '뫽똟죞挨롥岛䥭㳲ᦈ楸' AND metric = '▮뼲퐂绔薛䙞㫡麉薅慥' AND dt = '2017-01-26' AND values = values + {1485441867255 : 0.0786719051203193};

Exception thrown on update execution:
> org.scalatest.exceptions.TestFailedException: The future returned an exception of type: com.datastax.driver.core.exceptions.SyntaxError, with message: line 1:34 mismatched input 'WHERE' expecting K_SET (UPDATE metrics_test.metric_values [WHERE] producer...).

**Comment by alexflav23** [comment]
Hi @nukemichaels,

I will admit I am very surprised this is happening as we do have tests to cover all these scenarios but I will follow up with the example to figure out where the problem lies in the serialisation logic of UPDATE queries.

Thank you for reporting this.

Regards,
Flavian

**Comment by nukemichaels** [comment]
Thank you Flavian!

Forgot to mention that I'm getting this exceptions with embedded cassandra instance in unit-tests.

**Comment by nukemichaels** [comment]
I don't understand what kind of mystic it was, but I can't reproduce this issue after clean project rebuild. Everything works as expected.
Take my apologies.
