### ISSUE TITLE
Please publish phantom-sbt under com.outworkers

### ISSUE THREAD

**Issue by PatrickRoumanoff** [outworkers/phantom#614]
I spend a couple of hours trying to figure out why I couldn't resolve com.outworkers.phantom-sbt just to discover it just doesn't exist.

Using  the blog http://outworkers.com/blog/post/phantom-tips-tip2-testing-with-phantom-sbt  as a source of information. I finally found out the comment in the blog that fixes the resolution by referencing the com.websudos package.

I also understand that because of sbt phantom-sbt is not available for 2.11 which did add to the confusion because I tried to compile it myself just to discover the incompatibilities.

What is the blocker to run the build for 2.10 and publish phantom-sbt under com.outworkers? What can I do to help?

**Comment by ggcampinho** [comment]
I also had trouble following the post and even took a look in the plugin itself, but the documentation also doesn't reflect the current status:

https://github.com/outworkers/phantom/blob/develop/phantom-sbt/src/main/scala/com/outworkers/phantom/sbt/SbtPlugin.scala#L35

**Comment by alexflav23** [comment]
Hi @PatrickRoumanoff @ggcampinho We are working hard on a far more powerful SBT module that allows you to choose a testing backend between CCM and Embedded Cassandra, and that will also streamline the entire logging mechanism, specify a Cassandra version, a cluster size, and more, all from within SBT config.

It will also give you the ability to initialise schemas using SBT, as well as dump the entire schema into a CQL file you can use as part of a CI or deployment process, so it does come with enormous benefits and completely eliminates "COLUMN FAMILY ID MISMATCH" style errors that sometimes occur if multiple connectors concurrently attempt to initialise schemas.

This will ship in the next few weeks as it's a huge amount of work gone in, but we are working to solve this problem as well as add far more powerful functionality.

**Comment by alexflav23** [comment]
Hi @PatrickRoumanoff Fixed as of 2.12.2 that should be live shortly, the SBT plugin is now auto-published. It still has all the common pitfalls as we are investing heavy development effort into the more advanced Cassandra integration setup inside pro, but at least it will get the job done.

**Comment by eugenemiretsky** [comment]
Hi @alexflav23, 
There is still nothing in the outworkers mvn ( https://mvnrepository.com/artifact/com.outworkers). Generally, what is the latest version of phantom-sbt? I understand it is no longer supported.

**Comment by alexflav23** [comment]
@eugenemiretsky You need this in your `plugins.sbt`: `Resolver.bintrayIvyRepo("outworkers", "oss-releases")`
