### ISSUE TITLE
incorrect column order creation when creating schema automatically 

### ISSUE THREAD

**Issue by 123avi** [outworkers/phantom#618]
using database.createAsync()
on this object 
```
case class Foo(id: String, key: String, ts:Long)
abstract class CassandraFooModel extends CassandraTable[CassandraFooModel, Foo] {
  override def tableName = "my_table"
  object id extends StringColumn(this) with PartitionKey[String]
  object key extends StringColumn(this) with PrimaryKey[String] with ClusteringOrder[String]
  object ts extends LongColumn(this) with PrimaryKey[Long] with ClusteringOrder[Long] with Ascending
...

```
yields the following statement 
`CREATE TABLE IF NOT EXISTS mykeyspace.my_table (id text, key text, ts bigint, PRIMARY KEY (id, ts, key)) WITH CLUSTERING ORDER BY (ts ASC, key DESC);`

I expected that the Primary key will by the model order **(id, key, ts)** i.e
`PRIMARY KEY (id, key, ts)) WITH CLUSTERING ORDER BY (ts ASC, key DESC);`

**Comment by alexflav23** [comment]
Hi @123avi This doesn't sound very good, what version of phantom are you using? Looks like it may be a reasonably old one, have you checked out `2.1.0`?

**Comment by 123avi** [comment]
@alexflav23 , thanks for the quick response.
I am using the following dependencies :
```
 "com.websudos" %% "phantom-dsl" %"1.29.5",
 "com.websudos" %% "phantom-reactivestreams" % "1.29.5",
```

and ```database.createAsync()```

**Comment by alexflav23** [comment]
Hi @123avi I would upgrade to the newest Phantom, there are many many benefits and a lot of code you can just get rid off in `2.0.0`, such as you don't have to manually define `fromRow` anymore, or indexes don't require type arguments etc.

**Comment by 123avi** [comment]
@alexflav23 Thanks, that is awesome . just one question - is there any change in the log as well ? it seems that I do not see the queries log anymore

**Comment by alexflav23** [comment]
Hi @123avi Yes, we removed the hardcoded `logback` dependency in favour of a raw SLF4J api, so you will have to manually setup logback dependencies for logs to work. This was done so other users could for instance configure `log4j2` should that be their desired logging framework.

**Comment by alexflav23** [comment]
@123avi I am going to close this, as the macro bugs that were causing this inconsistency have long been fixed, it's just a question of you upgrading. Hopefully that answers your query.

**Comment by 123avi** [comment]
@alexflav23 definitely , thanks

**Comment by rtatavarty** [comment]
I am afraid I hitting the same issue in version 2.1.2. I would like to create a new issue for this instead of working on a closed one - @alexflav23 can suggest his preference.

The table has a few clustering keys with their own clustering order as show below:

```scala
case class UsageByDev(
  key: String,
  dh: String,
  date: DateTime,
  aid: String,
  did: String,
  st: DateTime,
  et: DateTime)

class UsageByDevs extends CassandraTable[IUsageByDevs, UsageByDev] {
  object key extends StringColumn(this) with PartitionKey
  object dh extends StringColumn(this) with PartitionKey
  object date extends DateTimeColumn(this) with PrimaryKey with ClusteringOrder with Descending
  object aid extends StringColumn(this) with PrimaryKey with ClusteringOrder with Ascending
  object did extends StringColumn(this) with PrimaryKey with ClusteringOrder with Ascending
  object st extends DateTimeColumn(this) with PrimaryKey with ClusteringOrder with Ascending
  object et extends DateTimeColumn(this)
}
```

But ```table.create.ifNotExists()``` threw errors as follows:

```log
[error] c.o.phantom - The order of columns in the CLUSTERING ORDER directive must be the one of the clustering key (date must appear before aid)
```

Upon turning on tracing in Cassandra and capturing the queries, the following was tried during create:

```sql
CREATE TABLE IF NOT EXISTS harvest_production.ns_app_usage_by_devices (aid text, dh text, st timestamp, key text, et timestamp, date timestamp, did text,
PRIMARY KEY ((key, dh), date, aid, did, st))
WITH CLUSTERING ORDER BY (st ASC, date DESC, did ASC, aid ASC);
```

I have got a few tables like this and it fails on all of them.
