### ISSUE TITLE
[documentation] Out of date for 2.x

### ISSUE THREAD

**Issue by haggy** [outworkers/phantom#624]
Hi,

I recently upgraded from 1.x to 2.x and noticed that the blog, which is highlighted as a good "Getting Started" guide is very out of date. Many things in the Connector blog are now invalid. Not sure if this is already on your radar but just wanted to let you know.

http://outworkers.com/blog/post/phantom-tips-3-understanding-phantom-connectors

**Comment by alexflav23** [comment]
Hi @haggy,

Thank you for reporting this, it's indeed become a problem and we are actively working to fix it in increments. We will leave this issue open, but our new blog post engine will be capable of targeting specific version ranges of our products, so hopefully with versioned documentation things will be a lot easier in the very near future.

Regards.

**Comment by haggy** [comment]
Great thanks! Keep up the good work!

**Comment by alexflav23** [comment]
Hi @haggy all our blog posts have now been updated! Thank you for the pointing it out!

**Comment by prettynatty** [comment]
I'd like to point out that also project website url in repository description is invalid: http://outworkers.github.io/phantom/
