### ISSUE TITLE
eqs phantom not work when using implicit def 

### ISSUE THREAD

**Issue by riBN** [outworkers/phantom#629]
I write an implicit  method that it return Int value.
`import com.websudos.phantom.dsl._`
` import scala.language.implicitConversions`
` implicit def getValue(a: UserId): Int = a.value`
and a method to selet from the data base 
` def get(userId: UserId) = {
        select
          .where(_.userId eqs userId)
          .one()
  }`

but I have this error : value eqs is not a member of object x$3.userId

**Comment by alexflav23** [comment]
First I'd recommend that you upgrade to a more recent version of phantom, like 2.1.3.

After that, you can do:

```scala
// I'm assuming UserId is a case class
case class UserId(value: Int)
implicit val userIdPrimitive = Primitive.derive[Int, UserId])(_.value)(UserId.apply)
```

On a separate note, I would strongly advise that you stick to the default `uuid` type for IDs, for various scaling and unicity considerations.

**Comment by riBN** [comment]
my phantom version is 1.29.6 and this solution is not work

**Comment by alexflav23** [comment]
Hi @riBN Yes, you need a newer phantom for `Primitive.derive[Type]`. The problem you have is that the two implicits do not get applied, phantom already applies an implicit to `_.userId`.

```scala
def get(userId: UserId) = select .where(_.userId eqs userId.value) .one()
```

**Comment by alexflav23** [comment]
Hi @riBN I'm going to close this as it's not really a framework issue, but a question of you upgrading phantom or changing the approach as it's a Scala limitation not a phantom one.
