### ISSUE TITLE
Unable to trigger DC failover

### ISSUE THREAD

**Issue by ksilin** [outworkers/phantom#632]
I have a multi-DC setup running - 4 nodes in DC1 (replication 4) and 3 nodes in DC2 (replication 3). DC-1 is the local one. I am trying to induce a DC failover by running a simple read loop and shutting down DC-1 nodes.

started with the [official example](https://github.com/thiagoandrade6/cassandra-phantom) and extrapolated from there:

my connection establishment:

```
val hosts = config.getStringList("host")
val keyspace: String = config.getString("keyspace")

val maybeLocalDc = config.as[Option[String]]("local_datacenter")
val lbPolicyBuilder = DCAwareRoundRobinPolicy.builder
  .allowRemoteDCsForLocalConsistencyLevel()
val lbPolicy =
  maybeLocalDc.fold(lbPolicyBuilder)(lbPolicyBuilder.withLocalDc).build()

lazy val connector: CassandraConnection = ContactPoints(hosts)
  .withClusterBuilder(
    cb => {
      cb.withCredentials(
          config.getString("username"),
          config.getString("password")
        )
        .withLoadBalancingPolicy(lbPolicy)
    }
  )
  .keySpace(keyspace)
```

Load balancing policy has no effect. Setting the local DC in the settings or leaving it empty has no effect

The consistency level of the query is explicitly set to `ONE`, so I assumed that a failover should occur:

```
def getBySongId(id: UUID): Future[Option[Song]] = {
  select
    .where(_.id eqs id)
    .consistencyLevel_=(ConsistencyLevel.ONE)
    .one()
}
```

However immedately after the last node in DC1 is shut down, an error occurs:

```
Exception in thread "main" com.datastax.driver.core.exceptions.TransportException: [/XX.XX.XX.XX:9042] Connection has been closed
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1131)
	at com.datastax.driver.core.Connection$ConnectionCloseFuture.force(Connection.java:1116)
	at com.datastax.driver.core.Connection.defunct(Connection.java:424)
	at com.datastax.driver.core.Connection$ChannelCloseListener.operationComplete(Connection.java:1073)
	at com.datastax.driver.core.Connection$ChannelCloseListener.operationComplete(Connection.java:1063)
...
```

Is this behavior expected? Is there a setting I forgot, is there a test/example I could refer to?

Phantom 2.0.2, Scala 2.11.8, DSE 5.0.6

**Comment by ksilin** [comment]
There were some settings missing, which seems to be required for a multi-DC failover. The `LocaBalancingPolicy` needs to be explicitly enabled to use remote hosts: 

`lbPolicyBuilder.withUsedHostsPerRemoteDc(2).allowRemoteDCsForLocalConsistencyLevel()`

further, the `ClusterBuilder` seems to be more robust if it can downgrade query consistency: 

`cb.withRetryPolicy(DowngradingConsistencyRetryPolicy.INSTANCE)`

**Comment by alexflav23** [comment]
Hi @ksilin Thank you for this, I think we should add a compile time set of restrictions around `ClusterBuilder`.

**Comment by ksilin** [comment]
Yeah, `ClusterBuilder` could use better/safer defaults. We did not notice perf degradation or other adverse effects after enabling failover and it took a while to figure out. This is the only example I have currently, but who knows :)
