### ISSUE TITLE
Dead links to "Getting started with phantom"

### ISSUE THREAD

**Issue by magoeke** [outworkers/phantom#636]
Hi :)
I want to use scala and cassandra. After looking for a driver/library that suits these needs I found phantom. My problem now is that the link to the [getting started](http://outworkers.com/blog/post/a-series-on-phantom-part-1-getting-started-with-phantom) is dead and I don't really know how to start with phantom. 

> The Requested URL /blog/post/a-series-on-phantom-part-1-getting-started-with-phantom was not found on this server 

I'd love if you could fix the link to the tutorials.

Best regards, Max

**Comment by alexflav23** [comment]
Hi @magoeke Thank you for reporting this, it's a deployment issue we have been experiencing with AWS that is being resolved as we speak!

**Comment by magoeke** [comment]
Thank you!
