### ISSUE TITLE
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [varchar <-> foo.bar.MetricName]

### ISSUE THREAD

**Issue by melodious** [outworkers/phantom#644]
I am trying to convert my queries to use prepared statements in order to get the benefits of Token Aware load balancing. I have several custom types that were working well with Phantom prior to using the prepared statements. Now I get this "Codec not found" error at runtime. 

Any tips for how to fix this?

Thanks!

**Comment by alexflav23** [comment]
Hi @melodious,

Yes this is a known problem, we rely on the datastax java driver to do some of the lifting of queries as there is quite a complex internal mechanism to replace. We are working on that, because their mechanism is incredibly slow and causes very real performance problems in collections and so on, but at this moment in time you will have to add a new codec to the registry sadly, and that will allow you to correctly deal with this problem.

Regards.

**Comment by melodious** [comment]
OK. Thanks. I created the codecs.

**Comment by alexflav23** [comment]
HI @melodious You can track progress on #646 , most of the work is fortunately complete, it will be a bit more to make prepared statements use the Scala macro powered derivation of serializers, but it will happen one way or the other.

**Comment by alexflav23** [comment]
Hi @melodious,

Work is coming to an end on #668 now, `PreparedStatement` no longer requires the runtime lookup of `CodecRegistry`, which means all you need to do is to define the implicit primitive with `Primitive.derive` which you are doing now and everything will work.

There will also be a massive performance increase with the new API, but that are a few outstanding failing tests still, so a couple more days and 2.8.0 should be out to fix all of this.

Regards.

**Comment by melodious** [comment]
@alexflav23 Thank you so much for the update! I'm looking forward to the new release!

**Comment by melodious** [comment]
@alexflav23 Is this change in the latest release?

**Comment by alexflav23** [comment]
Still blocked on #668, last few days of waiting!

**Comment by alexflav23** [comment]
@melodious Fixed in 2.8.0, on Maven Central in the next 2 hours! Finally here, query throughput should go significantly up as well!
