### ISSUE TITLE
Phantom SBT plugin does not respect logback settings.

### ISSUE THREAD

**Issue by jtownley** [outworkers/phantom#649]
Problem: Phantom SBT plugin does not respect logback settings. Nor does there appear to be away to change the log settings.

Effect: Test logs are spammed with DEBUG and INFO level messages making the ability to find problems unrelated to Cassandra very difficult.

Example: https://github.com/jtownley/PhotomSBTBugExample  <- This is a working example application to demonstrate the issue.

**Comment by kolemannix** [comment]
I am also experiencing this issue and it is very frustrating.

**Comment by alexflav23** [comment]
@jtownley @kolemannix This is because the embedded cassandra plugin we use by default will natively enforce `log4j`, so it expects a Log4J configuration in scope, in it's own isolated JVM, or for you to add the bridge manually for `log4j-over-slf4j`, and that should make it work.

**Comment by jtownley** [comment]
@alexflav23 Thanks for your response. I am not sure I follow what you are saying here. Are you aware of an example of where this is being done or can you be more specific?

**Comment by oschrenk** [comment]
Did somebody find a way to silence the log?

I put a `log4j.properties`, `log4j2.xml` and a `logback-test.xml` in `src/test/resources` and none of them is picked up. 


@alexflav23 Can you be more specific what you mean with "expects a Log4J configuration in scope"?

**Comment by alexflav23** [comment]
Hi @oschrenk The one we used in the past was `log4.properties` with the old school DSL, and that seemed to do the job, it needs to be in `src/test/resources` for every module that's running embedded Cassandra tests, if I remember that correctly.

We have dropped this plugin entirely, as Embedded Cassandra isn't very reliable or interesting, and we are working on a replacement tool for it. I've outlined the details of that in #614, it will not be available open source, but it will do a far far greater job and giving you what you need.

I'm sorry I don't have a great answer, we have long moved away from Embedded Cassandra.

**Comment by alexflav23** [comment]
@oschrenk Any luck with this? Just double checking to see if the ticket can now be closed.

**Comment by kolemannix** [comment]
@alexflav23 I'll try this out today and let you know.

**Comment by kolemannix** [comment]
Looks like it did not work - here is the `log4j-test.properties` file I added in `src/test/resources`: 
```
log4j.rootLogger = ERROR, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.conversionPattern=%m%n

log4j.logger.org.apache.cassandra.db.Memtable=ERROR, console
```

But I still see debug logs, even from the `org.apache.cassandra.db.Memtable` that I set to `error`. Anything I missed?

**Comment by oschrenk** [comment]
As far as I remember I didn't have any luck but unfortunately I'm no longer on the project, so I can't retry.

**Comment by velotelo** [comment]
Same problem here. Any luck on fixing this anyone?

**Comment by wsargent** [comment]
It looks like the underlying PhantomSbtPlugin comes from Cassandra-Unit, which uses "/log4j-embedded-cassandra.properties"

https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit/src/main/java/org/cassandraunit/utils/EmbeddedCassandraServerHelper.java#L48

https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit/src/main/resources/log4j-embedded-cassandra.properties

**Comment by hsn10** [comment]
I created SBT plugin which fixes the log problem.

https://gitlab.com/hsn10/cunit-sbt

During testing i found that Cassandra Unit is _really buggy software_ and i do not recommend its use in integration / testing. Just run standalone Cassandra and write script for init / cleanup, you need to have these for application deployement anyway.

**Comment by alexflav23** [comment]
As phantom SBT is no longer part of this anymore, it's time to close this issue.
