### ISSUE TITLE
Switch DateTime type to java.time instead of joda time?

### ISSUE THREAD

**Issue by smartnose** [outworkers/phantom#653]
This is more of a question than a request: now that more libraries are using java 8 date time types. Would you consider migrating date time types from joda to JDK default types? Having two different date time types in my project is causing some mild inconvinience

**Comment by mmatloka** [comment]
There is a seperate package for JDK8: https://github.com/outworkers/phantom/tree/develop/phantom-jdk8/src :)

**Comment by alexflav23** [comment]
```scala
libraryDependencies ++= Seq(
 ...
 "com.outworkers" %% "phantom-jdk8" % version
)
```
And then in your code:

```scala
import com.outworkers.phantom.jdk8.dsl._
```

It has support for a bunch of things, most importantly the standard `ZonedDateTime` and `OffsetDateTime`.
