### ISSUE TITLE
Constraining by multi-part WHERE conditions

### ISSUE THREAD

**Issue by leoromanovsky** [outworkers/phantom#672]
I'm unable to determine how to structure phantom code to be able to generate an `WHERE` constraint like shown below:

```
SELECT * FROM leaderboard WHERE game_id = 123 AND
  (elapsed_time, timestamp) < (235, 1331382417)
  order by elapsed_time DESC, timestamp DESC limit 5;
```

This has been verified to work when issued in the above form.

Something like this does not compile:

```
select
  .where(_.game_id eqs game_id.id)
  .and( (_.elapsed_time, _.timestamp) gt (elapsedTime, timestamp) )
  .limit(6)
  .consistencyLevel_=(ConsistencyLevel.QUORUM)
  .collect
```

**Comment by alexflav23** [comment]
Hi @leoromanovsky You use the `token` functions. Look [here](https://github.com/outworkers/phantom/blob/develop/phantom-dsl/src/test/scala/com/outworkers/phantom/builder/serializers/SelectQuerySerialisationTest.scala#L185).
