### ISSUE TITLE
How do remove a key-value pair from Map column?

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [outworkers/phantom#675]
As I can see from the code https://github.com/outworkers/phantom/blob/37eccb3f9e1a2f5ed44f20020bffa6bcc8179f68/phantom-dsl/src/main/scala/com/outworkers/phantom/builder/ops/Modify.scala#L171-L192

Map Column supports `set`, `put` and `putAll` operations. But how can remove the key-value pair completely?
Thank you for your help!

**Comment by alexflav23** [comment]
Hi,

Sorry, this should really be in the docs, I'm going to add a ticket for us to fix that.

```
db.recipes.delete(_.map(key)).where(_.url eqs url).queryString
```

Regards,
Flavian

**Comment by AnatoliiStepaniuk** [comment]
Flavian, thank you for such a quick response!
It's nice to see the project so alive!
