### ISSUE TITLE
Update record that matches multiple where clauses

### ISSUE THREAD

**Issue by GRpro** [outworkers/phantom#681]
Hi,

I am trying to update records that matches multiple conditions but run into issues.
Have the following table definitions:

```scala
case class Item (
  item1: String,
  item2: String,
  weight: Double
)

class ItemsTable extends CassandraTable[Items, Item] {

  object  item1 extends StringColumn(this) with PartitionKey
  object  item2 extends DoubleColumn(this) with ClusteringOrder with Descending
  object weight extends StringColumn(this) with ClusteringOrder with Ascending


  override def fromRow(row: Row): Item = {
    Item(
      item1(row),
      item2(row),
      weight(row)
    )
  }
}

abstract class Items extends ItemsTable with RootConnector {
  def updateSimilarity(item: Item): Future[ResultSet] = {
    update
      .where(_.item1 eqs item.item1)
      .and(_.item2 eqs item.item2)
      .modify(_.weight setTo item.weight)
      .future()
  }
}
```
The compiler argues 

```
value setTo is not a member of object x$5.similarity
[error]       .modify(_.weight setTo item.weight)
[error]                            ^
```

What I am doing wrong here?
Thanks.

**Comment by alexflav23** [comment]
@GRpro What version of phantom are you using?

**Comment by GRpro** [comment]
The version is 2.7.5

**Comment by alexflav23** [comment]
@GRpro You are not paying attention to your code `item.weight` is a `Double` in your case class and a `String` in your phantom DSL schema.

**Comment by GRpro** [comment]
@alexflav23 , it was a typo here in description, that is because I didn't post the whole piece of code because of complexity and made some changer right here. 
I've just updated the description. 

Could you please check this again?
Thanks a lot!
