### ISSUE TITLE
Does phantom support counter double columns?

### ISSUE THREAD

**Issue by GRpro** [outworkers/phantom#688]
Hi,

I have a usecase where the floating point value should be continuously updated.
I see there is a support for counter columns https://github.com/outworkers/phantom/wiki/Counter-columns but from the tutorial it is not clear whether we can increment or decrement it by a double value.

Thanks.

**Comment by alexflav23** [comment]
Hi @GRpro Counters are of type `Long` or `bigint` and as far as I know Cassandra only allows integer increments and decrements. Link [here](http://docs.datastax.com/en/cql/3.1/cql/cql_using/use_counter_t.html). You can try to increment by another type in `cqlsh` see what happens.

**Comment by GRpro** [comment]
It seems cassandra really does not support double  float counters:
![image](https://cloud.githubusercontent.com/assets/10188125/26283083/7fb5a458-3e29-11e7-840c-062b4f7f28fa.png)

**Comment by alexflav23** [comment]
@GRpro Yep, you should really rely on counters anyway, they don't have a good reputation when it comes to really high scale. People generally prefer aggregation. It would take me far too long to get into all the details, but I will close this issue in the interim.
