### ISSUE TITLE
Deleting all rows that match one of many primary keys, using ifExists

### ISSUE THREAD

**Issue by manumena** [outworkers/phantom#696]
Hi, I want to do a delete query where I know one of the primary keys and then return true if the deletion was successful or false if not. To do so I'm trying this

    def delete(userId: String): Future[Boolean] = {
        val result = delete().
            where(_.userId eqs userId)
            .ifExists
            .future()

        result.transform(_.wasApplied(), ex => throw DatabaseQueryException("...", ex))
    }

I think that the matter is that userId is not the only primary key.
This is the message I'm receiving

> DELETE statements must restrict all PRIMARY KEY columns with equality relations in order to delete non static columns

It works properly if I add `.and(_.otherPrimaryKey eqs primaryKey)` to the where clause, but that would be in case I want to delete one particular row.

I'm using `.ifExists` only because I need to know if there were rows with that userId or not, but maybe there is a better way?

**Comment by alexflav23** [comment]
`select.count` before the delete query? The performance penalty is minimal since you delete a partition at a time anyway.

**Comment by alexflav23** [comment]
I'm going to close this ticket as it's not related to phantom, but to your very particular schema and the fact that it sounds like it doesn't match requirements just yet. In the way it's currently designed, you need to batch deletes for every row inside the user partition.
