### ISSUE TITLE
Update Query having Using Clause with custom Timestamp

### ISSUE THREAD

**Issue by anchakrab** [outworkers/phantom#699]
Is there a way to use USING TIMESTAMP for an UPDATE query in phantom? I have an update query as --
```
      update
      .where(_.id eqs xyzId)
      .modify(_.number setIfDefined dtoNumber)
      .ifExists
```
I am trying to see if I can update records only for cases where cell timestamp is latest (to avoid race condition issues), with something similar to what we have for INSERT queries --
```.using(new UsingClause.Condition(CQLQuery(s"TIMESTAMP ${dto.someAttribute.getMillis * 1000}")))```

**Comment by alexflav23** [comment]
What's wrong with using `timestamp` method on `UpdateQuery` ? You can either pass the timestamp as a long or as an `org.joda.time.DateTime`.

```scala

import com.outworkers.phantom.dsl._
import org.joda.time.{ DateTime, DateTimeZone }

      update
      .where(_.id eqs xyzId)
      .modify(_.number setIfDefined dtoNumber)
      .timestamp(new DateTime(DateTimeZone.UTC))
      .ifExists
```

**Comment by alexflav23** [comment]
@anchakrab This is already available in phantom, the only thing I can think of is that your version of phantom may be too old. I'm going to close this ticket as it would appear it's a solved problem.

**Comment by anchakrab** [comment]
I am using latest phantom 2.10.0 version. With this approach I am getting following exception --
```
"ex":"class com.datastax.driver.core.exceptions.InvalidQueryException",
       "msg":"Cannot provide custom timestamp for conditional updates"
```
So the question is, how to use `IF EXISTS` and `Custom TIMESTAMP` in the same `UPDATE` query?

**Comment by alexflav23** [comment]
@anchakrab You obviously can't it seems, cause that's a Cassandra error. Are you saying the same query works if you execute it as a string?

**Comment by anchakrab** [comment]
My query looks like --
```
  val query = update
      .where(_.id eqs dto.Id)
      .modify(_.number setIfDefined dto.Number)
      .timestamp(dto.createdDate.getMillis * 1000)
      .ifExists
      println(query.qb.queryString)
      query.future()
```

**Comment by anchakrab** [comment]
Cassandra query doesn't work as well. So wanted to know if Phantom has a work around for this.

**Comment by alexflav23** [comment]
@anchakrab Why are you multiplying milliseconds by 1000 if Cassandra expects UTC timestamp in millseconds? Nope, Phantom has no workaround unfortunately.

**Comment by anchakrab** [comment]
We can ignore the multiplication in the example (was doing for a different reason), not multiplying doesn't resolve the problem though. So if there is no workaround for this, what would be the ideal way to update data into cassandra when I don't want an UPSERT behavior (i.e. I want to use IF EXIST) as well as I want to ensure updates don't happen with older data coming in at a later time (CUSTOM TIMESTAMP is supposed to take care of that)?
