### ISSUE TITLE
Unable to use ADT tables

### ISSUE THREAD

**Issue by prettynatty** [outworkers/phantom#700]
After upgrading from 2.1.1 to 2.10.0 we've got the following warning from the compiler:
```
Warning:scalac: 01:52:07.135 [NGSession 12: 127.0.0.1: compile-server] DEBUG com.outworkers.phantom.macros.TableHelperMacro - Supplied record type im.dlg.server.persist.AccessInterval has no fields defined, are you sure this is what you want?
```

that happens because we have a `sealed trait AccessInterval`, two case classes extending it and a `AccessIntervalTable extends Table[AccessIntervalTable, AccessInterval]` with a custom `fromRow` which returns one of the two children of AccessInterval.

Is it possible to implement such pattern in 2.10.0?

**Comment by prettynatty** [comment]
Right now class fiends are detected by macros for case classes and tuples. 
I could contribute a fix if we agree on API. For example, we could annotate fields applicable to a cassandra schema.

**Comment by alexflav23** [comment]
Hi @prettynatty,

You can still use ADT tables, someone asked us for them before, but you will have to manually define `fromRow` and `store` method. The macro doesn't traverse the ADT hierarchy. We are considering to add support for feeding in `HLists` and `Coproducts` from Shapeless to `Table`, so in the future it may be possible to do this natively, though currently it isn't possible to derive automated methods from ADTs, so just manually implement them.

The error is DEBUG only, to prevent errors, but you can ignore it.

Regards.

**Comment by alexflav23** [comment]
Hi @prettynatty, going to close this and open a new ticket, since what you are seeing are just compiler warnings if that's ok. We have added internal tickets to track and implement coproduct support for both shapeless and iota libraries through separate modules, but that doesn't sound like something that's absolutely required for you to progress right now.
