### ISSUE TITLE
option to force an individual query to be idempotent (for retries)

### ISSUE THREAD

**Issue by ManiacViper** [outworkers/phantom#710]
The idempotent flag right now can be set on the cluster but not on the statement level via Phantom.

This is allowed by the Datastax Cassandra driver but seems to be difficult to pass down via the Phantom driver.

This is needed to enable retries for idempotent write queries and some exceptions that are not retried by default for a read query.

**Comment by alexflav23** [comment]
@ManiacViper All the query methods on the underlying driver are exposed through the following syntax. I'll add a ticket to improve documentation on this, we know it's not as good as it should be, thank you for reporting this.

```scala
val query = database.primitives.store(row).future(_.setIdempotent(true))
```

**Comment by ManiacViper** [comment]
Oh okay, can I pass in the flag via the streaming module too? is there a
mechanism to do that?

**Comment by alexflav23** [comment]
Hi @ManiacViper, I don't think there is off the top of my head, would you like to post the example query you are after and we'll add the missing functionality. I closed the ticket as you didn't specify streaming, but happy to re-open if you can post a code example of what you expect to see.

**Comment by ManiacViper** [comment]
Hi @alexflav23, I'm using streams.publisher().
```
  import com.outworkers.phantom.streams._
 feedItems.publisher()(cassandraSession, KeySpace(cassandraConfig.keyspace), system.dispatcher)

```

 is there a way of setting it on the implicit Session maybe? if not I can look into it myself and have a PR soon for this if you want. Looked quickly into it and it looks like QueryOptions is the appropriate place maybe and could use that type as another implicit parameter in publisher method.

**Comment by alexflav23** [comment]
HI @ManiacViper,

You seem to be using it wrong, you should not have to provide any of those references explicitly, instead opt for using a `Database` wrapper class. That aside it's fine, we can definitely add the requested method signature. In the interim have a look [Database](https://github.com/outworkers/phantom/blob/develop/docs/basics/database.md).

Regards,

**Comment by alexflav23** [comment]
Hi @ManiacViper We are fixing this in the new phantom by replacing the generation mechanism with a free monad like interface. In short, we are implementing consistent options across all execution backends, including Scala Futures, Streams, Twitter Futures, Twitter Spools, Akka Streams, Play iteratees and the newly implemented Monix support.

**Comment by alexflav23** [comment]
@ManiacViper This is now fixed, in the latest `2.14.2` you can augment every single `SelectQuery` to become a streams producer. You can also pass in a statement modifier, like `_.setIdempotent(true)`, when you do that.

Have a look [here](https://github.com/outworkers/phantom/blob/develop/phantom-streams/src/main/scala/com/outworkers/phantom/streams/package.scala#L244), I hope this is the streaming you were referring to.

**Comment by ManiacViper** [comment]
Hey Flavian. Sorry for the delay in response.
Nice work, this is exactly what I meant,  this is pretty useful for
streaming apps.

Thanks

**Comment by alexflav23** [comment]
HI @ManiacViper We've added tests and everything else across the board to check that it is possible to do this properly across the various streaming implementations including reactive streams via `.publisher`, spools, and play iteratees so you should be pretty well covered by now . I'm working on writing some proper docs for this as well so for future use you can something you can refer to .
