### ISSUE TITLE
cassandra port number

### ISSUE THREAD

**Issue by hottelet** [outworkers/phantom#711]
Please provide the port number for the cassandra instance that runs when using SBT, and then Run.  I am using DevCenter, and need the login credentials, and port number, for localhost.  I tried port 9042, however, DevCenter can not connect:
The specified host(s) could not be reached.
All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
[localhost/127.0.0.1:9042] Cannot connect

**Comment by alexflav23** [comment]
9142
