### ISSUE TITLE
Removing "this" on dao fails to compile 

### ISSUE THREAD

**Issue by 123avi** [outworkers/phantom#713]
Hi,
I am using phantom `2.1.3` , IDE intellij
this how my mapping looks like:

```
case class Foo(mkey: String, value: Double, tags: Map[String, String])

abstract class FooDao extends CassandraTable[FooDao, Foo] {

  override def tableName = "metrics"

  object mkey extends StringColumn(this) with PartitionKey

  object value extends DoubleColumn(this)

  object tags extends `MapColumn[String, String](this)`

}
```
however when I remove `(this)` (as shown in the doc) it fails to compile, and weirdly it also mark the `(this)` on the `MapColumn` as "Not applicable"

**Comment by alexflav23** [comment]
Hi @123avi You are not following the doc properly, your version of phantom is too old and you need to mix in `Table` instead of `CassandraTable` to benefit from this new compact DSL. Try using `2.12.3` instead.

**Comment by 123avi** [comment]
Thanks !
