### ISSUE TITLE
phantom-sbt plugin JAR is not at Maven central

### ISSUE THREAD

**Issue by hsn10** [outworkers/phantom#745]
I tried to follow manual at http://outworkers.com/blog/post/phantom-tips-tip2-testing-with-phantom-sbt

After closer look, i discovered that on Maven central is only ivy metadata file - https://repo1.maven.org/maven2/com/outworkers/phantom-sbt_2.10_0.13/2.14.3/ no jar, so even if SBT is happy and does not complain about missing plugin, plugin itself is not working since no JAR was downloaded.

Correct configuration is to use bintray repository:
```
addSbtPlugin("com.outworkers" %% "phantom-sbt" % "2.13.4")
resolvers += Resolver.url("outworkers", url("https://dl.bintray.com/outworkers/oss-releases/"))(Resolver.ivyStylePatterns)

```

**Comment by alexflav23** [comment]
@hsn10 SBT jars cannot be published to Maven central since they follow Ivy style resolution. If you read the docs using Bintray is already there.
