### ISSUE TITLE
Problem upgrade from 1.28 to 2.14

### ISSUE THREAD

**Issue by git4sun** [outworkers/phantom#748]
My old project was built on 1.28. It doesn't seem to compile with play 2.6.x. So I am trying to upgrade to 2.14. But everything just breaks. 

`not found: type UUIDColumn
[error]   object id extends UUIDColumn(this) with PartitionKey[UUID]
`

I have this allover the place. I did `import com.outworkers.phantom.dsl._`. The migration guide doesn't say much about how to do the upgrade. And there is no tutorial of starting fresh with 2.x. So I am stuck here. Any help?

**Comment by alexflav23** [comment]
Hi @git4sun,

Please refer to [the migration guide](https://github.com/outworkers/phantom/blob/develop/docs/migrate.md#200-migration-guide) for details on this.

Regards.

**Comment by git4sun** [comment]
Where exactly is this addressed in the migration guide? I didn't find anything on specifics about what package I should import other than the dsl._. Would you mind point me to the lines?

**Comment by git4sun** [comment]
@alexflav23 the migration guide is not very helpful in this case. I finally figured out that CassandraTable should be Table. That's why all column types are not recognized.
