### ISSUE TITLE
Support "in" in prepared statement

### ISSUE THREAD

**Issue by fggarcia** [outworkers/phantom#750]
I was looking to build a select query

select * from table_name where partitionId = ? and key In ?

But In operation is not supported for prepared statement in phantom.

Driver support this

https://stackoverflow.com/questions/35069238/how-to-bind-in-clause-values-in-a-cql-3-prepared-statement

**Comment by alexflav23** [comment]
@fggarcia,

Thank you for the bug report, this is indeed not yet supported as it's a bit difficult to do prepared statements mixed with non prepared values in the same set at the type level, but we are working to include it in the next few releases.

Regards.

**Comment by alexflav23** [comment]
@fggarcia This works as of 2.18.0. You have to bind using `ListValue(args)` instead of just `List(a, b, c, ..)`

**Comment by fggarcia** [comment]
Thanks @alexflav23 !!! it works perfectly.
