### ISSUE TITLE
phantom-sbt do not works with cassandra 3.10+

### ISSUE THREAD

**Issue by hsn10** [outworkers/phantom#752]
I need higher cassandra version then 3.9 because of bug in cassandra (crash on query). Problem is that cassandra unit can not work out of box with higher cassandra versions then 3.9, so i cant just do _dependencyOverrides_

One line workaround needs to be added to sbt plugin:

https://github.com/jsevellec/cassandra-unit/issues/221

**Comment by alexflav23** [comment]
@hsn10 Thank you for the report, we will definitely look into it.

**Comment by hsn10** [comment]
I was not able to rebuild sbt plugin jar to test suggested workaround. Running publishLocal on sbt plugin created JAR just with manifest, so i updated to latest cassandra unit snapshot to fix problem.

**Comment by alexflav23** [comment]
@hsn10 Fixed in 2.16.0, will be published shortly. Thank you for this and apologies for the long winded follow up.
