### ISSUE TITLE
Migration to 2.x, enumcolumns doesn't work on eqs and setto

### ISSUE THREAD

**Issue by git4sun** [outworkers/phantom#753]
in UPDATE, SELECT queries, `eqs` and `setTo` doesn't work on EnumColumns. How to change that? 

`delete
      .where(_.uid eqs uid)
      .and(_.accountType eqs accoutType)
`

The error message: Type mismatch, expected: TokenConstructor, actual: BindingType

BTW, since `fromRow()` is not there any more, is there a place to customize the frowRow behavior?

**Comment by alexflav23** [comment]
@git4sun Please post the code for that enum problem, I have a suspicion. You can still `override def fromRow` and do whatever you want so yeah it's pretty straightforward to basically throw away what the macro does.

The macro does have a problem and it's not because of us but the Scala Macro lib, which doesn't let us read if the user already implemented this `fromRow` method, cause then we could issue warnings if the macro didn't work, or if overrides are invalid, but we are working on it.

**Comment by git4sun** [comment]
`
    
    import java.util.UUID
    import com.outworkers.phantom.column.MapColumn
    import com.outworkers.phantom.dsl._
    import play.api.libs.json.{Json, Writes}
    import scala.concurrent.Future
    object AdStatus extends Enumeration{
      type AdStatus=Value
      val Created = Value
      val Published = Value
      val Offline = Value
    }
    object AdModel extends Enumeration{
      type AdModel=Value
      val Open=Value("打开效果")
      val Click=Value("点击效果")
    }
    case class Ad(id: UUID,
              model: AdModel.AdModel,
              price: String="0.0",
              stats: Map[String, Double] = Map(),
              status:AdStatus.AdStatus=AdStatus.Published) extends Formatable[Ad]{
    }

    abstract class Ads extends Table[Ads, Ad] {
        object id extends UUIDColumn with PartitionKey
    
        object model extends EnumColumn[AdModel.type]

        object price extends StringColumn

      object stats extends MapColumn[String, Double]

      object status extends EnumColumn[AdStatus.type]
    }

    abstract class ConcreteAds extends Ads with RootConnector {
    
      def updateAd(ad:Ad):Future[ResultSet]={
            require(ad.id!=null)
            update.where(_.id eqs ad.id).modify(_.model setTo ad.model)
          .and(_.price setTo ad.price)
          .and(_.status setTo ad.status)
          .and(_.stats setTo ad.stats)
          .consistencyLevel_=(ConsistencyLevel.QUORUM).future
      }
    }

I got two errors: `modify(_.model setTo ad.model)` and `and(_.status setTo ad.status)`.  In another class where I used `(_.model eqs model)` also has the same error.

**Comment by git4sun** [comment]
I got it. The `EnumColumn[AdStatus.type]` should be `EnumColumn[AdStatus]`
