### ISSUE TITLE
if ALLOW FILTERING used allow build query using not indexed columns

### ISSUE THREAD

**Issue by hsn10** [outworkers/phantom#754]
If _ALLOW FILTERING_ CQL clause is used, _any_ not indexed column can be used in query. There are some restrictions depending on C* version for querying partial _PartitionKey_
> create table tokens(email text, t text primary key, expired int);
> insert into tokens(email,t,expired) values ('a@a', '323232', 5);
> insert into tokens(email,t,expired) values ('a@b', '345423232', 2);
> select * from tokens where expired > 2 allow filtering;
 t      | email | expired
--------+-------+---------
 323232 |   a@a |       5

I did not found way how to do it in Phantom. Current implementation does not allow queries of not indexed column (which matches cassandra) but _allow filtering_ does not change this.  There are some queries - such as data expiration which runs occasionally and would benefit from this feature.

Only possible way to get it work is by _cql(..) : QueryInterface_ or is there some way using implicit to turn col into _QueryColumn_ ?

**Comment by alexflav23** [comment]
HI @hsn10 This is an interesting edge case, you are right in saying this should work. If you have a little more time to invest, it would help to get an example Phantom schema with the exact queries you would expect to compile, and I will try to see this through asap for you in return.

Thank you!

**Comment by hsn10** [comment]
Here is testing case which should compile - https://github.com/hsn10/phantomtest

**Comment by alexflav23** [comment]
@hsn10 I've submitted a PR even to your fork showing how this feature now works, apologies for the lack of updates on this. It's been fixed and then we all forgot to update here. Please merge my PR to your fork and check if anything else is needed.

**Comment by hsn10** [comment]
FILTERING ISSUE is still not fixed. Second problem was fixed. I will merge your changes by hand and clear irrelevant files and make unit tests.

**Comment by alexflav23** [comment]
@hsn10 No problem, I think I just didn't understand what was going wrong, but we can work on it.

**Comment by alexflav23** [comment]
@hsn10 This has now been fixed in the latest release, based on your example. When it's out to Maven Central give it a try and let me know if you run into any trouble, otherwise closing this for now.
