### ISSUE TITLE
Add phantom-streams supported to prepared select queries

### ISSUE THREAD

**Issue by Vrolijkx** [outworkers/phantom#757]
Steam methods like:
```
publisher()
fetchEnumerator()
```
are at the moment not available on prepared queries for streaming. 
This because the ```ExecutableQueryStreamsAugmenter``` converter only works on ```SelectQuery``` and not on ```ExecutablePreparedSelectQuery```.

**Comment by alexflav23** [comment]
@Vrolijkx You have a point I think, but that's something we can definitely fix quickly, thank you for the bug report. I'll aim to get a release out for Monday with all this.

**Comment by alexflav23** [comment]
@Vrolijkx Fixed in 2.15.1, it will be published by CI shortly.
