### ISSUE TITLE
Using tuple type as partition key fails

### ISSUE THREAD

**Issue by hsn10** [outworkers/phantom#762]
If you want to use tuple type as partition key which is case supported by cassandra, it fails in phantom because invalid syntax CQL is generated for table creation. Using tuple in collection, indexed field or non primary key works without problem. 

I created sample project https://github.com/hsn10/phantomtest/tree/tuplepkey to reproduce issue

**Comment by alexflav23** [comment]
Hi @hsn10 I have a gut feeling this is to do with you deriving tuple primitives which also works by default.

**Comment by alexflav23** [comment]
Thank you for taking the time to create this, I will have a look during the weekend and have this fixed.

**Comment by hsn10** [comment]
I checked against 2.16.4 / 2.11 version and it is still not fixed. Can you look at it? It breaks my unit tests.

**Comment by alexflav23** [comment]
@hsn10 Fixed in 2.21.0 on Maven Central.
