### ISSUE TITLE
Latest phantom-sbt not on maven central

### ISSUE THREAD

**Issue by rohinisb** [outworkers/phantom#763]
Latest phantom-sbt is not available on maven central. The last version made available was version 1.26.1. It would be great if all phantom modules are available on central, mostly because central is widely used and mirrored which makes it easier. Was there any specific reason for not publishing just this module? Thanks

**Comment by alexflav23** [comment]
Hi @rohinisb SBT plugins can never be published to Central as they require Ivy paths not Maven ones sadly. Add `Resolver.bintrayRepo("outworkers", "oss-releases")` to your `plugins.sbt` and that should work.
