### ISSUE TITLE
DSL implicits conflict with Scala Async

### ISSUE THREAD

**Issue by jalaziz** [outworkers/phantom#767]
`QueryContext` and `DbOps` both define an `await` method. However, this method seems to serve little purpose as it's just a call to `Async.result`.

When using the DSL implicits, I ran into conflicts with our usage of the scala Async. Effectively, `import scala.async.Async._` and `import com.outworkers.phantom.dsl._` conflict.

I'm currently working around it  by using `import com.outworkers.phantom.dsl.{ await ⇒ _, _ }` for phantom, but I find it generally odd that phantom would expose the await method as an implicit in the global scope. I can see the convenience of it, but using `Async.result` is pretty easy as it is.

**Comment by alexflav23** [comment]
@jalaziz That method is not a convenience method so you wouldn't have to call `Await.result`, it's designed to abstract over various future backends. We can however rename the method to prevent such conflicts, as it's really intended for internal use.

Thank you for this, we never tried in conjunction with scala Async so we didn't know.

**Comment by jalaziz** [comment]
Ahh, makes sense. I only saw it being defined as `Await.result`, so just made the assumption.

If it's indeed only for internal use, renaming would be great!

**Comment by alexflav23** [comment]
@jalaziz Fixed in 2.16.0, will be released today. Thank you for the bug report once again.
