### ISSUE TITLE
Mixins columns no longer work in 2.X

### ISSUE THREAD

**Issue by jalaziz** [outworkers/phantom#768]
We have a use case where we place shared columns in traits and then inherit them when creating the table.

The `TableHelper` macro currently looks for the first table with columns, but doesn't check for partition keys. I understand that this was done to support inheritance. However, mixing in columns can be very useful when multiple tables all share the same columns.

An example can be found here: https://gist.github.com/jalaziz/f7f5030172acfccafb46a5d239975924

When defining tables with mixins, I find that compilation fails with `could not find implicit value for parameter helper: com.outworkers.phantom.macros.TableHelpe...`.

**Comment by alexflav23** [comment]
@jalaziz I think we need to work on formalising all the requirements for inheritance, and right now we are willing to champion those efforts. Before we explicitly marked this is a "not supported", and perhaps not make that explicit in the code, but I think right now there are quite a few people requesting this feature.

I'm going to open a separate issue with a proposal, it's reasonably straight forward, but just in case, so everyone can contribute and we can reach some kind of consensus on what this should look like.

**Comment by alexflav23** [comment]
I'm going to centralise this in #770, as there are many related tickets that have inheritance support as a root cause.
