### ISSUE TITLE
UDTs need to create automatically before creating the table

### ISSUE THREAD

**Issue by Rajitha15** [outworkers/phantom#771]
Hi team,

We are using UDTs in our project and now we are having an issue with auto table creations in test cases.  If you can give me the example of the creation of tables on fly in test cases it will be really great.

when i try this snippet 

```scala
import com.outworkers.phantom.builder.query.ExecutableStatementList

class TestDatabase(
  override val connector: CassandraConnection
) extends Database[TestDatabase](connector) {

  def initUds: ExecutableStatementList[Seq] = {
    new ExecutableStatementList[Seq](
      Seq(
        UDTPrimitive[Record].schemaQuery(),
        UDTPrimitive[RecordCollection].schemaQuery()
      )
    )
  }
}

override def createAsync()(implicit ex: ExecutionContextExecutor): Future[Seq[ResultSet]] = {
  initUds.sequentialFuture() flatMap(_ => super.createAsync())
}
```

then i am calling create.ifNotExists().future() i am getting below error 

Automatically initialising keyspace farallones with query:

```sql
CREATE KEYSPACE IF NOT EXISTS farallones WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1}; 
```

```scala
17:37:56.931 [pool-1-thread-1] ERROR com.outworkers.phantom - Failed to execute query CREATE TABLE IF NOT EXISTS farallones.parkingspot (parkingspotid text, name text, reservation boolean, handicap boolean, demarcated boolean, geocoordinates Corner, formfactor text, monitoringsensorid text, businessuse text, parkinggroupid text, typeofvehicle set<text>, howmetered text, undemarcatednumspots int, active text, ppv boolean, areaoftype set<text>, paystationid text, currentstatus int, orgid text, siteid text, isdeleted boolean, PRIMARY KEY (parkingspotid)); 
com.datastax.driver.core.exceptions.InvalidQueryException: Non-frozen User-Defined types are not supported, please use frozen<>
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:148)
```

thanks,
Rajitha

**Comment by alexflav23** [comment]
@Rajitha15 I think this is just the fact that you are using an older version of phantom/phantom-pro. 

Can you try bumping to the latest phantom-pro 0.15.0 working against phantom 2.15.5? Somewhere along the line there have been some upgrades to the entire mechanism, and quote important ones too.

Feel free to reach out, I am investigating the specific error to make sure it's been fixed in 0.15.0 like I think.

**Comment by Rajitha15** [comment]
i am not aware of the new release, where can i see new release details for phantom-pro

**Comment by Rajitha15** [comment]
I am expecting an example to create UDTs  in my previous post i used the ExecutableStatementList to create UDTs using createAsync but in latest release i cannot see that class. which one is replaced with that class ?

**Comment by Rajitha15** [comment]
this issue solved and thank yo so much for your support @alexflav23 . please close the ticket
