### ISSUE TITLE
Driver times out unexpectedly

### ISSUE THREAD

**Issue by dhuadaar** [outworkers/phantom#772]
I am executing a find query using the driver which times out event under light load of 300 requests. I have given sufficient head to  my 5 node cassandra cluster. Earlier I thought it could be due to GC pauses, but on analysing, this does not looks like an issue.

Cassandra version : 3.9
OS : Ubuntu 16.06 
phantom : 2.12.1

```
2017-11-15 11:31:03.494 c.o.phantom pool-71-thread-122 [ERROR] Failed to execute query SELECT * <my CQL query>;

com.datastax.driver.core.exceptions.OperationTimedOutException: [/cassandra_host:9042] Timed out waiting for server response
    at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:772) ~[stormjar.jar:?]
    at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1380) ~[stormjar.jar:?]
    at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:625) ~[stormjar.jar:?]
    at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:700) ~[stormjar.jar:?]
    at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:428) ~[stormjar.jar:?]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[stormjar.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

Let me know what all details you would need to help out on this.

**Comment by dhuadaar** [comment]
![screenshot from 2017-11-15 18-04-54](https://user-images.githubusercontent.com/14878279/32836542-28e82bb2-ca30-11e7-99b1-f81149a14a7e.png)

This is the latency as per node tool. My driver has a time out of 10s.

**Comment by alexflav23** [comment]
Hi @dhuadaar I am very happy to pursue this, but we will need a full scale measurable test that we can replicate, with the exact semantics of the table and everything else. I don't want to throw it out as it's very interesting.

The light load sounds like coming from the Cassandra end, as opposed to the driver side, so my bets currently are placed on optimising Cassandra further, because the problem is a timeout on the Cassandra end.

Do you want to create a separate repo to investigate specifics?

**Comment by dhuadaar** [comment]
Sure, let me know how can we go about it.

Also 
`The light load sounds like coming from the Cassandra end, as opposed to the driver side,  ....`

I earlier had the same feeling. But the nodetool shows no significant latency on hosts and this problem replicates only on the scala driver of outworkers. I tried drives in python as well to check and things are preety fine in the driver under similar load.

**Comment by alexflav23** [comment]
Hi @dhuadaar I don't want to disagree with that, if there are problems they need to be fixed. Can you please help with more details, either here or via email? I need some idea of the schema, queries, and load you are trying to perform, and we are more than happy to benchmark everything.

**Comment by alexflav23** [comment]
@dhuadaar What is your replication factor?

**Comment by dhuadaar** [comment]
Hi,
My replication factor is 3

**Comment by alexflav23** [comment]
Hi @dhuadaar Long time to follow up, but I'd like us to work against the same benchmark, phantom versions etc, to get comparable results and expected them not to be too divergent.

Any chance you have a reference schema you would like benchmarked, just so we can work against the same goal?

**Comment by dhuadaar** [comment]
Hello

We have been trying out various things and were able to solve the issue. I must say that the SQL mindset was the biggest blocker. 

We re-designed the schema and were able to handle load which was almost 30 times more than what was causing the issue with charm.

Thanks for taking this up. I would soon share details of old and new schema as it might be useful for people who could stuck in this situation in future. 

I think we can close this for now.
