### ISSUE TITLE
What to do with ResultSet in store/delete quries

### ISSUE THREAD

**Issue by eugenemiretsky** [outworkers/phantom#773]
More of a best practices/what other people are doing question. 
Delete and store return a Future[ResultSet] which is fairly meaningless. I don't want to propagate ResultSet outside of the Cassandra Database. 
The options are to map ResultsSet to 
1) Future[Entity]
2) Future[Unit]
What do you recommend?

**Comment by alexflav23** [comment]
Hi @eugenemiretsky, I guess it's up to the consumers. My advice is generally to preserve the `ResultSet` to as far as it makes sense, let's say a DatabaseController, and convert it to a `Future[Entity]` at the very end.

`ResultSet` much like its SQL counterpart, has a `wasApplied` method, which can tell you if an `update/delete` or whatever actually happened, and that can be neatly converted to either something as simple as a `Future[Boolean]` or some kind of entity.

**Comment by eugenemiretsky** [comment]
@alexflav23 when can wasApplied be false? My understanding is that is applied only to conditional update. 
I was the consumers of DatabaseProvider to not have to worry about the internal of Cassandra (Resultset), also, ideally, I don't want them to have to check both if the future failed, and the result of the future (in case it is Future[Boolean]). I suppose the only time it would make sense is for conditional updates, where the Future failing means a connection problem, while the Future value being false means that there was a logical problem that can be handled.

**Comment by alexflav23** [comment]
Hi @eugenemiretsky `wasApplied` can indeed be misleading, so this is usually something people do via consensus. It's up to you to decide when you want to drop Cassandra specificity.

I recommend maping to `Unit` if you think the `ResultSet` can cause issues and confusion further downstream, however duly note how `map` works on a Scala Future, you do pay a small cost for that `map` method call every time.
