### ISSUE TITLE
Update link in batches.md

### ISSUE THREAD

**Issue by esenatak** [outworkers/phantom#775]
- Currently, link to IterateeBigTest.scala is broken

**Comment by alexflav23** [comment]
Apologies for that, you are correct, link is out of date. New one [here](https://github.com/outworkers/phantom/blob/develop/phantom-streams/src/test/scala/com/outworkers/phantom/streams/suites/iteratee/IterateeBigReadPerformanceTest.scala). We also fixed this in the docs, it will be rolled out shortly.
