### ISSUE TITLE
adding condition to query doesn't work

### ISSUE THREAD

**Issue by git4sun** [outworkers/phantom#786]
I am trying to add query conditions one by one according to input. Here's what I did:

    val condSeq: Seq[(String,String)] = ...
    val query = condSeq.head match {
        case ("ad", c:String) => select.where(_.ad eqs c)
        case ("status", c:String) => select.where(_.status eqs c)
      }
    condSeq.drop(1).foreach { r =>
       r._1 match {
          case "adType" => query.and(_.adType eqs r._2)
          case "status" => query.and(_.status eqs r._2)
       }
    query.fetch

However, only one condition (the first one) is working. It looks like `query.and()` part doesn't have an effect on the query. I output the CQL raw queries, and noticed query.qb output the same result before and after `query.and(...)` is called. Is there something I did wrong? Or is it not preferred to use the query this way?

**Comment by tomerf** [comment]
The query object is immutable, and() creates a copy of the query object.
You need to change your code to the following:
```
val condSeq: Seq[(String,String)] = ...
val query = condSeq.head match {
    case ("ad", c:String) => select.where(_.ad eqs c)
    case ("status", c:String) => select.where(_.status eqs c)
  }
val newQuery = condSeq.drop(1).foldLeft(query) { (query, r) =>
   r._1 match {
      case "adType" => query.and(_.adType eqs r._2)
      case "status" => query.and(_.status eqs r._2)
   }
}
newQuery.fetch
```

**Comment by git4sun** [comment]
I see. Thanks.
