### ISSUE TITLE
Can't query datetime range on primary key

### ISSUE THREAD

**Issue by tomerf** [outworkers/phantom#787]
Hello, I'm trying to create a table with a date time column and query for data in a certain time range, but I get a compilation error when the date time column is defined as a primary key.
```
object id1 extends StringColumn with PartitionKey
object time extends DateTimeColumn with PrimaryKey with ClusteringOrder with Descending
object id2 extends UUIDColumn with PrimaryKey with ClusteringOrder with Ascending
...
other columns
...
```
and then do the following query:
```
select.where(_.id1 eqs value1)
        .and(_.time isGte startTime)
        .and(_.time isLt endTime)
        .iterator()
```
However I get a compilation error:
```
[error] /Users/tomer/project/common/src/main/scala/com/project/common/bigtable/Table.scala:82: value isGte is not a member of object x$2.time
[error]         .and(_.time isGte startTime)
```
If I define the time column without a primary key and order this code compiles without error:
```
object time extends DateTimeColumn
```
I'm not sure if I defined something wrong or there's a bug when the column is a primary key with cluster order.
Any help would be appriciated.

**Comment by alexflav23** [comment]
Hi @tomerf Try using this:

```scala
object id1 extends StringColumn with PartitionKey
object time extends DateTimeColumn with ClusteringOrder with Descending
object id2 extends UUIDColumn with ClusteringOrder with Ascending
```

There's no need to have both `ClusteringOrder` and `PrimaryKey` in there, and I think that's what's causing problems.

**Comment by tomerf** [comment]
Hi @alexflav23, I tried to remove it and still get the same error.

**Comment by alexflav23** [comment]
Hi @tomerf could you put the whole schema here? I think you are using the wrong operators, `isGte` operators are for conditional update clauses, not for where clauses, so I think you need to simply use: 

```scala
select.where(_.id1 eqs value1)
        .and(_.time gte startTime)
        .and(_.time lt endTime)
        .iterator()
```

**Comment by tomerf** [comment]
Yes that was the problem.
Thanks!
