### ISSUE TITLE
PrepareStatement issues with PhantomDSL for SELECT and UPDATE

### ISSUE THREAD

**Issue by Rajitha15** [outworkers/phantom#789]
Hi Alexandru,

We have few questions related to “prepare” feature in Phantom DSL.

Is there any detailed document and set of examples explaining “prepare” for all CRUD operations?
We referred to the examples on your GitHub [https://github.com/outworkers/phantom/] and the examples are limited and do not address all the cases. We are facing following issues

2.  We tried using “prepare” for select and update and faced below issues:
A. For select, we tried filtering based on multiple non-primary key string columns using “is” [Refer to QUERY1 & ERROR1 in the attachment] and “eqs” [Refer to QUERY2 & ERROR2 in the attachment] methods and the errors are thrown as listed in the attachment

B. For update, we tried to update based on the partition key and modifying values for a String Column [Refer to QUERY3 & ERROR3 in the attachment] and the errors are thrown as listed in the attachment.

3.  Version Info: Scala: “2.12.1”, PhantomDSL: “2.3.0” and “2.13.4"

4. It would be great if we can have one-on-one discussion and get more understanding on the “prepare” feature in PhantomDSL.

We look forward for your timely response.

Query1:

  def lookup(id1: String, id2: String): Future[Option[table1]] = {

    val query2 = select
      .where(_.id1.is(?))
      .and(_.id2.is(?))
      .consistencyLevel_=(ConsistencyLevel.LOCAL_QUORUM)
      .allowFiltering()
      .prepare

  query2.bind(id1, id2).one()
  }

ERROR1: Error:(22, 25) type mismatch;
 found   : com.outworkers.phantom.dsl.?.type
 required: String
      .where(_.id1.is(?))

Query2:

  def lookupOrgByOrgAndSite(orgId: String, siteId: String): Future[Option[table1]] = {

    val query2 = select
      .where(_.id1.eqs(?))
      .and(_.id2.eqs(?))
      .consistencyLevel_=(ConsistencyLevel.LOCAL_QUORUM)
      .allowFiltering()
      .prepare

  query2.bind(id1, id2).one()
  }

ERROR2: Error:(22, 22) value eqs is not a member of object x$2.id1
      .where(_.id1.eqs(?))

Query3:

def dismissAlert(alertId: String, orgId: String): Future[ResultSet] = {
   val query = update
     .where(_.id eqs ?)
     .modify(_.name setTo ?)
     .and(_.updated setTo ?)
     .ifExists
     .consistencyLevel_=(ConsistencyLevel.LOCAL_QUORUM)
     .prepare
     query.bind(id, orgId, "name", Calendar.getInstance().toInstant.toString).future()
 }

ERROR3: Error:(53, 8) could not find implicit value for parameter rev: shapeless.ops.hlist.Reverse.Aux[this.Out,Nothing]
      .prepare

      Error:(53, 8) not enough arguments for method prepare: (implicit session: com.datastax.driver.core.Session, implicit keySpace: com.outworkers.phantom.connectors.KeySpace, implicit ev: shapeless.=:!=[this.Out,shapeless.HNil], implicit rev: shapeless.ops.hlist.Reverse.Aux[this.Out,Nothing], implicit rev2: shapeless.ops.hlist.Reverse.Aux[this.Out,Nothing], implicit prepend: shapeless.ops.hlist.Prepend[Nothing,Nothing])com.outworkers.phantom.builder.query.prepared.PreparedBlock[prepend.Out].
Unspecified value parameters rev, rev2, prepend.
      .prepare

Thanks
Rajitha

**Comment by alexflav23** [comment]
Hi @Rajitha15,

Query 1: You are misunderstanding what `is` does, it's not a way to prepare statements, it's a way to check that a condition is met before executing an update, so it only works with conditional update queries, or Compare and Set clauses as they are called in Cassandra.

Query 2:

```scala
val query2 = select
  .where(_.orgId.eqs(?))
  .and(_.siteId.eqs(?))
  .consistencyLevel_=(ConsistencyLevel.LOCAL_QUORUM)
  .allowFiltering()
  .prepare
```
I'd imagine you are missing an index of any kind on `orgId`. Otherwise please post the schema here and I am very happy to take a look.

Query 3:

In Phantom prepared queries are fully typesafe and use HLists for enable that functionality. HLists or Heterogenous lists can store elements of multiple types, but you need to provide them *in the same order* you specified them in the original query.

```scala
def dismissAlert(alertId: String, orgId: String): Future[ResultSet] = {
  val query = update
    .where(_.alertid eqs ?)
    // Here you are specifying severity
    .modify(_.severity setTo ?)
    .and(_.updated setTo ?)
    .ifExists
    .consistencyLevel=(ConsistencyLevel.LOCAL_QUORUM)
    .prepare

   // Here your second argument is orgId instead of severity.
   // And you are binding 4 parameters, but you only specified 3 question marks above.
   query.bind(
     alertId,
     orgId,
     "Clear",
     Calendar.getInstance().toInstant.toString
    ).future()
}
```

You should also not willingly re-bind queries every time like you are doing above. Instead, use the cached `prepareAsync` API.

```scala

val query = update
    .where(_.alertid eqs ?)
    .and(_.orgId eqs ?)
    // Here you are specifying severity
    .modify(_.severity setTo ?)
    .and(_.updated setTo ?)
    .ifExists
    .consistencyLevel=(ConsistencyLevel.LOCAL_QUORUM)
    .prepareAsync

def dismissAlert(alertId: String, orgId: String): Future[ResultSet] = {
   query.flatMap(_.bind(alertId, orgId, "clear"))   
}
```
