### ISSUE TITLE
Configure DEFAULT_STARTUP_TIMEOUT through Phantom CassandraConnection

### ISSUE THREAD

**Issue by rohinisb** [outworkers/phantom#790]
Is there a way to set the DEFAULT_STARTUP_TIMEOUT used by EmbeddedCassandraServerHelper through CassandraConnection by passing a parameter or something? This is currently set to 10000 and I want to be able to increase it since it is too less for our ci machines and it almost always times out. Thanks.

**Comment by alexflav23** [comment]
You can already do this, in your `build.sbt`:

```scala
phantomCassandraTimeout in Test := Some(10000) // this is a number in milliseconds.

```

**Comment by rohinisb** [comment]
Hi @alexflav23 ,

I have added 
`phantomCassandraTimeout in Test := Some(20000) ` 
in my build.sbt and for some reason it is not being overridden. I get the following error

`ERROR org.cassandraunit.utils.EmbeddedCassandraServerHelper - Cassandra daemon did not start after 10000 ms. Consider increasing the timeout`

Complete error 
`11:45:27 java.lang.AssertionError: Cassandra daemon did not start within timeout
11:45:27 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:136)
11:45:27 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:91)
11:45:27 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:70)
11:45:27 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:62)
11:45:27 	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:58)
11:45:27 	at com.outworkers.phantom.sbt.EmbeddedCassandra$$anonfun$start$1.apply$mcV$sp(SbtPlugin.scala:136)
11:45:27 	at com.outworkers.phantom.sbt.EmbeddedCassandra$$anonfun$start$1.apply(SbtPlugin.scala:104)
11:45:27 	at com.outworkers.phantom.sbt.EmbeddedCassandra$$anonfun$start$1.apply(SbtPlugin.scala:104)
11:45:27 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
11:45:27 	at scala.concurrent.package$.blocking(package.scala:50)
11:45:27 	at com.outworkers.phantom.sbt.EmbeddedCassandra$.start(SbtPlugin.scala:104)
11:45:27 	at com.outworkers.phantom.sbt.PhantomSbtPlugin$$anonfun$projectSettings$5.apply(SbtPlugin.scala:79)
11:45:27 	at com.outworkers.phantom.sbt.PhantomSbtPlugin$$anonfun$projectSettings$5.apply(SbtPlugin.scala:79)
11:45:27 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
11:45:27 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
11:45:27 	at sbt.std.Transform$$anon$4.work(System.scala:63)
11:45:27 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
11:45:27 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
11:45:27 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
11:45:27 	at sbt.Execute.work(Execute.scala:237)
11:45:27 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
11:45:27 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
11:45:27 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
11:45:27 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
11:45:27 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:45:27 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11:45:27 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:45:27 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:45:27 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:45:27 	at java.lang.Thread.run(Thread.java:748)
11:45:27 [error] (dashboard/*:phantomStartEmbeddedCassandra) java.lang.AssertionError: Cassandra daemon did not start within timeout`

**Comment by alexflav23** [comment]
Hi @rohinisb The interesting thing is that the default is 20 seconds. Are you sure there is nothing interfering with your setting?

**Comment by rohinisb** [comment]
Hi @alexflav23, let me debug this issue more and get back to you. In the meantime, I will reopen if I find an issue. Thank you.

**Comment by rohinisb** [comment]
Hi @alexflav23, so as I see from my project we have version 2.1.9.2 of CassandraUnit and I can see that the value is `public static final long DEFAULT_STARTUP_TIMEOUT = 10000;` 
We use version 2.14.5 of the phantom-sbt plugin.

**Comment by rohinisb** [comment]
Hi @alexflav23 any update on this?
