### ISSUE TITLE
Missing Bijection between `Option[FullName]` and `Option[String]`

### ISSUE THREAD

**Issue by fuzzy-id** [outworkers/phantom#792]
You can find a test scenario at https://github.com/fuzzy-id/cassandra-tests

I guess it boils down to having some `case class`:
``` scala
case class SimpleFoo( name: Option[String] )
```
Now, doing  `gen[SimpleFoo]` results to an error at compile-time:
```
[error] cassandra-problems/src/test/scala/FooTests.scala:28:16: type mismatch;
[error]  found   : Option[com.outworkers.util.domain.GenerationDomain.FullName]
[error]     (which expands to)  Option[com.outworkers.util.domain.Definitions.FullName]
[error]  required: Option[String]
[error]     val f = gen[SimpleFoo]
[error]                ^
[error] one error found
```

**Comment by alexflav23** [comment]
Hi @fuzzy-id, this is not related to phantom, this is an issue for outworkers/util. Would you mind moving the issue over there, and we can look at it separately?

**Comment by fuzzy-id** [comment]
So I opened https://github.com/outworkers/util/issues/64 but nothing's happening over there. :(
