### ISSUE TITLE
Support for Speculative query execution

### ISSUE THREAD

**Issue by stephenpauldasari** [outworkers/phantom#793]
Hi Flavian

Can we incorporate Datastax's Speculative Query Execution via Phantom DSL driver?
http://docs.datastax.com/en/developer/java-driver/3.1/manual/speculative_execution/

**Comment by alexflav23** [comment]
@stephenpauldasari Phantom supports all options from the underlying driver. One example below.

```
val connector = ContactPoint.local
    .noHeartbeat()
    .withClusterBuilder(
      _.withReconnectionPolicy(new ConstantReconnectionPolicy(50))
        .withSpeculativeExecutionPolicy(new ConstantSpeculativeExecutionPolicy(500, 2))
    )
    .keySpace("phantom_example")
```
