### ISSUE TITLE
Map primitives with custom types for (Key/Value) don't get generated automatically

### ISSUE THREAD

**Issue by Vrolijkx** [outworkers/phantom#798]
When you try to use a map column in a table but the key or value is also a custom type. Then the PrimitiveMacro won't generate the correct Primitive. This can be worked around like in the snippet below. But this should be fixed in the PrimitiveMacro. 

```
trait CustomPrimitives {
    implicit val availabilityPrimitive: Primitive[Availability] = Primitive.derive[Availability, String](_.toString)(Availability.apply)
    implicit val durationPrimitive: Primitive[Duration] = Primitive.derive[Duration, String](_.toString)(Duration.parse)

    //This one is explicitly needed because the output of macro generating the default map primitive
    //Fails to generate it automatically because it does not have the implicit scope from above.
    implicit val availabilityTimingMapPrimitive: Primitive[Map[Availability, Duration]] = Primitives.map(availabilityPrimitive, durationPrimitive)

}
```

While debugging the PrimitiveMacro I noticed that the context has no implicit scope variable which I think is the cause of the problem.
com.outworkers.phantom.builder.primitives.PrimitiveMacro.scala:300

But this is only a guess I am not that familiar with macros.
  
**Needed Code:**
```
sealed trait Availability

object Availability {
  case object Available extends Availability
  case object Pending extends Availability
  case object UnAvailable extends Availability

  def apply(name: String): Availability = fromString(name)

  def fromString(name: String): Availability = name match {
    case "Available" => Available
    case "Pending" => Pending
    case "UnAvailable" => UnAvailable
    case other => throw new IllegalArgumentException(s"$other is not a valid type of Availability")
  }

}

case class MyEntity(key: String, timestamp: DateTime, durationByState: Map[Availability, Duration])

abstract class MyTable extends Table[MyTable, MyEntity] with RootConnector with CustomPrimitives {

  object key extends StringColumn with PartitionKey
  object timestamp extends DateTimeColumn
  object durationByState extends MapColumn[Availability, Duration]
}

class MyDb(override val connector: CassandraConnection) extends Database[MyDb](connector) {

  object myTable extends MyTable with Connector

}
```

**Comment by alexflav23** [comment]
Hi @Vrolijkx Thank you for providing this information, it may be entirely possible you are right. If you can please also provide a DSL schema of the case class and table, so we have something to copy paste and replicate the problem.

Remove any sensitive information, we only care about types. Thank you for taking the time to report this problem. Also, what do you mean when you say the primitive is incorrect, that the implicit is not found and the code doesn't compile or that it has runtime issues?

Regards.

**Comment by Vrolijkx** [comment]
Hi @alexflav23, I updated the description with the extra needed information. When you remove map Primitive you get next compile error:
```
Cannot find primitive implementation for trait Availability
[error]   object durationByState extends MapColumn[Availability, Duration]
[error]                                  ^
[error] one error found
```

Which is confusing because you added that one right above.

**Comment by alexflav23** [comment]
@Vrolijkx So what you really want here is not a map primitive really, it's a co-product primitive. If we implemented a native one for Coproduct, would you be happy to use the Shapeless API?

`type Availability = Available +: Pending +: Unavailable +: CNil`

At that point I think we can do something about making a generic co-product primitive.

**Comment by Vrolijkx** [comment]
@alexflav23 How do you mean coproduct.
I just want to be able to create a map of a custom key object(sealed trait) and a custom value object(JodaTime duration).
For me, the actual type of the key and the value that will be used for the map should not matter.
Phantom should be able to generate the Primitive needed for this map if:
- The primitive for the key can be found in implicit scope.
- The primitive for the value can be found in implicit scope.

And both are defined in my scenario. But for some reason, Phantom can't generate this map primitive and it must be manually defined.

I don't think a Coproduct will solve this problem.

**Comment by alexflav23** [comment]
@Vrolijkx I see what you mean, sorry I think I mis-understood the original requirement, I see what you need now, going to follow up later today and get a fix done for you.

**Comment by alexflav23** [comment]
@Vrolijkx We've found the problem and the bug here, it's not that the implicit is not visible, it's that for some bizarre reason the pass through implicit context is dropped for local scope, e.g whatever implicits are visible through inheritance end up being masked/dropped or ignored, because the resulting `Tree` is evaluated in a completely different scope. When `Primitives.map` finally ends up being called, it's managed to lose track of inherited implicit.

In short, higher scope implicits like `import CustomPrimitives._` or companion object definitions are available to `c.inferImplicitView` and to the `PrimitiveMacro`, those seem to work as expected.

* Working scenario*:

```scala

object CustomPrimitives {

  implicit val availabilityPrimitive: Primitive[Availability] = {
    Primitive.derive[Availability, String](_.toString)(Availability.apply)
  }
  implicit val durationPrimitive: Primitive[Duration] = {
    Primitive.derive[Duration, String](_.toString)(Duration.parse)
  }
}

case class MyEntity(
  key: String,
  timestamp: DateTime,
  durationByState: Map[Availability, Duration]
)

import CustomPrimitives._

abstract class MapTableBug extends Table[MapTableBug, MyEntity] with CustomPrimitives {
  object key extends StringColumn with PartitionKey
  object timestamp extends DateTimeColumn
  object durationByState extends MapColumn[Availability, Duration]
}

```

This is a problem of the macro API itself, not one specific to phantom, but there has to be a fix and we are working with developers on the macro API teams to figure out what the right API methods are to access implicits from inherited scope.

In the meantime, as a short-term fix, use the object import.

**Comment by Vrolijkx** [comment]
@alexflav23 Thanks for the workaround and good explanation.

**Comment by alexflav23** [comment]
Hi @Vrolijkx Yes, I've followed up with the macro team, pretty much all I am hearing is that no bugs will be fixed and that the full focus is on the long term scalacenter/macros replacement, so I imagine this is here to stay until the underlying macro lib completely changes.

Apologies for the inconvenience, trying to think of more workarounds but I'm not sure there's much we can do.

**Comment by kolemannix** [comment]
@alexflav23 I just ran into this as well.

I think it would be worth adding a small note to the primitives README explaining this, as I think most people's default plan for providing custom `Primitive[_]` instances will be to mix in a trait instead of an import.

Thanks for your awesome work on phantom!

**Comment by alexflav23** [comment]
Hi @Vrolijkx @kolemannix fixed in https://github.com/outworkers/phantom/pull/887. It will be available in the next release.
