### ISSUE TITLE
Table auto-creation logic appears to be broken in 2.20

### ISSUE THREAD

**Issue by jalaziz** [outworkers/phantom#805]
With the introduction of https://github.com/outworkers/phantom/commit/3de2569986335898f1f152e26d1b7e36f5b8b44f#diff-5d9200ac927eda8a988de85095358f1eR65, the instructions for customizing schema generations no longer work. The instructions [here](https://github.com/outworkers/phantom/blob/develop/readme/src/main/tut/basics/database.md#automated-schema-generation-using-database) recommend overriding a tables `autocreate` method. However, that method is no longer called by the database's `create` methods.

**Comment by alexflav23** [comment]
@jalaziz Entirely possible, we've just released something to fix secondary indexes and it may be now creating a problem. Going to follow up on this immediately as it could become a big issue for a lot of users.

Thank you for reporting this.

**Comment by alexflav23** [comment]
@jalaziz Coming up with a release for this during the weekend, watch out for a 2.21.0 on Monday.

**Comment by alexflav23** [comment]
Hi @jalaziz This is fixed now pending release, forgot to close it.
