### ISSUE TITLE
Creating Phantom DSL Connection just like DataStax Cluster.Builder

### ISSUE THREAD

**Issue by abhsrivastava** [outworkers/phantom#808]
I am migrating code written against DataStax Cluster.Builder to Phantom. I can create a connection in Phantom easily, but I am not able to create a connection with all the properties specified below

` val cluster = Cluster.builder()
     .withCompression(ProtocolOptions.Compression.LZ4)
     .addContactPoints(List("a", "b").asJava)
     .withCredentials("foo", "bar")
     .withPort(1111)
     .withProtocolVersion(ProtocolVersion.V4)
     .withPoolingOptions(new PoolingOptions()
        .setConnectionsPerHost(HostDistance.LOCAL, 1, 12)
        .setConnectionsPerHost(HostDistance.REMOTE, 1, 12)
        .setMaxRequestsPerConnection(HostDistance.LOCAL, 1028)
        .setMaxRequestsPerConnection(HostDistance.REMOTE, 1028)
     )
     .withQueryOptions(new QueryOptions().setConsistencyLevel(ConsistencyLevel.QUORUM))`

Can you please tell me how can I create. connection exactly like the one above

I also posted this question here https://stackoverflow.com/questions/48600984/how-to-build-a-phantom-cassandraconnection-from-datastax-clusterbuilder. I am logging it as an issue because I didn't get any response on SO.

**Comment by alexflav23** [comment]
Hi @abhsrivastava,

Simply use `_.withClusterBuilder`. An example is found [here](https://github.com/outworkers/phantom/blob/develop/docs/querying/indexes/sasi.md#using-sasi-support-in-phantom), check the `Connector` definition.
