### ISSUE TITLE
Different behavior between ListColumn and Col[List]

### ISSUE THREAD

**Issue by jalaziz** [outworkers/phantom#814]
The docs suggest that now `ListColumn[String]` and `Col[List[String]]` are equivalent:  https://github.com/outworkers/phantom/blob/d8afd1b34ebe514673e346041fb30223caadf469/readme/src/main/tut/basics/primitives.md.

However, I'm finding that `Col[Set[String]]` results in an NPE if a row is read before the column is set. With `SetColumn[String]`, we don't get the NPE.

In [CollectionColumn.scala](https://github.com/outworkers/phantom/blob/1dd89b99508c3ef60adfa7e168df2ddbc198859f/phantom-dsl/src/main/scala/com/outworkers/phantom/column/CollectionColumn.scala#L35) it seems that a collection column will return an empty collection if the column isn't returned.

The `PrimitiveColumn` version has no such semantics and does not return an empty collection if the row is not set.

This may be expected, but it's definitely a gotcha when upgrading.

**Comment by alexflav23** [comment]
Hi @jalaziz, that's not expected I guess. The `PrimitiveColumn` is not involved in deciding what happens with `Col[List[String]]`, the same macro will wire in the same primitive, so I am more than a little surprised you are getting an exception.

This is the code block below:

```scala
    override def deserialize(bytes: ByteBuffer, version: ProtocolVersion): M[RR] = {
      val empty = cbf().result()
      if (bytes == Primitive.nullValue || bytes.remaining() == 0) {
         empty
      } else {
        ....
      }
```

Please help me with some more info to reproduce this!

**Comment by jalaziz** [comment]
@alexflav23 I've pushed an example that demonstrates the issue: https://github.com/jalaziz/phantom/commit/dfc1f941f59bb1e386498506a51426d2ccdd8e13

If I convert the set and map columns back to `SetColumn` and `MapColumn` the tests pass. If I use the `Col[Set]` version, it fails on an NPE.

**Comment by alexflav23** [comment]
Fixed in https://github.com/outworkers/phantom/pull/896
