### ISSUE TITLE
Confusion on usage of phantom

### ISSUE THREAD

**Issue by akumarb2010** [outworkers/phantom#827]
Hi,

I am trying use phantom-dsl to connect to cassandra and I am using below maven dependency for it.

```
  <dependency>
            <groupId>com.outworkers</groupId>
            <artifactId>phantom-dsl_2.11</artifactId>
            <version>2.24.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

My code is not compiling and seems there are multiple versions of examples, so not sure on which on is the latest to follow. Is there any current workable example? 

Seems below all are for phantom examples, but seems they are different. 
http://outworkers.com/blog/post/a-series-on-phantom-part-1-getting-started-with-phantom
https://github.com/thiagoandrade6/cassandra-phantom
http://outworkers.com/blog/post/phantom-tips-3-understanding-phantom-connectors

https://github.com/tanwanirahul/phantom-1 approach is compiling but failing due to index columns.

**Comment by alexflav23** [comment]
Hi @akumarb2010 Apologies for the late reply, we are happy to help but going to need more specific questions or compilation errors if possible. Could you help us with that?

**Comment by alexflav23** [comment]
Hi @akumarb2010 I'm going to close this issue for now, as I've not heard back from you in a while. Please re-open this issue with more details if necessary.
