### ISSUE TITLE
Aggregation functions do not allow select mutliple fields

### ISSUE THREAD

**Issue by mariuszeniro** [outworkers/phantom#831]
Hi,
According to the [documentation](https://github.com/outworkers/phantom/blob/v2.24.3/docs/querying/select.md) we can query for aggregates like
`select.function(t => sum(t.long))` but what about multi aggregations e.g CQL `select sum(clicks), sum(impressions) where id = 1 from my_table`? It is not possible to build sth. like `select.function(t => sum(t.clicks),t => sum(t.impressions))`
Any suggestions ?

**Comment by alexflav23** [comment]
Hi @mariuszeniro I don't think this is possible right now, but it's definitely something we can support, let me follow up and see how it could be done.

**Comment by Prosenjitpaul121** [comment]
Please tell me details.Who are you?Not understand what you tell me.

**Comment by alexflav23** [comment]
Hi @mariuszeniro This is being resolved in #833, follow that branch for updates on this. It's pretty tricky type sorcery that needs to happen magically behind the scenes, but we are finding the right way to make it work.

One of the cool things calling `aggregate` gave was an automating correct return type, and we are just trying to preserve the same return type with the new aggregate function, that operators from an `HList` instead.

**Comment by alexflav23** [comment]
@mariuszeniro Fixed in 2.24.10, now on maven central.

You need to manually call `multiAggregate` when you have more than one aggregate selected though.
