### ISSUE TITLE
Question on using timestamp with insert

### ISSUE THREAD

**Issue by provegard** [outworkers/phantom#832]
`QueryBuilder.timestamp` takes a Long that is "The milliseconds since EPOCH long value of a timestamp."

However, CQL appears to take a [microseconds value](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlInsert.html).

I enabled trace logging to see actual queries, and it doesn't seem as if phantom converts the timestamp value. Am I missing something? My end goal is to be able to use a timestamp with higher precision than millisecond precision.

**Comment by alexflav23** [comment]
Hi @provegard That must be an error either in the docs or implementation logic. We can definitely re-enforce the unit with better method names, and method types of course. I'm going to follow up on this and come back with a fix.

**Comment by alexflav23** [comment]
hi @provegard With apologies for the delay, this has now been merged in.
