### ISSUE TITLE
How does the store method work?

### ISSUE THREAD

**Issue by git4sun** [outworkers/phantom#841]
I upgraded to 2.14. I noticed there is a store() method taking the case class and insert each field. It seems very compelling so I tried it. But it gives me errors:
`Not enough arguments for method store`

Instead, if I use the old insert.value() and list all the fields, it works just fine. The link to the store method document returns 404. Is there any update on that?

**Comment by alexflav23** [comment]
Hi @git4sun: https://github.com/outworkers/phantom/blob/develop/docs/basics/tables.md#extractors-and-how-they-get-generated

Where are you seeing the broken link?

**Comment by alexflav23** [comment]
@git4sun The link above should work, I'm going to close this ticket for now, but pleasa re-open if necessary. We are working on a new menu for the documentation which should be available by the end of the week, that should fix some of the problems and missing links.

**Comment by git4sun** [comment]
https://github.com/outworkers/phantom/blob/develop/docs/migrate.md
The store method page link on the migration guide page is broken.

**Comment by git4sun** [comment]
btw, did you see my question on stackoverflow? any idea why its not working? I am currently using datastax driver directly connect to the cassandra db. It works.
