### ISSUE TITLE
Documentation page (or link) broken?

### ISSUE THREAD

**Issue by dgrald** [outworkers/phantom#844]
I receive a 404 at http://outworkers.github.io/phantom/. Is there another way to view the documentation? Or does the link need to be updated?

**Comment by alexflav23** [comment]
@dgrald This should be updated, apologies for the oversight. Try (this link) [https://github.com/outworkers/phantom/tree/docs/]

**Comment by dgrald** [comment]
Thanks, @alexflav23 . Yeah, the .md files are usable, but it's hard to navigate between files when they're not linked together.

If it's alright with you, I'll leave this issue open until the documentation page is fixed.

**Comment by alexflav23** [comment]
@dgrald Fixed today.
