### ISSUE TITLE
Phantom 2.24.10  cannot apply aggregation functions for optional numeric columns.

### ISSUE THREAD

**Issue by livius-ungureanu** [outworkers/phantom#865]
I've got a table with the following column:
```
object siz extends OptionalLongColumn
```
Then I have an aggregate statement that refers it:
```
myTable.select.function(t => sum(t.siz) ~ count()).where(_.id eqs ?)
```
and I get the following build error:
```
could not find implicit value for parameter numeric: Numeric[Option[Long]]
```

So it's clear that this `implicit numeric: Numeric[T]`  is wanted to prevent the user from summing up Strings and Blobs etc...
But my column is OptionalLongColumn which on Cassandra side translates to a Long column that can accept null values. The Cassandra's sum is happy to work with nulls but on the phantom side the user is not allowed  sum with OptionalLongColumn.

Net:  The phantom doc says:
"This explores all the various SELECT functionality in CQL as described in the official reference here. Phantom aims to provide a 100% mapping with all the latest CQL features, but if you find anything that you need missing, please help us by reporting it through GitHub issues."

Since Cassandra accepts aggregation functions against numeric columns with nulls, the same way phantom should allow aggregation functions against  optional numeric columns.

**Comment by alexflav23** [comment]
Hi @livius-ungureanu,

You can easily fix this locally.

```
implicit def optionNumeric[T](implicit ev: Numeric[T]): Numeric[Option[T]] = new Numeric[Option[T]] {
 ....
}
```

I'll try and add it to the framework, need to consider any downsides strongly before we do, but you can move way faster than waiting for a release just by adding that implicit.

**Comment by alexflav23** [comment]
@livius-ungureanu You need to double check whatever is below to make sure all operations make sense. E.g how does `Option[Int]` compare to `Option[Int]`? In the true Cassandra sense, you can flatten the `None` to a `0`, but there's a need to account for all edge cases.

```scala
implicit def optionNumeric[T](implicit ev: Numeric[T]): Numeric[Option[T]] = new Numeric[Option[T]] {
    override def plus(x: Option[T], y: Option[T]): Option[T] = {
      for (x1 <- x; y1 <- y) yield ev.plus(x1, y1)
    }

    override def minus(x: Option[T], y: Option[T]): Option[T] = {
      for (x1 <- x; y1 <- y) yield ev.minus(x1, y1)
    }

    override def times(x: Option[T], y: Option[T]): Option[T] = {
      for (x1 <- x; y1 <- y) yield ev.times(x1, y1)
    }

    override def negate(x: Option[T]): Option[T] = {
      x.map(ev.negate)
    }

    override def fromInt(x: Int): Option[T] = {
      Option(ev.fromInt(x))
    }

    override def toInt(x: Option[T]): Int = {
      x.fold(0)(ev.toInt)
    }

    override def toLong(x: Option[T]): Long = {
      x.fold(0L)(ev.toLong)
    }

    override def toFloat(x: Option[T]): Float = {
      x.fold(0F)(ev.toFloat)
    }

    override def toDouble(x: Option[T]): Double = {
      x.fold(0D)(ev.toDouble)
    }

    override def compare(x: Option[T], y: Option[T]): Int = {
      { for (x1 <- x; y1 <- y) yield ev.compare(x1, y1) } getOrElse 0
    }
  }
```

**Comment by livius-ungureanu** [comment]
since the `implicit Numeric[T]` is not actually used in   and  in my case  I am dealing only with  Option[Long] columns that needs aggregation,  I only added:
```
trait NumericOptionLong extends Numeric[Option[Long]] {
  def plus(x: Option[Long], y: Option[Long]): Option[Long] = ???
  def minus(x: Option[Long], y: Option[Long]): Option[Long] = ???
  def times(x: Option[Long], y: Option[Long]): Option[Long] = ???
  def negate(x: Option[Long]): Option[Long] = ???
  def fromInt(x: Int): Option[Long] = ???
  def toInt(x: Option[Long]): Int = ???
  def toLong(x: Option[Long]): Long = ???
  def toFloat(x: Option[Long]): Float = ???
  def toDouble(x: Option[Long]): Double = ???
  def compare(x: Option[Long], y: Option[Long]): Int = ???
}

object NumericExt {
  implicit object OptionLongIsIntegral extends NumericOptionLong
}
```

in order to satisfy the compiler.

This is an workaround in my case but phantom should offer something like  you have mentioned above.

**Comment by alexflav23** [comment]
Hi @livius-ungureanu,

It shouldn't because the math is only valid if `null` defaults to `0`, which is valid in Cassandra, but can easily mess up other people's code. We're going to look at adding a new typeclass specific to phantom, instead of `scala.math.Numeric` which would easily interfere with other people's code by allowing operations that don't make mathematical sense.

**Comment by alexflav23** [comment]
Hi @livius-ungureanu, resolved in the latest release.
