### ISSUE TITLE
Count aggregation function is also wanted to accept a column name.

### ISSUE THREAD

**Issue by livius-ungureanu** [outworkers/phantom#868]
Hi  @alexflav23 

Still related to https://github.com/outworkers/phantom/issues/866:

I've checked out 2.28.0
I've seen that `SelectQuery#count` was updated to accept column name which is fine.

But in my case I'd need the `count` aggregation to also be updated to make it possible:
```
myTable.select.function(t => count(t.size) ~ sum(t.siz)).where(_.id eqs ?)
```
I want to combine both count and sum in a single C* call

**Comment by alexflav23** [comment]
Hi @livius-ungureanu fixed in 2.29.0
