### ISSUE TITLE
broken links on home readme

### ISSUE THREAD

**Issue by mtekp** [outworkers/phantom#870]
"[A series on Cassandra ](http://outworkers.com/blog/post/a-series-on-cassandra-part-1-getting-rid-of-the-sql-mentality)" links are broken

**Comment by egoarka** [comment]
workaround http://web.archive.org/
P.S. just waiting for full recovery of blog

**Comment by alexflav23** [comment]
Hi @egoarka @mtekp We are just in the process of moving it to a new platform, it should be completed within the next 2 weeks. Thank you for making us aware of it, and apologies for the disruption.

**Comment by alexflav23** [comment]
Hi @egoarka @mtekp Links now updated, we are using medium.com as a blogging platform instead of the small proprietary system we had.

**Comment by egoarka** [comment]
appreciate it, thanks!
