### ISSUE TITLE
 Set column helpers(e.g  add, addAll, remove, removeAll) in the UPDATE dsl statement are not available  in prepared  mode.

### ISSUE THREAD

**Issue by livius-ungureanu** [outworkers/phantom#879]
Phantom doc says:
"Phantom aims to provide a 100% mapping with all the latest CQL features, but if you find anything that you need missing, please help us by reporting it through GitHub issues."

Given the following table:
```
class Recipes extends Table[Recipes, Recipe] {

  object url extends StringColumn with PartitionKey

  object description extends OptionalStringColumn

  object ingredients extends SetColumn[String]
}
```

It seems phantom does not support prepared updates where set columns are modified with add, addAll, remove, removeAll helpers..

As an example this is not supported:
```
val query_add = database.recipes.update
      .where(_.url eqs ?)
      .modify(_.ingredients addAll ?)  // this is not supported
      .prepare()

 query.bind(Set('ingr1', 'ingr2'), recipe.url)
```

The underlying cql is perfectly valid though:
```
cqlsh> UPDATE  recipes
  SET ingredients = ingredients + {'ingr1', 'ingr2'} WHERE id = url ...;
```

Thank you in advance.

**Comment by alexflav23** [comment]
@livius-ungureanu Fixed in 2.34.0 coming up on Central.
