### ISSUE TITLE
Special DELETE statement not available in prepared mode

### ISSUE THREAD

**Issue by livius-ungureanu** [outworkers/phantom#880]
Phantom doc says:
"Phantom aims to provide a 100% mapping with all the latest CQL features, but if you find anything that you need missing, please help us by reporting it through GitHub issues."

Given the following table:
```
class Recipes extends Table[Recipes, Recipe] {

  object url extends StringColumn with PartitionKey

  object description extends OptionalStringColumn

  object ingredients extends SetColumn[String]
}
```
The following  CQL statement is valid in order to delete some flags from the ingredients  set.
```
delete ingredients ['ingr2'] from recipes   WHERE  ...
```
Unfortunately it seems that this kind of statement is not supported in prepared mode.

Note: I've seen in doc that the dsl of UPDATE supports  `remove`  or `removeAll`  but this is not available in prepared mode. ( see https://github.com/outworkers/phantom/issues/879)

Thank you in advance.

**Comment by alexflav23** [comment]
@livius-ungureanu Fixed in 2.34.0 coming up on Central.
