### ISSUE TITLE
Phantom DSL does not generate the right alter CQL statement when adding several columns.

### ISSUE THREAD

**Issue by livius-ungureanu** [outworkers/phantom#881]
If several columns are wanted to be added to an existing table using the DSL :
```
recipesTable.alter().add("likes",  "int").add("img", "blob")
```

the DSL will generate:
```
ALTER TABLE  recipes ADD  likes int  ADD  img  blob;
```
which is not CQL valid.

Note:
 C* started to support multiple columns addition only starting with C* 3.6(See https://issues.apache.org/jira/browse/CASSANDRA-10411).

But even after 3.6 the new CQL would be:
ALTER TABLE recipes ADD (likes int, img  blob)

Thank you in advance.

**Comment by alexflav23** [comment]
@livius-ungureanu Fixed in https://github.com/outworkers/phantom/pull/888, pending release.
