### ISSUE TITLE
unresolved dependency: com.outworkers#phantom-udt_2.12;0.16.0: not found

### ISSUE THREAD

**Issue by Rajitha15** [outworkers/phantom#882]
Hi team, 
we are facing this issue today , earlier it used to work, not sure the subscription expired or any other issue?please check and let us know. We are blocked due to this.

**Comment by Rajitha15** [comment]
we identified this issue is due to subscription expired. but now we renew the subscription and i could log in to the site with login credentials https://bintray.com/websudos/oss-releases/phantom-udt.
But still we get the error while building the jar. Please resolve this issue ASAP. Let me know if you need anything.

thanks

**Comment by alexflav23** [comment]
Hi @Rajitha15 Please try adding the latest oss resolver as well `Resolver.bintrayRepo("outworkers", "oss-releases")`, and let me know if you still have issues. The latest version of pro is 0.35.0 and the latest version of phantom is 2.33.0, so it could also be  useful upgrade.

**Comment by Rajitha15** [comment]
@alexflav23 Thanks for the resolution, but we have code in production also, how can we resolve this issue without doing any changes? and we don't have any information about adding the resolver to the phantom pro.

**Comment by alexflav23** [comment]
HI @Rajitha15, we are going to fix this today.

**Comment by Rajitha15** [comment]
@alexflav23 Backward compatability is not yet supportedp plz let me know once you fix this issue.

**Comment by alexflav23** [comment]
Hi @Rajitha15 Please try again now.

**Comment by Rajitha15** [comment]
thanks it is working now.
