### ISSUE TITLE
Prepared statement TTL in update query

### ISSUE THREAD

**Issue by fggarcia** [outworkers/phantom#885]
When I try to write prepared for this query:

````
update.where(_.searchId eqs searchId).and(_.searchTime eqs searchTime).ttl(modifyTtlToDeleteInSeconds)
````

```
    val updateTTL = update
      .where(_.searchId eqs ?)
      .and(_.searchTime eqs ?)
      .ttl(?)
      .consistencyLevel_=(ConsistencyLevel.LOCAL_QUORUM)
      .prepare()
```

Phantom not support ttl prepared statement for update query.

**Comment by alexflav23** [comment]
Fixed in https://github.com/outworkers/phantom/pull/886.

**Comment by fggarcia** [comment]
Hi @alexflav23 

I appreciate your work and quickly response to the issue.

In the example, I wanted to say that i want only upgrade the ttl ( i upgrade to 2.35.0)

Unlees i set "modify" method, i can't set ttl(?)

For example:

    val updateTtlPreparedStatement = update
      .where(_.searchId eqs ?)
      .and(_.searchTime eqs ?)
      .ttl(?)
      .consistencyLevel_=(ConsistencyLevel.LOCAL_QUORUM)
      .prepare()

is it that possible?

**Comment by fggarcia** [comment]
Hi @alexflav23 

Sorry for write to you again.

I only want to know if you read last comment about the issue?

**Comment by alexflav23** [comment]
Hi @fggarcia Makes sense, we are going to re-adjust the implementation of `UpdateQuery` to eliminate some of the duplication we have internally in the code and support prepared `ttl` without the now required `modify` clause.

**Comment by fggarcia** [comment]
Hi @fggarcia Thanks you so much!!

**Comment by fggarcia** [comment]
Hi @alexflav23, can you reopen this issue?

**Comment by fggarcia** [comment]
Hi @alexflav23 

Sorry for write to you again.

Can you reopen this issue?

**Comment by alexflav23** [comment]
@fggarcia I picked this up today.

```
    lazy val updateWithTTL = db.verizonSchema.update
      .where(_.uid eqs ?)
      .ttl(?)
      .prepareAsync()
```

Looks like this is not possible in Cassandra.

```
UPDATE phantom.verizonSchema USING TTL ? WHERE uid = ?;
[info] - should allow using TTL in prepared update statements without a modify clause *** FAILED ***
[info]   The future returned an exception of type: com.datastax.driver.core.exceptions.SyntaxError, with message: line 1:41 mismatched input 'WHERE' expecting K_SET (...phantom.verizonSchema USING TTL ? [WHERE]...). (PreparedUpdateQueryTest.scala:292)
```

Judging by the ANTLR grammar error, Cassandra does not support this. If it does, please send me the CQL queries working in the terminal, and we can pick this up again. In the meantime, I'm going to close this ticket as unfortunately it doesn't look to be a working Cassandra feature.
