### ISSUE TITLE
How to update or search Cassandra table with multiple fields that are not a Partition Key

### ISSUE THREAD

**Issue by itsursujit** [outworkers/phantom#899]
Hello,

I was trying to connect Phantom driver to scala. I'm able to insert data to the cassandra table. But when I tried to search or update table by name or some field other than ID(PartitionKey), I couldn't do that.

Please suggest one how can I achieve the solution?

**Comment by alexflav23** [comment]
Here are some examples.

https://github.com/outworkers/phantom/blob/develop/phantom-dsl/src/test/scala/com/outworkers/phantom/builder/query/db/crud/UpdateQueryTest.scala#L44

**Comment by itsursujit** [comment]
Thank you for quick response. I checked the file but the query is using `pKey` which I believe is PartitionKey.

**Comment by alexflav23** [comment]
@itsursujit That's how Cassandra works. Maybe spend some time reading about data modelling in Cassandra. https://medium.com/outworkers

**Comment by alexflav23** [comment]
@itsursujit This specifically might help you: https://medium.com/outworkers/at-outworkers-cassandra-and-datastax-enterprise-are-core-technologies-in-our-area-of-competence-4a1df2eb718d.

Otherwise read the docs on how to use SASI indexes, secondary indexes etc.

**Comment by sujit-baniya** [comment]
Great! Thank you
