### ISSUE TITLE
Scala 2.13

### ISSUE THREAD

**Issue by antonkulaga** [outworkers/phantom#901]
Could you please add Scala 2.13 support?

**Comment by jan-pieter** [comment]
+1, for us this is one of the last libraries blocking our upgrade to Scala 2.13. Perhaps this issue can be used to track the progress (and list missing Scala 2.13 dependencies?)

**Comment by alexflav23** [comment]
Hi @antonkulaga @jan-pieter This is being considered as we speak, there are significant changes, and we're hoping to come up with a timeline for this change within the next few days.

**Comment by stsatlantis** [comment]
@alexflav23 I think as soon as there is a timeline it can be picked up by the community to help :) I'm looking forward to it, and also looking forward to helping.

**Comment by bharath12345** [comment]
any update on this?

**Comment by alexflav23** [comment]
@antonkulaga @jan-pieter @stsatlantis @bharath12345 Scala 2.13 support is now available as part of Phantom 2.50.0, to be published to Maven Central later today. There should be no changes to the codebase as part of this upgrade, but please let me know if there are issues.
