### ISSUE TITLE
Table not created after another table was created with a tableName overridden

### ISSUE THREAD

**Issue by antoniomaccioni** [outworkers/phantom#902]
I noticed the following behaviour, where _Scenario 1_ works fine and in _Scenario 2_  _new_table_2_ is not auto-created. The two scenarios should be equivalent.

**Scenario 1**
```
object table_1 extends Table_1 with connector.Connector
  
object table_2 extends Table_2 with connector.Connector {
    override def tableName = "new_table_2"
  }
```

**Scenario 2**
```
object table_2 extends Table_2 with connector.Connector {
    override def tableName = "new_table_2"
  }

object table_1 extends Table_1 with connector.Connector
```

**Comment by alexflav23** [comment]
Hi @antoniomaccioni Can you provide a full code sample? There's something else going on here, we have never experienced issues with auto-creation, the table order is irrelevant. Please provide an example I can execute where the issue can be reproduced.

**Comment by antoniomaccioni** [comment]
Hey @alexflav23 . Unfortunately, I cannot share the full code. If you tell me exactly what else you would be interested in checking I might give it to you "anonymyzed"

**Comment by alexflav23** [comment]
@antoniomaccioni Can you provide a minimal subset? I want to see how the tables get initialised, feel free to remove any proprietary information about specific package names and so on.

**Comment by alexflav23** [comment]
@antoniomaccioni Any news on this? Is this something you have been able to resolve?
