### ISSUE TITLE
scala.NotImplementedError: an implementation is missing at runtime

### ISSUE THREAD

**Issue by eugenemiretsky** [outworkers/phantom#903]
```scala
import com.outworkers.phantom.jdk8._

trait TravelTable extends Table[TravelTable, TravelEvent] with TravelRepository {

  override val tableName = "travel"

  object customerId extends StringColumn with PartitionKey

  object createdAt extends Col[ZonedDateTime] with ClusteringOrder with Descending

  object id extends StringColumn

  object subType extends StringColumn

  object sourceCity extends StringColumn

  object destinationCity extends StringColumn

  object verticalId extends SmallIntColumn

  object startDate extends Col[JdkLocalDate]

  private lazy val preparedGet =
    select
      .where(_.customerId eqs ?)
      .consistencyLevel_=(ConsistencyLevel.ONE)
      .prepare()

  def get(customerId: CustomerId): Future[Seq[TravelEvent]] = {

    logger.debug(s"TravelTable get $customerId")

     val res = preparedGet.bind(customerId.toString).fetch().recover {
       case NonFatal(t) =>
        logger.warn(s"failed to fetch from cassandra with error $t  ${t.getCause} ${t.printStackTrace}")
         throw t
     }
    res.foreach {r => logger.debug(s"TravelTable get for $customerId res is $r $r.")}
    res
  }
}
```

Calling get fails with scala.NotImplementedError: an implementation is missing at runtime. Not quite sure which field is causing it yet, but more importantly, shouldn't it be caught in compile time?

**Comment by eugenemiretsky** [comment]
This is my case class

`
case class TravelEvent(
  `type`: String,
  subType: String,
  id: Option[String],
  createdAt: DateTime,
  customerId: String,
  sourceCity: String,
  destinationCity: String,
  verticalId: Short,
  startDate: LocalDate
) extends Event`

**Comment by alexflav23** [comment]
@eugenemiretsky The runtime failure means only one thing, phantom couldn't match your columns to your case class somehow.  Have a look at the docs here for [How to do advanced debugging](https://github.com/outworkers/phantom/blob/develop/docs/basics/debugging.md#comoutworkersphantommacrosdebugoptionsshowtrees-flag), they should help you print out everything you need.

Apologies for the delay in closing this.
