### ISSUE TITLE
New entries sometimes are null when fetched

### ISSUE THREAD

**Issue by Funmbi24** [outworkers/phantom#904]
Hi guys, so this is an issue I've been experiencing for a few weeks now. For some reason (node failure or something else I'm not sure), when I insert into CassyDb and try to fetch, the results sometimes have a null entry. Mostly in a specific field. I would like to know why this and what fixes I can use to solve this. Don't really want to make the column optional. Any help is appreciated, thanks

**Comment by alexflav23** [comment]
Hi @Funmbi24 This has nothing to do with phantom from the likes of it. The most likely out come is you have an issue with your Cassandra configuration, replication factor, or something similar. As this is not really a driver issue, and there is very little we can do without seeing the actual configuration, I will close this issue.
