### ISSUE TITLE
Ambiguous implicit conversions in query column

### ISSUE THREAD

**Issue by kw217** [outworkers/phantom#905]
Our application compiles under Phantom 2.41.0, but fails to compile under 2.42.0, due to a problem with "ambiguous implicit values".

I've managed to work around it, but the workaround ruins the neat look of the Phantom query. Please could you investigate whether this regression can be fixed?

I've reduced the problem to the following case. With the query written as `.and(_.obj eqs rowData.objectId)` (which works fine in 2.41.0), I get
```
[error] ...Example.scala:NNN: ambiguous implicit values:
[error]  both method nsubAmbig1 in package shapeless of type [A, B >: A]=> shapeless.package.<:!<[A,B]
[error]  and method nsubAmbig2 in package shapeless of type [A, B >: A]=> shapeless.package.<:!<[A,B]
[error]  match expected type shapeless.<:!<[col.type,com.outworkers.phantom.keys.Indexed]
[error]       .and(_.obj eqs rowData.objectId)
[error]              ^
```
But with the query written as `.and(t => Indexed.indexedToQueryColumn(t.obj) eqs rowData.objectId)`, it compiles.

The reduced code is as follows:
```scala
import com.outworkers.phantom.dsl.{Table => PhantomTable}
// ... other imports omitted ...

case class ExampleRecord(boxId: UUID,
                         objectId: UUID,
                         data: String)

trait ExampleTable[Table <: PhantomTable[Table, ExampleRecord] with ExampleTable[Table]]
{ this: PhantomTable[Table, ExampleRecord] =>

  def box : TimeUUIDColumn with PartitionKey
  def obj : TimeUUIDColumn with PrimaryKey with ClusteringOrder with Ascending
  def dat : StringColumn

  def deleteQuery(row: ExampleRecord) = {
    val rowData = row.asInstanceOf[ExampleRecord]
    delete
      .where(_.box eqs rowData.boxId)
      .and(_.obj eqs rowData.objectId)  // fails in 2.42.0
//      .and(t => Indexed.indexedToQueryColumn(t.obj) eqs rowData.objectId)  // compiles
      .executableQuery
  }
}
```

If I simply use a class directly (rather than a trait) the problem doesn't arise - but we have multiple similar tables in our database, so we have to use this more general approach.

Thanks!

**Comment by alexflav23** [comment]
Hi @kw217,

```scala
[error] ...Example.scala:NNN: ambiguous implicit values:
[error]  both method nsubAmbig1 in package shapeless of type [A, B >: A]=> shapeless.package.<:!<[A,B]
[error]  and method nsubAmbig2 in package shapeless of type [A, B >: A]=> shapeless.package.<:!<[A,B]
[error]  match expected type shapeless.<:!<[col.type,com.outworkers.phantom.keys.Indexed]
[error]       .and(_.obj eqs rowData.objectId)
```

This looks to me like an intentional compiler error to produce ambiguity. Somehow the compiler is not clear on whether the column is indexed or not from what I can tell. We don't openly support table inheritance as there are several edge cases that are very tricky to impossible to support with the current macro API, hence I'm not sure what to advise, since the tin always aid "don't use inheritance".

**Comment by kw217** [comment]
OK, thanks @alexflav23, that makes sense. I can work around this so it's not blocking me. Thanks for the explanation - I had forgotten that inheritance was unsupported.
