### ISSUE TITLE
cassandraVersion in class CassandraConnection can throw Exceptions

### ISSUE THREAD

**Issue by jaspervz** [outworkers/phantom#907]
The method cassandraVersion in CassandraConnection throws a RuntimeException when connected to a Cassandra cluster that consists of different versions.

Given the return type of the method, Option[VersionNumber], None as return value would be expected in this case. Actually, None is never returned from this method.

I can make a pull request if the behavior that None is returned when the version can't be determined is the desired behavior.

**Comment by alexflav23** [comment]
@jaspervz Sounds good, but in spirit of not breaking existing API, could you instead add an additional `cassandraVersionOpt` method, that will behave exactly as you describe? There may be further downstream issues to fix, as phantom relies on knowing the version to toggle some features, though none critical.

**Comment by jaspervz** [comment]
I created a pull request for this: https://github.com/outworkers/phantom/pull/908 The pull request doesn't build, but this is caused by not being able to resolve a dependency, which is unrelated to the code change.
