### ISSUE TITLE
Auto-application to `()` is deprecated warning in `in` clause

### ISSUE THREAD

**Issue by mikla** [outworkers/phantom#915]
Scala 2.13.3 deprecated auto-application of (non-Java-defined) methods with a single empty parameter list.

I'm getting warn when using `in` clause and I don't really understand how deal with it. Please advice. 

```
object universalId extends UUIDColumn() with PartitionKey {
    override lazy val name = "universal_id"
  }

ids: List[UUID]
```
I'm getting warn here:

```
Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method list,
[error] or remove the empty argument list from its definition (Java-defined methods are exempt).
[error] In Scala 3, an unapplied method like this will be eta-expanded into a function.

select.where(_.universalId in ids)
                                             ^
```                                       

However, similar piece of code that works with `LongColumn` compiles without warning.

Tried to catch Primitive instance for `ListValue` `implicitly` without any luck.

However, 

re-creating instance for `Primitive[ListValue[UUID]]` did help, but it looks kind of verbose:
```
  implicit val instance: Primitive[ListValue[UUID]] =
      ListValue.primitive(Primitives.list()(implicitly[Primitive[UUID]]))

    select.where(_.universalId in ids.toList)
```

**Comment by alexflav23** [comment]
Hi @mikla your problem is here I believe:

```
object universalId extends UUIDColumn() 
```

should be

```
object universalId extends UUIDColumn
```

You will notice the `()` after a column is never used in any phantom example.

**Comment by mikla** [comment]
@alexflav23 thanks for advice, but it didn't help.
However, fun fact: if I change it to `with PrimaryKey` - everything is fine.

**Comment by arixmkii** [comment]
It is caused by phantom-dsl macro here https://github.com/outworkers/phantom/blob/develop/phantom-dsl/src/main/scala/com/outworkers/phantom/builder/primitives/PrimitiveMacro.scala#L69

```
q"""$prefix.Primitives.list[$inner]()"""
```

Same for the `set()` and may be some more.

@alexflav23 Should we open a new issue with updated description?
