### ISSUE TITLE
Issue resolving dependencies with sbt 1.5.0

### ISSUE THREAD

**Issue by arixmkii** [outworkers/phantom#927]
sbt 1.5.0 changed dependency eviction mechanisms and now it fails to build projects using `phantom-dsl`. Error is like
```
[2021-04-06T11:34:40.576Z] [error] sbt.librarymanagement.ResolveException: Error downloading org.typelevel:macro-compat_2.13.4:1.1.1
```

`macro-compat` is now discontinued and seems it was needed only for Scala `2.10.x`, which is now is not in the list for cross compilation.

**Comment by fggarcia** [comment]
@alexflav23 can you check this issue??

**Comment by mikla** [comment]
Hello! 
Would be nice to have it merged, as it blocks upgrading to latest `sbt`.
WDYT?

**Comment by otto-dev** [comment]
> it blocks upgrading to latest sbt.

Even worse for people who are already on the latest `sbt` and want to add `phantom-dsl` as a dependency - project breaks. (it's August now, the `sbt` release has been out for a while)

Please merge the above fix kindly. Thank you!

**Comment by mikla** [comment]
+1

**Comment by otto-dev** [comment]
Temp fix:
```
      libraryDependencies += "com.outworkers" %% "phantom-dsl" % Version.phantom excludeAll (
        ExclusionRule(organization = "org.typelevel"),
      ),
```

**Comment by arixmkii** [comment]
@alexflav23 can we get a release with this fix out?

**Comment by mikla** [comment]
+1

**Comment by andreluistosato** [comment]
+1
